apiVersion: vertexai.gcp.upbound.io/v1beta1
kind: FeatureGroup
metadata:
  annotations:
    meta.upbound.io/example-id: vertexai/v1beta1/featuregroup
  labels:
    testing.upbound.io/example-name: feature_group
  name: feature-group
spec:
  forProvider:
    bigQuery:
    - bigQuerySource:
      - inputUri: bq://${google_bigquery_table.sample_table.project}.${google_bigquery_table.sample_table.dataset_id}.${google_bigquery_table.sample_table.table_id}
      entityIdColumns:
      - feature_id
    description: A sample feature group
    labels:
      label-one: value-one
    region: us-central1
