apiVersion: vertexai.gcp.upbound.io/v1beta1
kind: FeatureGroupFeature
metadata:
  annotations:
    meta.upbound.io/example-id: vertexai/v1beta1/featuregroupfeature
  labels:
    testing.upbound.io/example-name: feature_group_feature
  name: feature-group-feature
spec:
  forProvider:
    description: A sample feature
    featureGroupSelector:
      matchLabels:
        testing.upbound.io/example-name: sample_feature_group
    labels:
      label-one: value-one
    region: us-central1

---

apiVersion: vertexai.gcp.upbound.io/v1beta1
kind: FeatureGroup
metadata:
  annotations:
    meta.upbound.io/example-id: vertexai/v1beta1/featuregroupfeature
  labels:
    testing.upbound.io/example-name: sample_feature_group
  name: sample-feature-group
spec:
  forProvider:
    bigQuery:
    - bigQuerySource:
      - inputUri: bq://${google_bigquery_table.sample_table.project}.${google_bigquery_table.sample_table.dataset_id}.${google_bigquery_table.sample_table.table_id}
      entityIdColumns:
      - feature_id
    description: A sample feature group
    labels:
      label-one: value-one
    region: us-central1
