apiVersion: vertexai.gcp.upbound.io/v1beta1
kind: IndexEndpoint
metadata:
  annotations:
    meta.upbound.io/example-id: vertexai/v1beta1/indexendpoint
  labels:
    testing.upbound.io/example-name: index_endpoint
  name: index-endpoint
spec:
  forProvider:
    description: A sample vertex endpoint
    displayName: sample-endpoint
    labels:
      label-one: value-one
    network: projects/${data.google_project.project.number}/global/networks/${google_compute_network.vertex_network.name}
    region: us-central1
