apiVersion: vertexai.gcp.upbound.io/v1beta1
kind: Index
metadata:
  annotations:
    meta.upbound.io/example-id: vertexai/v1beta1/index
  labels:
    testing.upbound.io/example-name: index
  name: index
spec:
  forProvider:
    description: index for test
    displayName: test-index
    encryptionSpec:
    - kmsKeyName: kms-name
    indexUpdateMethod: BATCH_UPDATE
    labels:
      foo: bar
    metadata:
    - config:
      - algorithmConfig:
        - treeAhConfig:
          - leafNodeEmbeddingCount: 500
            leafNodesToSearchPercent: 7
        approximateNeighborsCount: 150
        dimensions: 2
        distanceMeasureType: DOT_PRODUCT_DISTANCE
        shardSize: SHARD_SIZE_SMALL
      contentsDeltaUri: gs://${google_storage_bucket.bucket.name}/contents
    provider: ${google-beta}
    region: us-central1
