apiVersion: vertexai.gcp.upbound.io/v1beta1
kind: IndexEndpointDeployedIndex
metadata:
  annotations:
    meta.upbound.io/example-id: vertexai/v1beta1/indexendpointdeployedindex
  labels:
    testing.upbound.io/example-name: basic_deployed_index
  name: basic-deployed-index
spec:
  forProvider:
    deployedIndexAuthConfig:
    - authProvider:
      - allowedIssuers:
        - ${google_service_account.sa.email}
        audiences:
        - 123456-my-app
    displayName: vertex-deployed-index
    enableAccessLogging: false
    indexEndpointSelector:
      matchLabels:
        testing.upbound.io/example-name: vertex_index_endpoint_deployed
    indexSelector:
      matchLabels:
        testing.upbound.io/example-name: index
    region: us-central1
    reservedIpRanges:
    - vertex-ai-range

---

apiVersion: vertexai.gcp.upbound.io/v1beta1
kind: Index
metadata:
  annotations:
    meta.upbound.io/example-id: vertexai/v1beta1/indexendpointdeployedindex
  labels:
    testing.upbound.io/example-name: index
  name: index
spec:
  forProvider:
    description: index for test
    displayName: test-index
    indexUpdateMethod: BATCH_UPDATE
    labels:
      foo: bar
    metadata:
    - config:
      - algorithmConfig:
        - treeAhConfig:
          - leafNodeEmbeddingCount: 500
            leafNodesToSearchPercent: 7
        approximateNeighborsCount: 150
        dimensions: 2
        distanceMeasureType: DOT_PRODUCT_DISTANCE
        shardSize: SHARD_SIZE_SMALL
      contentsDeltaUri: bucket-name
    region: us-central1

---

apiVersion: vertexai.gcp.upbound.io/v1beta1
kind: IndexEndpoint
metadata:
  annotations:
    meta.upbound.io/example-id: vertexai/v1beta1/indexendpointdeployedindex
  labels:
    testing.upbound.io/example-name: vertex_index_endpoint_deployed
  name: vertex-index-endpoint-deployed
spec:
  forProvider:
    description: A sample vertex endpoint
    displayName: sample-endpoint
    labels:
      label-one: value-one
    network: projects/${data.google_project.project.number}/global/networks/${data.google_compute_network.vertex_network.name}
    region: us-central1
