# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: vertexai.gcp.upbound.io/v1beta1
kind: IndexEndpoint
metadata:
  annotations:
    meta.upbound.io/example-id: vertexai/v1beta1/indexendpoint
  labels:
    testing.upbound.io/example-name: index_endpoint
  name: index-endpoint
spec:
  forProvider:
    description: A sample vertex endpoint
    displayName: sample-endpoint
    labels:
      label-one: value-one
    network: projects/${data.google_project.project.number}/global/networks/${google_compute_network.vertex_network.name}
    region: us-central1

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: GlobalAddress
metadata:
  annotations:
    meta.upbound.io/example-id: vertexai/v1beta1/indexendpoint
  labels:
    testing.upbound.io/example-name: vertex_range
  name: vertex-range
spec:
  forProvider:
    addressType: INTERNAL
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: vertex_network
    prefixLength: 24
    purpose: VPC_PEERING

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: vertexai/v1beta1/indexendpoint
  labels:
    testing.upbound.io/example-name: vertex_network
  name: vertex-network
spec:
  forProvider: {}

---

apiVersion: servicenetworking.gcp.upbound.io/v1beta1
kind: Connection
metadata:
  annotations:
    meta.upbound.io/example-id: vertexai/v1beta1/indexendpoint
  labels:
    testing.upbound.io/example-name: vertex_vpc_connection
  name: vertex-vpc-connection
spec:
  forProvider:
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: vertex_network
    reservedPeeringRangesRefs:
    - name: vertex_range
    service: servicenetworking.googleapis.com
