// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CacheConfigInitParameters struct {

	// If set to true, disables GenAI caching. Otherwise caching is enabled.
	DisableCache *bool `json:"disableCache,omitempty" tf:"disable_cache,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`
}

type CacheConfigObservation struct {

	// If set to true, disables GenAI caching. Otherwise caching is enabled.
	DisableCache *bool `json:"disableCache,omitempty" tf:"disable_cache,omitempty"`

	// an identifier for the resource with format projects/{{project}}/cacheConfig
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Identifier. name of the cache config. Format: - projects/{project}/cacheConfig.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`
}

type CacheConfigParameters struct {

	// If set to true, disables GenAI caching. Otherwise caching is enabled.
	// +kubebuilder:validation:Optional
	DisableCache *bool `json:"disableCache,omitempty" tf:"disable_cache,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`
}

// CacheConfigSpec defines the desired state of CacheConfig
type CacheConfigSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CacheConfigParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CacheConfigInitParameters `json:"initProvider,omitempty"`
}

// CacheConfigStatus defines the observed state of CacheConfig.
type CacheConfigStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CacheConfigObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CacheConfig is the Schema for the CacheConfigs API. Config of GenAI caching features.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,gcp}
type CacheConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.disableCache) || (has(self.initProvider) && has(self.initProvider.disableCache))",message="spec.forProvider.disableCache is a required parameter"
	Spec   CacheConfigSpec   `json:"spec"`
	Status CacheConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CacheConfigList contains a list of CacheConfigs
type CacheConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CacheConfig `json:"items"`
}

// Repository type metadata.
var (
	CacheConfig_Kind             = "CacheConfig"
	CacheConfig_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CacheConfig_Kind}.String()
	CacheConfig_KindAPIVersion   = CacheConfig_Kind + "." + CRDGroupVersion.String()
	CacheConfig_GroupVersionKind = CRDGroupVersion.WithKind(CacheConfig_Kind)
)

func init() {
	SchemeBuilder.Register(&CacheConfig{}, &CacheConfigList{})
}
