// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by angryjet. DO NOT EDIT.
// Code transformed by upjet. DO NOT EDIT.

package v1beta1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	xpresource "github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	apisresolver "github.com/upbound/provider-gcp/internal/apis"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

func (mg *FeaturestoreEntitytype) ResolveReferences( // ResolveReferences of this FeaturestoreEntitytype.
	ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("vertexai.gcp.upbound.io", "v1beta1", "Featurestore", "FeaturestoreList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Featurestore),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.FeaturestoreRef,
			Selector:     mg.Spec.ForProvider.FeaturestoreSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Featurestore")
	}
	mg.Spec.ForProvider.Featurestore = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.FeaturestoreRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("vertexai.gcp.upbound.io", "v1beta1", "Featurestore", "FeaturestoreList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Featurestore),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.FeaturestoreRef,
			Selector:     mg.Spec.InitProvider.FeaturestoreSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Featurestore")
	}
	mg.Spec.InitProvider.Featurestore = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.FeaturestoreRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this IndexEndpointDeployedIndex.
func (mg *IndexEndpointDeployedIndex) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("vertexai.gcp.upbound.io", "v1beta1", "Index", "IndexList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Index),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.IndexRef,
			Selector:     mg.Spec.ForProvider.IndexSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Index")
	}
	mg.Spec.ForProvider.Index = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.IndexRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("vertexai.gcp.upbound.io", "v1beta1", "IndexEndpoint", "IndexEndpointList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.IndexEndpoint),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.IndexEndpointRef,
			Selector:     mg.Spec.ForProvider.IndexEndpointSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.IndexEndpoint")
	}
	mg.Spec.ForProvider.IndexEndpoint = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.IndexEndpointRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("vertexai.gcp.upbound.io", "v1beta1", "Index", "IndexList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Index),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.IndexRef,
			Selector:     mg.Spec.InitProvider.IndexSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Index")
	}
	mg.Spec.InitProvider.Index = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.IndexRef = rsp.ResolvedReference

	return nil
}
