// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type FeatureGroupFeatureInitParameters struct {

	// The description of the FeatureGroup.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The labels with user-defined metadata to organize your FeatureGroup.
	// Note: This field is non-authoritative, and will only manage the labels present in your configuration.
	// Please refer to the field effective_labels for all of the labels present on the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The name of the BigQuery Table/View column hosting data for this version. If no value is provided, will use featureId.
	VersionColumnName *string `json:"versionColumnName,omitempty" tf:"version_column_name,omitempty"`
}

type FeatureGroupFeatureObservation struct {

	// The timestamp of when the FeatureGroup was created in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to nine fractional digits.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// The description of the FeatureGroup.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +mapType=granular
	EffectiveLabels map[string]*string `json:"effectiveLabels,omitempty" tf:"effective_labels,omitempty"`

	// The name of the Feature Group.
	FeatureGroup *string `json:"featureGroup,omitempty" tf:"feature_group,omitempty"`

	// an identifier for the resource with format projects/{{project}}/locations/{{region}}/featureGroups/{{feature_group}}/features/{{name}}
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The labels with user-defined metadata to organize your FeatureGroup.
	// Note: This field is non-authoritative, and will only manage the labels present in your configuration.
	// Please refer to the field effective_labels for all of the labels present on the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The region for the resource. It should be the same as the feature group's region.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The combination of labels configured directly on the resource
	// and default labels configured on the provider.
	// +mapType=granular
	TerraformLabels map[string]*string `json:"terraformLabels,omitempty" tf:"terraform_labels,omitempty"`

	// The timestamp of when the FeatureGroup was last updated in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to nine fractional digits.
	UpdateTime *string `json:"updateTime,omitempty" tf:"update_time,omitempty"`

	// The name of the BigQuery Table/View column hosting data for this version. If no value is provided, will use featureId.
	VersionColumnName *string `json:"versionColumnName,omitempty" tf:"version_column_name,omitempty"`
}

type FeatureGroupFeatureParameters struct {

	// The description of the FeatureGroup.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the Feature Group.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/apis/namespaced/vertexai/v1beta1.FeatureGroup
	// +kubebuilder:validation:Optional
	FeatureGroup *string `json:"featureGroup,omitempty" tf:"feature_group,omitempty"`

	// Reference to a FeatureGroup in vertexai to populate featureGroup.
	// +kubebuilder:validation:Optional
	FeatureGroupRef *v1.NamespacedReference `json:"featureGroupRef,omitempty" tf:"-"`

	// Selector for a FeatureGroup in vertexai to populate featureGroup.
	// +kubebuilder:validation:Optional
	FeatureGroupSelector *v1.NamespacedSelector `json:"featureGroupSelector,omitempty" tf:"-"`

	// The labels with user-defined metadata to organize your FeatureGroup.
	// Note: This field is non-authoritative, and will only manage the labels present in your configuration.
	// Please refer to the field effective_labels for all of the labels present on the resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The region for the resource. It should be the same as the feature group's region.
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`

	// The name of the BigQuery Table/View column hosting data for this version. If no value is provided, will use featureId.
	// +kubebuilder:validation:Optional
	VersionColumnName *string `json:"versionColumnName,omitempty" tf:"version_column_name,omitempty"`
}

// FeatureGroupFeatureSpec defines the desired state of FeatureGroupFeature
type FeatureGroupFeatureSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            FeatureGroupFeatureParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FeatureGroupFeatureInitParameters `json:"initProvider,omitempty"`
}

// FeatureGroupFeatureStatus defines the observed state of FeatureGroupFeature.
type FeatureGroupFeatureStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FeatureGroupFeatureObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FeatureGroupFeature is the Schema for the FeatureGroupFeatures API. Vertex AI Feature Group Feature is feature metadata information.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gcp}
type FeatureGroupFeature struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              FeatureGroupFeatureSpec   `json:"spec"`
	Status            FeatureGroupFeatureStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FeatureGroupFeatureList contains a list of FeatureGroupFeatures
type FeatureGroupFeatureList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FeatureGroupFeature `json:"items"`
}

// Repository type metadata.
var (
	FeatureGroupFeature_Kind             = "FeatureGroupFeature"
	FeatureGroupFeature_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FeatureGroupFeature_Kind}.String()
	FeatureGroupFeature_KindAPIVersion   = FeatureGroupFeature_Kind + "." + CRDGroupVersion.String()
	FeatureGroupFeature_GroupVersionKind = CRDGroupVersion.WithKind(FeatureGroupFeature_Kind)
)

func init() {
	SchemeBuilder.Register(&FeatureGroupFeature{}, &FeatureGroupFeatureList{})
}
