// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type FeaturestoreEntitytypeFeatureInitParameters struct {

	// Description of the feature.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the Featurestore to use, in the format projects/{project}/locations/{location}/featurestores/{featurestore}/entityTypes/{entitytype}.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/namespaced/vertexai/v1beta1.FeaturestoreEntitytype
	Entitytype *string `json:"entitytype,omitempty" tf:"entitytype,omitempty"`

	// Reference to a FeaturestoreEntitytype in vertexai to populate entitytype.
	// +kubebuilder:validation:Optional
	EntitytypeRef *v1.NamespacedReference `json:"entitytypeRef,omitempty" tf:"-"`

	// Selector for a FeaturestoreEntitytype in vertexai to populate entitytype.
	// +kubebuilder:validation:Optional
	EntitytypeSelector *v1.NamespacedSelector `json:"entitytypeSelector,omitempty" tf:"-"`

	// A set of key/value label pairs to assign to the feature.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the feature. The feature can be up to 64 characters long and can consist only of ASCII Latin letters A-Z and a-z, underscore(_), and ASCII digits 0-9 starting with a letter. The value will be unique given an entity type.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Type of Feature value. Immutable. https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.featurestores.entityTypes.features#ValueType
	ValueType *string `json:"valueType,omitempty" tf:"value_type,omitempty"`
}

type FeaturestoreEntitytypeFeatureObservation struct {

	// The timestamp of when the entity type was created in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to nine fractional digits.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// Description of the feature.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// for all of the labels present on the resource.
	// +mapType=granular
	EffectiveLabels map[string]*string `json:"effectiveLabels,omitempty" tf:"effective_labels,omitempty"`

	// The name of the Featurestore to use, in the format projects/{project}/locations/{location}/featurestores/{featurestore}/entityTypes/{entitytype}.
	Entitytype *string `json:"entitytype,omitempty" tf:"entitytype,omitempty"`

	// Used to perform consistent read-modify-write updates.
	Etag *string `json:"etag,omitempty" tf:"etag,omitempty"`

	// an identifier for the resource with format {{entitytype}}/features/{{name}}
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A set of key/value label pairs to assign to the feature.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the feature. The feature can be up to 64 characters long and can consist only of ASCII Latin letters A-Z and a-z, underscore(_), and ASCII digits 0-9 starting with a letter. The value will be unique given an entity type.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The combination of labels configured directly on the resource
	// and default labels configured on the provider.
	// +mapType=granular
	TerraformLabels map[string]*string `json:"terraformLabels,omitempty" tf:"terraform_labels,omitempty"`

	// The timestamp when the entity type was most recently updated in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to nine fractional digits.
	UpdateTime *string `json:"updateTime,omitempty" tf:"update_time,omitempty"`

	// Type of Feature value. Immutable. https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.featurestores.entityTypes.features#ValueType
	ValueType *string `json:"valueType,omitempty" tf:"value_type,omitempty"`
}

type FeaturestoreEntitytypeFeatureParameters struct {

	// Description of the feature.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the Featurestore to use, in the format projects/{project}/locations/{location}/featurestores/{featurestore}/entityTypes/{entitytype}.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/namespaced/vertexai/v1beta1.FeaturestoreEntitytype
	// +kubebuilder:validation:Optional
	Entitytype *string `json:"entitytype,omitempty" tf:"entitytype,omitempty"`

	// Reference to a FeaturestoreEntitytype in vertexai to populate entitytype.
	// +kubebuilder:validation:Optional
	EntitytypeRef *v1.NamespacedReference `json:"entitytypeRef,omitempty" tf:"-"`

	// Selector for a FeaturestoreEntitytype in vertexai to populate entitytype.
	// +kubebuilder:validation:Optional
	EntitytypeSelector *v1.NamespacedSelector `json:"entitytypeSelector,omitempty" tf:"-"`

	// A set of key/value label pairs to assign to the feature.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The name of the feature. The feature can be up to 64 characters long and can consist only of ASCII Latin letters A-Z and a-z, underscore(_), and ASCII digits 0-9 starting with a letter. The value will be unique given an entity type.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Type of Feature value. Immutable. https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.featurestores.entityTypes.features#ValueType
	// +kubebuilder:validation:Optional
	ValueType *string `json:"valueType,omitempty" tf:"value_type,omitempty"`
}

// FeaturestoreEntitytypeFeatureSpec defines the desired state of FeaturestoreEntitytypeFeature
type FeaturestoreEntitytypeFeatureSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            FeaturestoreEntitytypeFeatureParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FeaturestoreEntitytypeFeatureInitParameters `json:"initProvider,omitempty"`
}

// FeaturestoreEntitytypeFeatureStatus defines the observed state of FeaturestoreEntitytypeFeature.
type FeaturestoreEntitytypeFeatureStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FeaturestoreEntitytypeFeatureObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FeaturestoreEntitytypeFeature is the Schema for the FeaturestoreEntitytypeFeatures API. Feature Metadata information that describes an attribute of an entity type.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gcp}
type FeaturestoreEntitytypeFeature struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.valueType) || (has(self.initProvider) && has(self.initProvider.valueType))",message="spec.forProvider.valueType is a required parameter"
	Spec   FeaturestoreEntitytypeFeatureSpec   `json:"spec"`
	Status FeaturestoreEntitytypeFeatureStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FeaturestoreEntitytypeFeatureList contains a list of FeaturestoreEntitytypeFeatures
type FeaturestoreEntitytypeFeatureList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FeaturestoreEntitytypeFeature `json:"items"`
}

// Repository type metadata.
var (
	FeaturestoreEntitytypeFeature_Kind             = "FeaturestoreEntitytypeFeature"
	FeaturestoreEntitytypeFeature_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FeaturestoreEntitytypeFeature_Kind}.String()
	FeaturestoreEntitytypeFeature_KindAPIVersion   = FeaturestoreEntitytypeFeature_Kind + "." + CRDGroupVersion.String()
	FeaturestoreEntitytypeFeature_GroupVersionKind = CRDGroupVersion.WithKind(FeaturestoreEntitytypeFeature_Kind)
)

func init() {
	SchemeBuilder.Register(&FeaturestoreEntitytypeFeature{}, &FeaturestoreEntitytypeFeatureList{})
}
