// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BigQueryInitParameters struct {

	// The BigQuery source URI that points to either a BigQuery Table or View.
	// Structure is documented below.
	BigQuerySource *BigQuerySourceInitParameters `json:"bigQuerySource,omitempty" tf:"big_query_source,omitempty"`

	// Columns to construct entityId / row keys. If not provided defaults to entityId.
	EntityIDColumns []*string `json:"entityIdColumns,omitempty" tf:"entity_id_columns,omitempty"`
}

type BigQueryObservation struct {

	// The BigQuery source URI that points to either a BigQuery Table or View.
	// Structure is documented below.
	BigQuerySource *BigQuerySourceObservation `json:"bigQuerySource,omitempty" tf:"big_query_source,omitempty"`

	// Columns to construct entityId / row keys. If not provided defaults to entityId.
	EntityIDColumns []*string `json:"entityIdColumns,omitempty" tf:"entity_id_columns,omitempty"`
}

type BigQueryParameters struct {

	// The BigQuery source URI that points to either a BigQuery Table or View.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	BigQuerySource *BigQuerySourceParameters `json:"bigQuerySource" tf:"big_query_source,omitempty"`

	// Columns to construct entityId / row keys. If not provided defaults to entityId.
	// +kubebuilder:validation:Optional
	EntityIDColumns []*string `json:"entityIdColumns,omitempty" tf:"entity_id_columns,omitempty"`
}

type BigQuerySourceInitParameters struct {

	// BigQuery URI to a table, up to 2000 characters long. For example: bq://projectId.bqDatasetId.bqTableId.
	InputURI *string `json:"inputUri,omitempty" tf:"input_uri,omitempty"`
}

type BigQuerySourceObservation struct {

	// BigQuery URI to a table, up to 2000 characters long. For example: bq://projectId.bqDatasetId.bqTableId.
	InputURI *string `json:"inputUri,omitempty" tf:"input_uri,omitempty"`
}

type BigQuerySourceParameters struct {

	// BigQuery URI to a table, up to 2000 characters long. For example: bq://projectId.bqDatasetId.bqTableId.
	// +kubebuilder:validation:Optional
	InputURI *string `json:"inputUri" tf:"input_uri,omitempty"`
}

type FeatureGroupInitParameters struct {

	// Indicates that features for this group come from BigQuery Table/View. By default treats the source as a sparse time series source, which is required to have an entityId and a feature_timestamp column in the source.
	// Structure is documented below.
	BigQuery *BigQueryInitParameters `json:"bigQuery,omitempty" tf:"big_query,omitempty"`

	// The description of the FeatureGroup.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The labels with user-defined metadata to organize your FeatureGroup.
	// Note: This field is non-authoritative, and will only manage the labels present in your configuration.
	// Please refer to the field effective_labels for all of the labels present on the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`
}

type FeatureGroupObservation struct {

	// Indicates that features for this group come from BigQuery Table/View. By default treats the source as a sparse time series source, which is required to have an entityId and a feature_timestamp column in the source.
	// Structure is documented below.
	BigQuery *BigQueryObservation `json:"bigQuery,omitempty" tf:"big_query,omitempty"`

	// The timestamp of when the FeatureGroup was created in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to nine fractional digits.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// The description of the FeatureGroup.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +mapType=granular
	EffectiveLabels map[string]*string `json:"effectiveLabels,omitempty" tf:"effective_labels,omitempty"`

	// Used to perform consistent read-modify-write updates.
	Etag *string `json:"etag,omitempty" tf:"etag,omitempty"`

	// an identifier for the resource with format projects/{{project}}/locations/{{region}}/featureGroups/{{name}}
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The labels with user-defined metadata to organize your FeatureGroup.
	// Note: This field is non-authoritative, and will only manage the labels present in your configuration.
	// Please refer to the field effective_labels for all of the labels present on the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The region of feature group. eg us-central1
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The combination of labels configured directly on the resource
	// and default labels configured on the provider.
	// +mapType=granular
	TerraformLabels map[string]*string `json:"terraformLabels,omitempty" tf:"terraform_labels,omitempty"`

	// The timestamp of when the FeatureGroup was last updated in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to nine fractional digits.
	UpdateTime *string `json:"updateTime,omitempty" tf:"update_time,omitempty"`
}

type FeatureGroupParameters struct {

	// Indicates that features for this group come from BigQuery Table/View. By default treats the source as a sparse time series source, which is required to have an entityId and a feature_timestamp column in the source.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	BigQuery *BigQueryParameters `json:"bigQuery,omitempty" tf:"big_query,omitempty"`

	// The description of the FeatureGroup.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The labels with user-defined metadata to organize your FeatureGroup.
	// Note: This field is non-authoritative, and will only manage the labels present in your configuration.
	// Please refer to the field effective_labels for all of the labels present on the resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The region of feature group. eg us-central1
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`
}

// FeatureGroupSpec defines the desired state of FeatureGroup
type FeatureGroupSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            FeatureGroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FeatureGroupInitParameters `json:"initProvider,omitempty"`
}

// FeatureGroupStatus defines the observed state of FeatureGroup.
type FeatureGroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FeatureGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FeatureGroup is the Schema for the FeatureGroups API. Vertex AI Feature Group.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gcp}
type FeatureGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              FeatureGroupSpec   `json:"spec"`
	Status            FeatureGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FeatureGroupList contains a list of FeatureGroups
type FeatureGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FeatureGroup `json:"items"`
}

// Repository type metadata.
var (
	FeatureGroup_Kind             = "FeatureGroup"
	FeatureGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FeatureGroup_Kind}.String()
	FeatureGroup_KindAPIVersion   = FeatureGroup_Kind + "." + CRDGroupVersion.String()
	FeatureGroup_GroupVersionKind = CRDGroupVersion.WithKind(FeatureGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&FeatureGroup{}, &FeatureGroupList{})
}
