// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AutoScalingInitParameters struct {

	// A percentage of the cluster's CPU capacity. Can be from 10% to 80%. When a cluster's CPU utilization exceeds the target that you have set, Bigtable immediately adds nodes to the cluster. When CPU utilization is substantially lower than the target, Bigtable removes nodes. If not set will default to 50%.
	CPUUtilizationTarget *float64 `json:"cpuUtilizationTarget,omitempty" tf:"cpu_utilization_target,omitempty"`

	// The maximum number of nodes to scale up to. Must be greater than or equal to minNodeCount, and less than or equal to 10 times of 'minNodeCount'.
	MaxNodeCount *float64 `json:"maxNodeCount,omitempty" tf:"max_node_count,omitempty"`

	// The minimum number of nodes to scale down to. Must be greater than or equal to 1.
	MinNodeCount *float64 `json:"minNodeCount,omitempty" tf:"min_node_count,omitempty"`
}

type AutoScalingObservation struct {

	// A percentage of the cluster's CPU capacity. Can be from 10% to 80%. When a cluster's CPU utilization exceeds the target that you have set, Bigtable immediately adds nodes to the cluster. When CPU utilization is substantially lower than the target, Bigtable removes nodes. If not set will default to 50%.
	CPUUtilizationTarget *float64 `json:"cpuUtilizationTarget,omitempty" tf:"cpu_utilization_target,omitempty"`

	// The maximum number of nodes to scale up to. Must be greater than or equal to minNodeCount, and less than or equal to 10 times of 'minNodeCount'.
	MaxNodeCount *float64 `json:"maxNodeCount,omitempty" tf:"max_node_count,omitempty"`

	// The minimum number of nodes to scale down to. Must be greater than or equal to 1.
	MinNodeCount *float64 `json:"minNodeCount,omitempty" tf:"min_node_count,omitempty"`
}

type AutoScalingParameters struct {

	// A percentage of the cluster's CPU capacity. Can be from 10% to 80%. When a cluster's CPU utilization exceeds the target that you have set, Bigtable immediately adds nodes to the cluster. When CPU utilization is substantially lower than the target, Bigtable removes nodes. If not set will default to 50%.
	// +kubebuilder:validation:Optional
	CPUUtilizationTarget *float64 `json:"cpuUtilizationTarget,omitempty" tf:"cpu_utilization_target,omitempty"`

	// The maximum number of nodes to scale up to. Must be greater than or equal to minNodeCount, and less than or equal to 10 times of 'minNodeCount'.
	// +kubebuilder:validation:Optional
	MaxNodeCount *float64 `json:"maxNodeCount" tf:"max_node_count,omitempty"`

	// The minimum number of nodes to scale down to. Must be greater than or equal to 1.
	// +kubebuilder:validation:Optional
	MinNodeCount *float64 `json:"minNodeCount" tf:"min_node_count,omitempty"`
}

type BigtableInitParameters struct {

	// Autoscaling config applied to Bigtable Instance.
	// Structure is documented below.
	AutoScaling *AutoScalingInitParameters `json:"autoScaling,omitempty" tf:"auto_scaling,omitempty"`
}

type BigtableObservation struct {

	// Autoscaling config applied to Bigtable Instance.
	// Structure is documented below.
	AutoScaling *AutoScalingObservation `json:"autoScaling,omitempty" tf:"auto_scaling,omitempty"`
}

type BigtableParameters struct {

	// Autoscaling config applied to Bigtable Instance.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	AutoScaling *AutoScalingParameters `json:"autoScaling" tf:"auto_scaling,omitempty"`
}

type DedicatedServingEndpointInitParameters struct {

	// Private service connect config.
	// Structure is documented below.
	PrivateServiceConnectConfig *DedicatedServingEndpointPrivateServiceConnectConfigInitParameters `json:"privateServiceConnectConfig,omitempty" tf:"private_service_connect_config,omitempty"`
}

type DedicatedServingEndpointObservation struct {

	// Private service connect config.
	// Structure is documented below.
	PrivateServiceConnectConfig *DedicatedServingEndpointPrivateServiceConnectConfigObservation `json:"privateServiceConnectConfig,omitempty" tf:"private_service_connect_config,omitempty"`

	// (Output)
	// Domain name to use for this FeatureOnlineStore
	PublicEndpointDomainName *string `json:"publicEndpointDomainName,omitempty" tf:"public_endpoint_domain_name,omitempty"`

	// (Output)
	// Name of the service attachment resource. Applicable only if private service connect is enabled and after FeatureViewSync is created.
	ServiceAttachment *string `json:"serviceAttachment,omitempty" tf:"service_attachment,omitempty"`
}

type DedicatedServingEndpointParameters struct {

	// Private service connect config.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	PrivateServiceConnectConfig *DedicatedServingEndpointPrivateServiceConnectConfigParameters `json:"privateServiceConnectConfig,omitempty" tf:"private_service_connect_config,omitempty"`
}

type DedicatedServingEndpointPrivateServiceConnectConfigInitParameters struct {

	// If set to true, customers will use private service connection to send request. Otherwise, the connection will set to public endpoint.
	EnablePrivateServiceConnect *bool `json:"enablePrivateServiceConnect,omitempty" tf:"enable_private_service_connect,omitempty"`

	// A list of Projects from which the forwarding rule will target the service attachment.
	ProjectAllowlist []*string `json:"projectAllowlist,omitempty" tf:"project_allowlist,omitempty"`
}

type DedicatedServingEndpointPrivateServiceConnectConfigObservation struct {

	// If set to true, customers will use private service connection to send request. Otherwise, the connection will set to public endpoint.
	EnablePrivateServiceConnect *bool `json:"enablePrivateServiceConnect,omitempty" tf:"enable_private_service_connect,omitempty"`

	// A list of Projects from which the forwarding rule will target the service attachment.
	ProjectAllowlist []*string `json:"projectAllowlist,omitempty" tf:"project_allowlist,omitempty"`
}

type DedicatedServingEndpointPrivateServiceConnectConfigParameters struct {

	// If set to true, customers will use private service connection to send request. Otherwise, the connection will set to public endpoint.
	// +kubebuilder:validation:Optional
	EnablePrivateServiceConnect *bool `json:"enablePrivateServiceConnect" tf:"enable_private_service_connect,omitempty"`

	// A list of Projects from which the forwarding rule will target the service attachment.
	// +kubebuilder:validation:Optional
	ProjectAllowlist []*string `json:"projectAllowlist,omitempty" tf:"project_allowlist,omitempty"`
}

type FeatureOnlineStoreInitParameters struct {

	// Settings for Cloud Bigtable instance that will be created to serve featureValues for all FeatureViews under this FeatureOnlineStore.
	// Structure is documented below.
	Bigtable *BigtableInitParameters `json:"bigtable,omitempty" tf:"bigtable,omitempty"`

	// The dedicated serving endpoint for this FeatureOnlineStore, which is different from common vertex service endpoint. Only need to be set when you choose Optimized storage type or enable EmbeddingManagement. Will use public endpoint by default.
	// Structure is documented below.
	DedicatedServingEndpoint *DedicatedServingEndpointInitParameters `json:"dedicatedServingEndpoint,omitempty" tf:"dedicated_serving_endpoint,omitempty"`

	// If set to true, any FeatureViews and Features for this FeatureOnlineStore will also be deleted.
	ForceDestroy *bool `json:"forceDestroy,omitempty" tf:"force_destroy,omitempty"`

	// The labels with user-defined metadata to organize your feature online stores.
	// Note: This field is non-authoritative, and will only manage the labels present in your configuration.
	// Please refer to the field effective_labels for all of the labels present on the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Settings for the Optimized store that will be created to serve featureValues for all FeatureViews under this FeatureOnlineStore
	Optimized *OptimizedInitParameters `json:"optimized,omitempty" tf:"optimized,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`
}

type FeatureOnlineStoreObservation struct {

	// Settings for Cloud Bigtable instance that will be created to serve featureValues for all FeatureViews under this FeatureOnlineStore.
	// Structure is documented below.
	Bigtable *BigtableObservation `json:"bigtable,omitempty" tf:"bigtable,omitempty"`

	// The timestamp of when the feature online store was created in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to nine fractional digits.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// The dedicated serving endpoint for this FeatureOnlineStore, which is different from common vertex service endpoint. Only need to be set when you choose Optimized storage type or enable EmbeddingManagement. Will use public endpoint by default.
	// Structure is documented below.
	DedicatedServingEndpoint *DedicatedServingEndpointObservation `json:"dedicatedServingEndpoint,omitempty" tf:"dedicated_serving_endpoint,omitempty"`

	// +mapType=granular
	EffectiveLabels map[string]*string `json:"effectiveLabels,omitempty" tf:"effective_labels,omitempty"`

	// Used to perform consistent read-modify-write updates.
	Etag *string `json:"etag,omitempty" tf:"etag,omitempty"`

	// If set to true, any FeatureViews and Features for this FeatureOnlineStore will also be deleted.
	ForceDestroy *bool `json:"forceDestroy,omitempty" tf:"force_destroy,omitempty"`

	// an identifier for the resource with format projects/{{project}}/locations/{{region}}/featureOnlineStores/{{name}}
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The labels with user-defined metadata to organize your feature online stores.
	// Note: This field is non-authoritative, and will only manage the labels present in your configuration.
	// Please refer to the field effective_labels for all of the labels present on the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Settings for the Optimized store that will be created to serve featureValues for all FeatureViews under this FeatureOnlineStore
	Optimized *OptimizedParameters `json:"optimized,omitempty" tf:"optimized,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The region of feature online store. eg us-central1
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The state of the Feature Online Store. See the possible states in this link.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// The combination of labels configured directly on the resource
	// and default labels configured on the provider.
	// +mapType=granular
	TerraformLabels map[string]*string `json:"terraformLabels,omitempty" tf:"terraform_labels,omitempty"`

	// The timestamp of when the feature online store was last updated in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to nine fractional digits.
	UpdateTime *string `json:"updateTime,omitempty" tf:"update_time,omitempty"`
}

type FeatureOnlineStoreParameters struct {

	// Settings for Cloud Bigtable instance that will be created to serve featureValues for all FeatureViews under this FeatureOnlineStore.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	Bigtable *BigtableParameters `json:"bigtable,omitempty" tf:"bigtable,omitempty"`

	// The dedicated serving endpoint for this FeatureOnlineStore, which is different from common vertex service endpoint. Only need to be set when you choose Optimized storage type or enable EmbeddingManagement. Will use public endpoint by default.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	DedicatedServingEndpoint *DedicatedServingEndpointParameters `json:"dedicatedServingEndpoint,omitempty" tf:"dedicated_serving_endpoint,omitempty"`

	// If set to true, any FeatureViews and Features for this FeatureOnlineStore will also be deleted.
	// +kubebuilder:validation:Optional
	ForceDestroy *bool `json:"forceDestroy,omitempty" tf:"force_destroy,omitempty"`

	// The labels with user-defined metadata to organize your feature online stores.
	// Note: This field is non-authoritative, and will only manage the labels present in your configuration.
	// Please refer to the field effective_labels for all of the labels present on the resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Settings for the Optimized store that will be created to serve featureValues for all FeatureViews under this FeatureOnlineStore
	// +kubebuilder:validation:Optional
	Optimized *OptimizedParameters `json:"optimized,omitempty" tf:"optimized,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The region of feature online store. eg us-central1
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`
}

type OptimizedInitParameters struct {
}

type OptimizedObservation struct {
}

type OptimizedParameters struct {
}

// FeatureOnlineStoreSpec defines the desired state of FeatureOnlineStore
type FeatureOnlineStoreSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            FeatureOnlineStoreParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FeatureOnlineStoreInitParameters `json:"initProvider,omitempty"`
}

// FeatureOnlineStoreStatus defines the observed state of FeatureOnlineStore.
type FeatureOnlineStoreStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FeatureOnlineStoreObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FeatureOnlineStore is the Schema for the FeatureOnlineStores API. Vertex AI Feature Online Store provides a centralized repository for serving ML features and embedding indexes at low latency.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gcp}
type FeatureOnlineStore struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              FeatureOnlineStoreSpec   `json:"spec"`
	Status            FeatureOnlineStoreStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FeatureOnlineStoreList contains a list of FeatureOnlineStores
type FeatureOnlineStoreList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FeatureOnlineStore `json:"items"`
}

// Repository type metadata.
var (
	FeatureOnlineStore_Kind             = "FeatureOnlineStore"
	FeatureOnlineStore_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FeatureOnlineStore_Kind}.String()
	FeatureOnlineStore_KindAPIVersion   = FeatureOnlineStore_Kind + "." + CRDGroupVersion.String()
	FeatureOnlineStore_GroupVersionKind = CRDGroupVersion.WithKind(FeatureOnlineStore_Kind)
)

func init() {
	SchemeBuilder.Register(&FeatureOnlineStore{}, &FeatureOnlineStoreList{})
}
