// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type FeatureGroupsInitParameters struct {

	// Identifier of the feature group.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/apis/namespaced/vertexai/v1beta1.FeatureGroup
	FeatureGroupID *string `json:"featureGroupId,omitempty" tf:"feature_group_id,omitempty"`

	// Reference to a FeatureGroup in vertexai to populate featureGroupId.
	// +kubebuilder:validation:Optional
	FeatureGroupIDRef *v1.NamespacedReference `json:"featureGroupIdRef,omitempty" tf:"-"`

	// Selector for a FeatureGroup in vertexai to populate featureGroupId.
	// +kubebuilder:validation:Optional
	FeatureGroupIDSelector *v1.NamespacedSelector `json:"featureGroupIdSelector,omitempty" tf:"-"`

	// Identifiers of features under the feature group.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/apis/namespaced/vertexai/v1beta1.FeatureGroupFeature
	FeatureIds []*string `json:"featureIds,omitempty" tf:"feature_ids,omitempty"`

	// References to FeatureGroupFeature in vertexai to populate featureIds.
	// +kubebuilder:validation:Optional
	FeatureIdsRefs []v1.NamespacedReference `json:"featureIdsRefs,omitempty" tf:"-"`

	// Selector for a list of FeatureGroupFeature in vertexai to populate featureIds.
	// +kubebuilder:validation:Optional
	FeatureIdsSelector *v1.NamespacedSelector `json:"featureIdsSelector,omitempty" tf:"-"`
}

type FeatureGroupsObservation struct {

	// Identifier of the feature group.
	FeatureGroupID *string `json:"featureGroupId,omitempty" tf:"feature_group_id,omitempty"`

	// Identifiers of features under the feature group.
	FeatureIds []*string `json:"featureIds,omitempty" tf:"feature_ids,omitempty"`
}

type FeatureGroupsParameters struct {

	// Identifier of the feature group.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/apis/namespaced/vertexai/v1beta1.FeatureGroup
	// +kubebuilder:validation:Optional
	FeatureGroupID *string `json:"featureGroupId,omitempty" tf:"feature_group_id,omitempty"`

	// Reference to a FeatureGroup in vertexai to populate featureGroupId.
	// +kubebuilder:validation:Optional
	FeatureGroupIDRef *v1.NamespacedReference `json:"featureGroupIdRef,omitempty" tf:"-"`

	// Selector for a FeatureGroup in vertexai to populate featureGroupId.
	// +kubebuilder:validation:Optional
	FeatureGroupIDSelector *v1.NamespacedSelector `json:"featureGroupIdSelector,omitempty" tf:"-"`

	// Identifiers of features under the feature group.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/apis/namespaced/vertexai/v1beta1.FeatureGroupFeature
	// +kubebuilder:validation:Optional
	FeatureIds []*string `json:"featureIds,omitempty" tf:"feature_ids,omitempty"`

	// References to FeatureGroupFeature in vertexai to populate featureIds.
	// +kubebuilder:validation:Optional
	FeatureIdsRefs []v1.NamespacedReference `json:"featureIdsRefs,omitempty" tf:"-"`

	// Selector for a list of FeatureGroupFeature in vertexai to populate featureIds.
	// +kubebuilder:validation:Optional
	FeatureIdsSelector *v1.NamespacedSelector `json:"featureIdsSelector,omitempty" tf:"-"`
}

type FeatureOnlineStoreFeatureviewBigQuerySourceInitParameters struct {

	// Columns to construct entityId / row keys. Start by supporting 1 only.
	EntityIDColumns []*string `json:"entityIdColumns,omitempty" tf:"entity_id_columns,omitempty"`

	// The BigQuery view URI that will be materialized on each sync trigger based on FeatureView.SyncConfig.
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`
}

type FeatureOnlineStoreFeatureviewBigQuerySourceObservation struct {

	// Columns to construct entityId / row keys. Start by supporting 1 only.
	EntityIDColumns []*string `json:"entityIdColumns,omitempty" tf:"entity_id_columns,omitempty"`

	// The BigQuery view URI that will be materialized on each sync trigger based on FeatureView.SyncConfig.
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`
}

type FeatureOnlineStoreFeatureviewBigQuerySourceParameters struct {

	// Columns to construct entityId / row keys. Start by supporting 1 only.
	// +kubebuilder:validation:Optional
	EntityIDColumns []*string `json:"entityIdColumns" tf:"entity_id_columns,omitempty"`

	// The BigQuery view URI that will be materialized on each sync trigger based on FeatureView.SyncConfig.
	// +kubebuilder:validation:Optional
	URI *string `json:"uri" tf:"uri,omitempty"`
}

type FeatureOnlineStoreFeatureviewInitParameters struct {

	// Configures how data is supposed to be extracted from a BigQuery source to be loaded onto the FeatureOnlineStore.
	// Structure is documented below.
	BigQuerySource *FeatureOnlineStoreFeatureviewBigQuerySourceInitParameters `json:"bigQuerySource,omitempty" tf:"big_query_source,omitempty"`

	// Configures the features from a Feature Registry source that need to be loaded onto the FeatureOnlineStore.
	// Structure is documented below.
	FeatureRegistrySource *FeatureRegistrySourceInitParameters `json:"featureRegistrySource,omitempty" tf:"feature_registry_source,omitempty"`

	// A set of key/value label pairs to assign to this FeatureView.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/apis/namespaced/cloudplatform/v1beta1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("project_id",false)
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in cloudplatform to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v1.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in cloudplatform to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v1.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`

	// Configures when data is to be synced/updated for this FeatureView. At the end of the sync the latest featureValues for each entityId of this FeatureView are made ready for online serving.
	// Structure is documented below.
	SyncConfig *SyncConfigInitParameters `json:"syncConfig,omitempty" tf:"sync_config,omitempty"`
}

type FeatureOnlineStoreFeatureviewObservation struct {

	// Configures how data is supposed to be extracted from a BigQuery source to be loaded onto the FeatureOnlineStore.
	// Structure is documented below.
	BigQuerySource *FeatureOnlineStoreFeatureviewBigQuerySourceObservation `json:"bigQuerySource,omitempty" tf:"big_query_source,omitempty"`

	// The timestamp of when the featureOnlinestore was created in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to nine fractional digits.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// for all of the labels present on the resource.
	// +mapType=granular
	EffectiveLabels map[string]*string `json:"effectiveLabels,omitempty" tf:"effective_labels,omitempty"`

	// The name of the FeatureOnlineStore to use for the featureview.
	FeatureOnlineStore *string `json:"featureOnlineStore,omitempty" tf:"feature_online_store,omitempty"`

	// Configures the features from a Feature Registry source that need to be loaded onto the FeatureOnlineStore.
	// Structure is documented below.
	FeatureRegistrySource *FeatureRegistrySourceObservation `json:"featureRegistrySource,omitempty" tf:"feature_registry_source,omitempty"`

	// an identifier for the resource with format projects/{{project}}/locations/{{region}}/featureOnlineStores/{{feature_online_store}}/featureViews/{{name}}
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A set of key/value label pairs to assign to this FeatureView.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The region for the resource. It should be the same as the featureonlinestore region.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Configures when data is to be synced/updated for this FeatureView. At the end of the sync the latest featureValues for each entityId of this FeatureView are made ready for online serving.
	// Structure is documented below.
	SyncConfig *SyncConfigObservation `json:"syncConfig,omitempty" tf:"sync_config,omitempty"`

	// The combination of labels configured directly on the resource
	// and default labels configured on the provider.
	// +mapType=granular
	TerraformLabels map[string]*string `json:"terraformLabels,omitempty" tf:"terraform_labels,omitempty"`

	// The timestamp of when the featureOnlinestore was last updated in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to nine fractional digits.
	UpdateTime *string `json:"updateTime,omitempty" tf:"update_time,omitempty"`
}

type FeatureOnlineStoreFeatureviewParameters struct {

	// Configures how data is supposed to be extracted from a BigQuery source to be loaded onto the FeatureOnlineStore.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	BigQuerySource *FeatureOnlineStoreFeatureviewBigQuerySourceParameters `json:"bigQuerySource,omitempty" tf:"big_query_source,omitempty"`

	// The name of the FeatureOnlineStore to use for the featureview.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/apis/namespaced/vertexai/v1beta1.FeatureOnlineStore
	// +kubebuilder:validation:Optional
	FeatureOnlineStore *string `json:"featureOnlineStore,omitempty" tf:"feature_online_store,omitempty"`

	// Reference to a FeatureOnlineStore in vertexai to populate featureOnlineStore.
	// +kubebuilder:validation:Optional
	FeatureOnlineStoreRef *v1.NamespacedReference `json:"featureOnlineStoreRef,omitempty" tf:"-"`

	// Selector for a FeatureOnlineStore in vertexai to populate featureOnlineStore.
	// +kubebuilder:validation:Optional
	FeatureOnlineStoreSelector *v1.NamespacedSelector `json:"featureOnlineStoreSelector,omitempty" tf:"-"`

	// Configures the features from a Feature Registry source that need to be loaded onto the FeatureOnlineStore.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	FeatureRegistrySource *FeatureRegistrySourceParameters `json:"featureRegistrySource,omitempty" tf:"feature_registry_source,omitempty"`

	// A set of key/value label pairs to assign to this FeatureView.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/apis/namespaced/cloudplatform/v1beta1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("project_id",false)
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in cloudplatform to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v1.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in cloudplatform to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v1.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`

	// The region for the resource. It should be the same as the featureonlinestore region.
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`

	// Configures when data is to be synced/updated for this FeatureView. At the end of the sync the latest featureValues for each entityId of this FeatureView are made ready for online serving.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	SyncConfig *SyncConfigParameters `json:"syncConfig,omitempty" tf:"sync_config,omitempty"`
}

type FeatureRegistrySourceInitParameters struct {

	// List of features that need to be synced to Online Store.
	// Structure is documented below.
	FeatureGroups []FeatureGroupsInitParameters `json:"featureGroups,omitempty" tf:"feature_groups,omitempty"`

	// The project number of the parent project of the feature Groups.
	ProjectNumber *string `json:"projectNumber,omitempty" tf:"project_number,omitempty"`
}

type FeatureRegistrySourceObservation struct {

	// List of features that need to be synced to Online Store.
	// Structure is documented below.
	FeatureGroups []FeatureGroupsObservation `json:"featureGroups,omitempty" tf:"feature_groups,omitempty"`

	// The project number of the parent project of the feature Groups.
	ProjectNumber *string `json:"projectNumber,omitempty" tf:"project_number,omitempty"`
}

type FeatureRegistrySourceParameters struct {

	// List of features that need to be synced to Online Store.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	FeatureGroups []FeatureGroupsParameters `json:"featureGroups" tf:"feature_groups,omitempty"`

	// The project number of the parent project of the feature Groups.
	// +kubebuilder:validation:Optional
	ProjectNumber *string `json:"projectNumber,omitempty" tf:"project_number,omitempty"`
}

type SyncConfigInitParameters struct {

	// Cron schedule (https://en.wikipedia.org/wiki/Cron) to launch scheduled runs.
	// To explicitly set a timezone to the cron tab, apply a prefix in the cron tab: "CRON_TZ=${IANA_TIME_ZONE}" or "TZ=${IANA_TIME_ZONE}".
	Cron *string `json:"cron,omitempty" tf:"cron,omitempty"`
}

type SyncConfigObservation struct {

	// Cron schedule (https://en.wikipedia.org/wiki/Cron) to launch scheduled runs.
	// To explicitly set a timezone to the cron tab, apply a prefix in the cron tab: "CRON_TZ=${IANA_TIME_ZONE}" or "TZ=${IANA_TIME_ZONE}".
	Cron *string `json:"cron,omitempty" tf:"cron,omitempty"`
}

type SyncConfigParameters struct {

	// Cron schedule (https://en.wikipedia.org/wiki/Cron) to launch scheduled runs.
	// To explicitly set a timezone to the cron tab, apply a prefix in the cron tab: "CRON_TZ=${IANA_TIME_ZONE}" or "TZ=${IANA_TIME_ZONE}".
	// +kubebuilder:validation:Optional
	Cron *string `json:"cron,omitempty" tf:"cron,omitempty"`
}

// FeatureOnlineStoreFeatureviewSpec defines the desired state of FeatureOnlineStoreFeatureview
type FeatureOnlineStoreFeatureviewSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            FeatureOnlineStoreFeatureviewParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FeatureOnlineStoreFeatureviewInitParameters `json:"initProvider,omitempty"`
}

// FeatureOnlineStoreFeatureviewStatus defines the observed state of FeatureOnlineStoreFeatureview.
type FeatureOnlineStoreFeatureviewStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FeatureOnlineStoreFeatureviewObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FeatureOnlineStoreFeatureview is the Schema for the FeatureOnlineStoreFeatureviews API. FeatureView is representation of values that the FeatureOnlineStore will serve based on its syncConfig.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gcp}
type FeatureOnlineStoreFeatureview struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              FeatureOnlineStoreFeatureviewSpec   `json:"spec"`
	Status            FeatureOnlineStoreFeatureviewStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FeatureOnlineStoreFeatureviewList contains a list of FeatureOnlineStoreFeatureviews
type FeatureOnlineStoreFeatureviewList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FeatureOnlineStoreFeatureview `json:"items"`
}

// Repository type metadata.
var (
	FeatureOnlineStoreFeatureview_Kind             = "FeatureOnlineStoreFeatureview"
	FeatureOnlineStoreFeatureview_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FeatureOnlineStoreFeatureview_Kind}.String()
	FeatureOnlineStoreFeatureview_KindAPIVersion   = FeatureOnlineStoreFeatureview_Kind + "." + CRDGroupVersion.String()
	FeatureOnlineStoreFeatureview_GroupVersionKind = CRDGroupVersion.WithKind(FeatureOnlineStoreFeatureview_Kind)
)

func init() {
	SchemeBuilder.Register(&FeatureOnlineStoreFeatureview{}, &FeatureOnlineStoreFeatureviewList{})
}
