// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BasicInitParameters struct {
}

type BasicObservation struct {
}

type BasicParameters struct {
}

type RagEngineConfigInitParameters struct {

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Required. The config of the RagManagedDb used by RagEngine.
	// Structure is documented below.
	RagManagedDBConfig *RagManagedDBConfigInitParameters `json:"ragManagedDbConfig,omitempty" tf:"rag_managed_db_config,omitempty"`
}

type RagEngineConfigObservation struct {

	// an identifier for the resource with format projects/{{project}}/locations/{{region}}/ragEngineConfig
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The resource name of the Dataset. This value is set by Google.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Required. The config of the RagManagedDb used by RagEngine.
	// Structure is documented below.
	RagManagedDBConfig *RagManagedDBConfigObservation `json:"ragManagedDbConfig,omitempty" tf:"rag_managed_db_config,omitempty"`

	// The region of the RagEngineConfig. eg us-central1
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type RagEngineConfigParameters struct {

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Required. The config of the RagManagedDb used by RagEngine.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	RagManagedDBConfig *RagManagedDBConfigParameters `json:"ragManagedDbConfig,omitempty" tf:"rag_managed_db_config,omitempty"`

	// The region of the RagEngineConfig. eg us-central1
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`
}

type RagManagedDBConfigInitParameters struct {

	// Basic tier is a cost-effective and low compute tier suitable for the following cases: Experimenting with RagManagedDb, Small data size, Latency insensitive workload, Only using RAG Engine with external vector DBs.
	// NOTE: This is the default tier if not explicitly chosen.
	Basic *BasicInitParameters `json:"basic,omitempty" tf:"basic,omitempty"`

	// Scaled tier offers production grade performance along with autoscaling functionality. It is suitable for customers with large amounts of data or performance sensitive workloads.
	Scaled *ScaledInitParameters `json:"scaled,omitempty" tf:"scaled,omitempty"`

	// Disables the RAG Engine service and deletes all your data held within this service. This will halt the billing of the service.
	// NOTE: Once deleted the data cannot be recovered. To start using RAG Engine again, you will need to update the tier by calling the UpdateRagEngineConfig API.
	Unprovisioned *UnprovisionedInitParameters `json:"unprovisioned,omitempty" tf:"unprovisioned,omitempty"`
}

type RagManagedDBConfigObservation struct {

	// Basic tier is a cost-effective and low compute tier suitable for the following cases: Experimenting with RagManagedDb, Small data size, Latency insensitive workload, Only using RAG Engine with external vector DBs.
	// NOTE: This is the default tier if not explicitly chosen.
	Basic *BasicParameters `json:"basic,omitempty" tf:"basic,omitempty"`

	// Scaled tier offers production grade performance along with autoscaling functionality. It is suitable for customers with large amounts of data or performance sensitive workloads.
	Scaled *ScaledParameters `json:"scaled,omitempty" tf:"scaled,omitempty"`

	// Disables the RAG Engine service and deletes all your data held within this service. This will halt the billing of the service.
	// NOTE: Once deleted the data cannot be recovered. To start using RAG Engine again, you will need to update the tier by calling the UpdateRagEngineConfig API.
	Unprovisioned *UnprovisionedParameters `json:"unprovisioned,omitempty" tf:"unprovisioned,omitempty"`
}

type RagManagedDBConfigParameters struct {

	// Basic tier is a cost-effective and low compute tier suitable for the following cases: Experimenting with RagManagedDb, Small data size, Latency insensitive workload, Only using RAG Engine with external vector DBs.
	// NOTE: This is the default tier if not explicitly chosen.
	// +kubebuilder:validation:Optional
	Basic *BasicParameters `json:"basic,omitempty" tf:"basic,omitempty"`

	// Scaled tier offers production grade performance along with autoscaling functionality. It is suitable for customers with large amounts of data or performance sensitive workloads.
	// +kubebuilder:validation:Optional
	Scaled *ScaledParameters `json:"scaled,omitempty" tf:"scaled,omitempty"`

	// Disables the RAG Engine service and deletes all your data held within this service. This will halt the billing of the service.
	// NOTE: Once deleted the data cannot be recovered. To start using RAG Engine again, you will need to update the tier by calling the UpdateRagEngineConfig API.
	// +kubebuilder:validation:Optional
	Unprovisioned *UnprovisionedParameters `json:"unprovisioned,omitempty" tf:"unprovisioned,omitempty"`
}

type ScaledInitParameters struct {
}

type ScaledObservation struct {
}

type ScaledParameters struct {
}

type UnprovisionedInitParameters struct {
}

type UnprovisionedObservation struct {
}

type UnprovisionedParameters struct {
}

// RagEngineConfigSpec defines the desired state of RagEngineConfig
type RagEngineConfigSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RagEngineConfigParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RagEngineConfigInitParameters `json:"initProvider,omitempty"`
}

// RagEngineConfigStatus defines the observed state of RagEngineConfig.
type RagEngineConfigStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RagEngineConfigObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RagEngineConfig is the Schema for the RagEngineConfigs API. Vertex AI RAG Engine lets you scale your RagManagedDb instance based on your usage and performance requirements using a choice of two tiers, and optionally, lets you delete your Vertex AI RAG Engine data using a third tier.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gcp}
type RagEngineConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ragManagedDbConfig) || (has(self.initProvider) && has(self.initProvider.ragManagedDbConfig))",message="spec.forProvider.ragManagedDbConfig is a required parameter"
	Spec   RagEngineConfigSpec   `json:"spec"`
	Status RagEngineConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RagEngineConfigList contains a list of RagEngineConfigs
type RagEngineConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RagEngineConfig `json:"items"`
}

// Repository type metadata.
var (
	RagEngineConfig_Kind             = "RagEngineConfig"
	RagEngineConfig_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RagEngineConfig_Kind}.String()
	RagEngineConfig_KindAPIVersion   = RagEngineConfig_Kind + "." + CRDGroupVersion.String()
	RagEngineConfig_GroupVersionKind = CRDGroupVersion.WithKind(RagEngineConfig_Kind)
)

func init() {
	SchemeBuilder.Register(&RagEngineConfig{}, &RagEngineConfigList{})
}
