// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AgentCreationConfigInitParameters struct {

	// Name of the company, organization or other entity that the agent represents. Used for knowledge connector LLM prompt and for knowledge search.
	Business *string `json:"business,omitempty" tf:"business,omitempty"`

	// The default language of the agent as a language tag. See Language Support for a list of the currently supported language codes.
	DefaultLanguageCode *string `json:"defaultLanguageCode,omitempty" tf:"default_language_code,omitempty"`

	// The time zone of the agent from the time zone database, e.g., America/New_York, Europe/Paris.
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`
}

type AgentCreationConfigObservation struct {

	// Name of the company, organization or other entity that the agent represents. Used for knowledge connector LLM prompt and for knowledge search.
	Business *string `json:"business,omitempty" tf:"business,omitempty"`

	// The default language of the agent as a language tag. See Language Support for a list of the currently supported language codes.
	DefaultLanguageCode *string `json:"defaultLanguageCode,omitempty" tf:"default_language_code,omitempty"`

	// Location.
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// The time zone of the agent from the time zone database, e.g., America/New_York, Europe/Paris.
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`
}

type AgentCreationConfigParameters struct {

	// Name of the company, organization or other entity that the agent represents. Used for knowledge connector LLM prompt and for knowledge search.
	// +kubebuilder:validation:Optional
	Business *string `json:"business,omitempty" tf:"business,omitempty"`

	// The default language of the agent as a language tag. See Language Support for a list of the currently supported language codes.
	// +kubebuilder:validation:Optional
	DefaultLanguageCode *string `json:"defaultLanguageCode" tf:"default_language_code,omitempty"`

	// Location.
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// The time zone of the agent from the time zone database, e.g., America/New_York, Europe/Paris.
	// +kubebuilder:validation:Optional
	TimeZone *string `json:"timeZone" tf:"time_zone,omitempty"`
}

type ChatEngineConfigInitParameters struct {

	// The configuration to generate the Dialogflow agent that is associated to this Engine.
	// Exactly one of agent_creation_config or dialogflow_agent_to_link must be set.
	// Structure is documented below.
	AgentCreationConfig *AgentCreationConfigInitParameters `json:"agentCreationConfig,omitempty" tf:"agent_creation_config,omitempty"`

	// If the flag set to true, we allow the agent and engine are in
	// different locations, otherwise the agent and engine are required to be
	// in the same location. The flag is set to false by default.
	// Note that the allow_cross_region are one-time consumed by and passed
	// to EngineService.CreateEngine. It means they cannot be retrieved using
	// EngineService.GetEngine or EngineService.ListEngines API after engine
	// creation.
	AllowCrossRegion *bool `json:"allowCrossRegion,omitempty" tf:"allow_cross_region,omitempty"`

	// The resource name of an existing Dialogflow agent to link to this Chat Engine. Format: projects/<Project_ID>/locations/<Location_ID>/agents/<Agent_ID>.
	// Exactly one of agent_creation_config or dialogflow_agent_to_link must be set.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/cluster/dialogflowcx/v1beta2.Agent
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	DialogflowAgentToLink *string `json:"dialogflowAgentToLink,omitempty" tf:"dialogflow_agent_to_link,omitempty"`

	// Reference to a Agent in dialogflowcx to populate dialogflowAgentToLink.
	// +kubebuilder:validation:Optional
	DialogflowAgentToLinkRef *v1.Reference `json:"dialogflowAgentToLinkRef,omitempty" tf:"-"`

	// Selector for a Agent in dialogflowcx to populate dialogflowAgentToLink.
	// +kubebuilder:validation:Optional
	DialogflowAgentToLinkSelector *v1.Selector `json:"dialogflowAgentToLinkSelector,omitempty" tf:"-"`
}

type ChatEngineConfigObservation struct {

	// The configuration to generate the Dialogflow agent that is associated to this Engine.
	// Exactly one of agent_creation_config or dialogflow_agent_to_link must be set.
	// Structure is documented below.
	AgentCreationConfig *AgentCreationConfigObservation `json:"agentCreationConfig,omitempty" tf:"agent_creation_config,omitempty"`

	// If the flag set to true, we allow the agent and engine are in
	// different locations, otherwise the agent and engine are required to be
	// in the same location. The flag is set to false by default.
	// Note that the allow_cross_region are one-time consumed by and passed
	// to EngineService.CreateEngine. It means they cannot be retrieved using
	// EngineService.GetEngine or EngineService.ListEngines API after engine
	// creation.
	AllowCrossRegion *bool `json:"allowCrossRegion,omitempty" tf:"allow_cross_region,omitempty"`

	// The resource name of an existing Dialogflow agent to link to this Chat Engine. Format: projects/<Project_ID>/locations/<Location_ID>/agents/<Agent_ID>.
	// Exactly one of agent_creation_config or dialogflow_agent_to_link must be set.
	DialogflowAgentToLink *string `json:"dialogflowAgentToLink,omitempty" tf:"dialogflow_agent_to_link,omitempty"`
}

type ChatEngineConfigParameters struct {

	// The configuration to generate the Dialogflow agent that is associated to this Engine.
	// Exactly one of agent_creation_config or dialogflow_agent_to_link must be set.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	AgentCreationConfig *AgentCreationConfigParameters `json:"agentCreationConfig,omitempty" tf:"agent_creation_config,omitempty"`

	// If the flag set to true, we allow the agent and engine are in
	// different locations, otherwise the agent and engine are required to be
	// in the same location. The flag is set to false by default.
	// Note that the allow_cross_region are one-time consumed by and passed
	// to EngineService.CreateEngine. It means they cannot be retrieved using
	// EngineService.GetEngine or EngineService.ListEngines API after engine
	// creation.
	// +kubebuilder:validation:Optional
	AllowCrossRegion *bool `json:"allowCrossRegion,omitempty" tf:"allow_cross_region,omitempty"`

	// The resource name of an existing Dialogflow agent to link to this Chat Engine. Format: projects/<Project_ID>/locations/<Location_ID>/agents/<Agent_ID>.
	// Exactly one of agent_creation_config or dialogflow_agent_to_link must be set.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/cluster/dialogflowcx/v1beta2.Agent
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	DialogflowAgentToLink *string `json:"dialogflowAgentToLink,omitempty" tf:"dialogflow_agent_to_link,omitempty"`

	// Reference to a Agent in dialogflowcx to populate dialogflowAgentToLink.
	// +kubebuilder:validation:Optional
	DialogflowAgentToLinkRef *v1.Reference `json:"dialogflowAgentToLinkRef,omitempty" tf:"-"`

	// Selector for a Agent in dialogflowcx to populate dialogflowAgentToLink.
	// +kubebuilder:validation:Optional
	DialogflowAgentToLinkSelector *v1.Selector `json:"dialogflowAgentToLinkSelector,omitempty" tf:"-"`
}

type ChatEngineInitParameters struct {

	// Configurations for a chat Engine.
	// Structure is documented below.
	ChatEngineConfig *ChatEngineConfigInitParameters `json:"chatEngineConfig,omitempty" tf:"chat_engine_config,omitempty"`

	// Common config spec that specifies the metadata of the engine.
	// Structure is documented below.
	CommonConfig *CommonConfigInitParameters `json:"commonConfig,omitempty" tf:"common_config,omitempty"`

	// The data stores associated with this engine. Multiple DataStores in the same Collection can be associated here. All listed DataStores must be SOLUTION_TYPE_CHAT.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/cluster/discoveryengine/v1beta1.DataStore
	DataStoreIds []*string `json:"dataStoreIds,omitempty" tf:"data_store_ids,omitempty"`

	// References to DataStore in discoveryengine to populate dataStoreIds.
	// +kubebuilder:validation:Optional
	DataStoreIdsRefs []v1.Reference `json:"dataStoreIdsRefs,omitempty" tf:"-"`

	// Selector for a list of DataStore in discoveryengine to populate dataStoreIds.
	// +kubebuilder:validation:Optional
	DataStoreIdsSelector *v1.Selector `json:"dataStoreIdsSelector,omitempty" tf:"-"`

	// The display name of the engine. Should be human readable. UTF-8 encoded string with limit of 1024 characters.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The industry vertical that the chat engine registers. Vertical on Engine has to match vertical of the DataStore linked to the engine.
	// Default value is GENERIC.
	// Possible values are: GENERIC.
	IndustryVertical *string `json:"industryVertical,omitempty" tf:"industry_vertical,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`
}

type ChatEngineMetadataInitParameters struct {
}

type ChatEngineMetadataObservation struct {

	// (Output)
	// The resource name of a Dialogflow agent, that this Chat Engine refers to.
	DialogflowAgent *string `json:"dialogflowAgent,omitempty" tf:"dialogflow_agent,omitempty"`
}

type ChatEngineMetadataParameters struct {
}

type ChatEngineObservation struct {

	// Configurations for a chat Engine.
	// Structure is documented below.
	ChatEngineConfig *ChatEngineConfigObservation `json:"chatEngineConfig,omitempty" tf:"chat_engine_config,omitempty"`

	// Additional information of the Chat Engine.
	// Structure is documented below.
	ChatEngineMetadata []ChatEngineMetadataObservation `json:"chatEngineMetadata,omitempty" tf:"chat_engine_metadata,omitempty"`

	// The collection ID.
	CollectionID *string `json:"collectionId,omitempty" tf:"collection_id,omitempty"`

	// Common config spec that specifies the metadata of the engine.
	// Structure is documented below.
	CommonConfig *CommonConfigObservation `json:"commonConfig,omitempty" tf:"common_config,omitempty"`

	// Timestamp the Engine was created at.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// The data stores associated with this engine. Multiple DataStores in the same Collection can be associated here. All listed DataStores must be SOLUTION_TYPE_CHAT.
	DataStoreIds []*string `json:"dataStoreIds,omitempty" tf:"data_store_ids,omitempty"`

	// The display name of the engine. Should be human readable. UTF-8 encoded string with limit of 1024 characters.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// an identifier for the resource with format projects/{{project}}/locations/{{location}}/collections/{{collection_id}}/engines/{{engine_id}}
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The industry vertical that the chat engine registers. Vertical on Engine has to match vertical of the DataStore linked to the engine.
	// Default value is GENERIC.
	// Possible values are: GENERIC.
	IndustryVertical *string `json:"industryVertical,omitempty" tf:"industry_vertical,omitempty"`

	// Location.
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// The unique full resource name of the chat engine. Values are of the format
	// projects/{project}/locations/{location}/collections/{collection_id}/engines/{engine_id}.
	// This field must be a UTF-8 encoded string with a length limit of 1024
	// characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Timestamp the Engine was last updated.
	UpdateTime *string `json:"updateTime,omitempty" tf:"update_time,omitempty"`
}

type ChatEngineParameters struct {

	// Configurations for a chat Engine.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	ChatEngineConfig *ChatEngineConfigParameters `json:"chatEngineConfig,omitempty" tf:"chat_engine_config,omitempty"`

	// The collection ID.
	// +kubebuilder:validation:Required
	CollectionID *string `json:"collectionId" tf:"collection_id,omitempty"`

	// Common config spec that specifies the metadata of the engine.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	CommonConfig *CommonConfigParameters `json:"commonConfig,omitempty" tf:"common_config,omitempty"`

	// The data stores associated with this engine. Multiple DataStores in the same Collection can be associated here. All listed DataStores must be SOLUTION_TYPE_CHAT.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/cluster/discoveryengine/v1beta1.DataStore
	// +kubebuilder:validation:Optional
	DataStoreIds []*string `json:"dataStoreIds,omitempty" tf:"data_store_ids,omitempty"`

	// References to DataStore in discoveryengine to populate dataStoreIds.
	// +kubebuilder:validation:Optional
	DataStoreIdsRefs []v1.Reference `json:"dataStoreIdsRefs,omitempty" tf:"-"`

	// Selector for a list of DataStore in discoveryengine to populate dataStoreIds.
	// +kubebuilder:validation:Optional
	DataStoreIdsSelector *v1.Selector `json:"dataStoreIdsSelector,omitempty" tf:"-"`

	// The display name of the engine. Should be human readable. UTF-8 encoded string with limit of 1024 characters.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The industry vertical that the chat engine registers. Vertical on Engine has to match vertical of the DataStore linked to the engine.
	// Default value is GENERIC.
	// Possible values are: GENERIC.
	// +kubebuilder:validation:Optional
	IndustryVertical *string `json:"industryVertical,omitempty" tf:"industry_vertical,omitempty"`

	// Location.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/cluster/discoveryengine/v1beta1.DataStore
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("location",false)
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// Reference to a DataStore in discoveryengine to populate location.
	// +kubebuilder:validation:Optional
	LocationRef *v1.Reference `json:"locationRef,omitempty" tf:"-"`

	// Selector for a DataStore in discoveryengine to populate location.
	// +kubebuilder:validation:Optional
	LocationSelector *v1.Selector `json:"locationSelector,omitempty" tf:"-"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`
}

type CommonConfigInitParameters struct {

	// The name of the company, business or entity that is associated with the engine. Setting this may help improve LLM related features.
	CompanyName *string `json:"companyName,omitempty" tf:"company_name,omitempty"`
}

type CommonConfigObservation struct {

	// The name of the company, business or entity that is associated with the engine. Setting this may help improve LLM related features.
	CompanyName *string `json:"companyName,omitempty" tf:"company_name,omitempty"`
}

type CommonConfigParameters struct {

	// The name of the company, business or entity that is associated with the engine. Setting this may help improve LLM related features.
	// +kubebuilder:validation:Optional
	CompanyName *string `json:"companyName,omitempty" tf:"company_name,omitempty"`
}

// ChatEngineSpec defines the desired state of ChatEngine
type ChatEngineSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ChatEngineParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ChatEngineInitParameters `json:"initProvider,omitempty"`
}

// ChatEngineStatus defines the observed state of ChatEngine.
type ChatEngineStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ChatEngineObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ChatEngine is the Schema for the ChatEngines API. Vertex chat and Conversation Engine Chat type
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,gcp}
type ChatEngine struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.chatEngineConfig) || (has(self.initProvider) && has(self.initProvider.chatEngineConfig))",message="spec.forProvider.chatEngineConfig is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	Spec   ChatEngineSpec   `json:"spec"`
	Status ChatEngineStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ChatEngineList contains a list of ChatEngines
type ChatEngineList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ChatEngine `json:"items"`
}

// Repository type metadata.
var (
	ChatEngine_Kind             = "ChatEngine"
	ChatEngine_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ChatEngine_Kind}.String()
	ChatEngine_KindAPIVersion   = ChatEngine_Kind + "." + CRDGroupVersion.String()
	ChatEngine_GroupVersionKind = CRDGroupVersion.WithKind(ChatEngine_Kind)
)

func init() {
	SchemeBuilder.Register(&ChatEngine{}, &ChatEngineList{})
}
