// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type EngineFeaturesConfigInitParameters struct {

	// Feature configurations that are required for creating a Most Popular engine.
	// Structure is documented below.
	MostPopularConfig *MostPopularConfigInitParameters `json:"mostPopularConfig,omitempty" tf:"most_popular_config,omitempty"`

	// Additional feature configurations for creating a recommended-for-you engine.
	// Structure is documented below.
	RecommendedForYouConfig *RecommendedForYouConfigInitParameters `json:"recommendedForYouConfig,omitempty" tf:"recommended_for_you_config,omitempty"`
}

type EngineFeaturesConfigObservation struct {

	// Feature configurations that are required for creating a Most Popular engine.
	// Structure is documented below.
	MostPopularConfig *MostPopularConfigObservation `json:"mostPopularConfig,omitempty" tf:"most_popular_config,omitempty"`

	// Additional feature configurations for creating a recommended-for-you engine.
	// Structure is documented below.
	RecommendedForYouConfig *RecommendedForYouConfigObservation `json:"recommendedForYouConfig,omitempty" tf:"recommended_for_you_config,omitempty"`
}

type EngineFeaturesConfigParameters struct {

	// Feature configurations that are required for creating a Most Popular engine.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	MostPopularConfig *MostPopularConfigParameters `json:"mostPopularConfig,omitempty" tf:"most_popular_config,omitempty"`

	// Additional feature configurations for creating a recommended-for-you engine.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	RecommendedForYouConfig *RecommendedForYouConfigParameters `json:"recommendedForYouConfig,omitempty" tf:"recommended_for_you_config,omitempty"`
}

type MediaRecommendationEngineConfigInitParameters struct {

	// More feature configs of the selected engine type.
	// Structure is documented below.
	EngineFeaturesConfig *EngineFeaturesConfigInitParameters `json:"engineFeaturesConfig,omitempty" tf:"engine_features_config,omitempty"`

	// The optimization objective. e.g., cvr.
	// This field together with MediaRecommendationEngineConfig.type describes
	// engine metadata to use to control engine training and serving.
	// Currently supported values: ctr, cvr.
	// If not specified, we choose default based on engine type. Default depends on type of recommendation:
	// recommended-for-you => ctr
	// others-you-may-like => ctr
	OptimizationObjective *string `json:"optimizationObjective,omitempty" tf:"optimization_objective,omitempty"`

	// Name and value of the custom threshold for cvr optimization_objective.
	// For target_field watch-time, target_field_value must be an integer
	// value indicating the media progress time in seconds between (0, 86400]
	// (excludes 0, includes 86400) (e.g., 90).
	// For target_field watch-percentage, the target_field_value must be a
	// valid float value between (0, 1.0] (excludes 0, includes 1.0) (e.g., 0.5).
	// Structure is documented below.
	OptimizationObjectiveConfig *OptimizationObjectiveConfigInitParameters `json:"optimizationObjectiveConfig,omitempty" tf:"optimization_objective_config,omitempty"`

	// The training state that the engine is in (e.g. TRAINING or PAUSED).
	// Since part of the cost of running the service
	// is frequency of training - this can be used to determine when to train
	// engine in order to control cost. If not specified: the default value for
	// CreateEngine method is TRAINING. The default value for
	// UpdateEngine method is to keep the state the same as before.
	// Possible values are: PAUSED, TRAINING.
	TrainingState *string `json:"trainingState,omitempty" tf:"training_state,omitempty"`

	// The type of engine. e.g., recommended-for-you.
	// This field together with MediaRecommendationEngineConfig.optimizationObjective describes
	// engine metadata to use to control engine training and serving.
	// Currently supported values: recommended-for-you, others-you-may-like,
	// more-like-this, most-popular-items.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type MediaRecommendationEngineConfigObservation struct {

	// More feature configs of the selected engine type.
	// Structure is documented below.
	EngineFeaturesConfig *EngineFeaturesConfigObservation `json:"engineFeaturesConfig,omitempty" tf:"engine_features_config,omitempty"`

	// The optimization objective. e.g., cvr.
	// This field together with MediaRecommendationEngineConfig.type describes
	// engine metadata to use to control engine training and serving.
	// Currently supported values: ctr, cvr.
	// If not specified, we choose default based on engine type. Default depends on type of recommendation:
	// recommended-for-you => ctr
	// others-you-may-like => ctr
	OptimizationObjective *string `json:"optimizationObjective,omitempty" tf:"optimization_objective,omitempty"`

	// Name and value of the custom threshold for cvr optimization_objective.
	// For target_field watch-time, target_field_value must be an integer
	// value indicating the media progress time in seconds between (0, 86400]
	// (excludes 0, includes 86400) (e.g., 90).
	// For target_field watch-percentage, the target_field_value must be a
	// valid float value between (0, 1.0] (excludes 0, includes 1.0) (e.g., 0.5).
	// Structure is documented below.
	OptimizationObjectiveConfig *OptimizationObjectiveConfigObservation `json:"optimizationObjectiveConfig,omitempty" tf:"optimization_objective_config,omitempty"`

	// The training state that the engine is in (e.g. TRAINING or PAUSED).
	// Since part of the cost of running the service
	// is frequency of training - this can be used to determine when to train
	// engine in order to control cost. If not specified: the default value for
	// CreateEngine method is TRAINING. The default value for
	// UpdateEngine method is to keep the state the same as before.
	// Possible values are: PAUSED, TRAINING.
	TrainingState *string `json:"trainingState,omitempty" tf:"training_state,omitempty"`

	// The type of engine. e.g., recommended-for-you.
	// This field together with MediaRecommendationEngineConfig.optimizationObjective describes
	// engine metadata to use to control engine training and serving.
	// Currently supported values: recommended-for-you, others-you-may-like,
	// more-like-this, most-popular-items.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type MediaRecommendationEngineConfigParameters struct {

	// More feature configs of the selected engine type.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	EngineFeaturesConfig *EngineFeaturesConfigParameters `json:"engineFeaturesConfig,omitempty" tf:"engine_features_config,omitempty"`

	// The optimization objective. e.g., cvr.
	// This field together with MediaRecommendationEngineConfig.type describes
	// engine metadata to use to control engine training and serving.
	// Currently supported values: ctr, cvr.
	// If not specified, we choose default based on engine type. Default depends on type of recommendation:
	// recommended-for-you => ctr
	// others-you-may-like => ctr
	// +kubebuilder:validation:Optional
	OptimizationObjective *string `json:"optimizationObjective,omitempty" tf:"optimization_objective,omitempty"`

	// Name and value of the custom threshold for cvr optimization_objective.
	// For target_field watch-time, target_field_value must be an integer
	// value indicating the media progress time in seconds between (0, 86400]
	// (excludes 0, includes 86400) (e.g., 90).
	// For target_field watch-percentage, the target_field_value must be a
	// valid float value between (0, 1.0] (excludes 0, includes 1.0) (e.g., 0.5).
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	OptimizationObjectiveConfig *OptimizationObjectiveConfigParameters `json:"optimizationObjectiveConfig,omitempty" tf:"optimization_objective_config,omitempty"`

	// The training state that the engine is in (e.g. TRAINING or PAUSED).
	// Since part of the cost of running the service
	// is frequency of training - this can be used to determine when to train
	// engine in order to control cost. If not specified: the default value for
	// CreateEngine method is TRAINING. The default value for
	// UpdateEngine method is to keep the state the same as before.
	// Possible values are: PAUSED, TRAINING.
	// +kubebuilder:validation:Optional
	TrainingState *string `json:"trainingState,omitempty" tf:"training_state,omitempty"`

	// The type of engine. e.g., recommended-for-you.
	// This field together with MediaRecommendationEngineConfig.optimizationObjective describes
	// engine metadata to use to control engine training and serving.
	// Currently supported values: recommended-for-you, others-you-may-like,
	// more-like-this, most-popular-items.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type MostPopularConfigInitParameters struct {

	// The time window of which the engine is queried at training and
	// prediction time. Positive integers only. The value translates to the
	// last X days of events. Currently required for the most-popular-items
	// engine.
	TimeWindowDays *float64 `json:"timeWindowDays,omitempty" tf:"time_window_days,omitempty"`
}

type MostPopularConfigObservation struct {

	// The time window of which the engine is queried at training and
	// prediction time. Positive integers only. The value translates to the
	// last X days of events. Currently required for the most-popular-items
	// engine.
	TimeWindowDays *float64 `json:"timeWindowDays,omitempty" tf:"time_window_days,omitempty"`
}

type MostPopularConfigParameters struct {

	// The time window of which the engine is queried at training and
	// prediction time. Positive integers only. The value translates to the
	// last X days of events. Currently required for the most-popular-items
	// engine.
	// +kubebuilder:validation:Optional
	TimeWindowDays *float64 `json:"timeWindowDays,omitempty" tf:"time_window_days,omitempty"`
}

type OptimizationObjectiveConfigInitParameters struct {

	// The name of the field to target. Currently supported values: watch-percentage, watch-time.
	TargetField *string `json:"targetField,omitempty" tf:"target_field,omitempty"`

	// The threshold to be applied to the target (e.g., 0.5).
	TargetFieldValueFloat *float64 `json:"targetFieldValueFloat,omitempty" tf:"target_field_value_float,omitempty"`
}

type OptimizationObjectiveConfigObservation struct {

	// The name of the field to target. Currently supported values: watch-percentage, watch-time.
	TargetField *string `json:"targetField,omitempty" tf:"target_field,omitempty"`

	// The threshold to be applied to the target (e.g., 0.5).
	TargetFieldValueFloat *float64 `json:"targetFieldValueFloat,omitempty" tf:"target_field_value_float,omitempty"`
}

type OptimizationObjectiveConfigParameters struct {

	// The name of the field to target. Currently supported values: watch-percentage, watch-time.
	// +kubebuilder:validation:Optional
	TargetField *string `json:"targetField,omitempty" tf:"target_field,omitempty"`

	// The threshold to be applied to the target (e.g., 0.5).
	// +kubebuilder:validation:Optional
	TargetFieldValueFloat *float64 `json:"targetFieldValueFloat,omitempty" tf:"target_field_value_float,omitempty"`
}

type RecommendationEngineCommonConfigInitParameters struct {

	// The name of the company, business or entity that is associated with the engine. Setting this may help improve LLM related features.cd
	CompanyName *string `json:"companyName,omitempty" tf:"company_name,omitempty"`
}

type RecommendationEngineCommonConfigObservation struct {

	// The name of the company, business or entity that is associated with the engine. Setting this may help improve LLM related features.cd
	CompanyName *string `json:"companyName,omitempty" tf:"company_name,omitempty"`
}

type RecommendationEngineCommonConfigParameters struct {

	// The name of the company, business or entity that is associated with the engine. Setting this may help improve LLM related features.cd
	// +kubebuilder:validation:Optional
	CompanyName *string `json:"companyName,omitempty" tf:"company_name,omitempty"`
}

type RecommendationEngineInitParameters struct {

	// Common config spec that specifies the metadata of the engine.
	// Structure is documented below.
	CommonConfig *RecommendationEngineCommonConfigInitParameters `json:"commonConfig,omitempty" tf:"common_config,omitempty"`

	// The data stores associated with this engine. For SOLUTION_TYPE_RECOMMENDATION type of engines, they can only associate with at most one data store.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/cluster/discoveryengine/v1beta1.DataStore
	DataStoreIds []*string `json:"dataStoreIds,omitempty" tf:"data_store_ids,omitempty"`

	// References to DataStore in discoveryengine to populate dataStoreIds.
	// +kubebuilder:validation:Optional
	DataStoreIdsRefs []v1.Reference `json:"dataStoreIdsRefs,omitempty" tf:"-"`

	// Selector for a list of DataStore in discoveryengine to populate dataStoreIds.
	// +kubebuilder:validation:Optional
	DataStoreIdsSelector *v1.Selector `json:"dataStoreIdsSelector,omitempty" tf:"-"`

	// Required. The display name of the engine. Should be human readable. UTF-8 encoded string with limit of 1024 characters.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The industry vertical that the engine registers. The restriction of the Engine industry vertical is based on DataStore: If unspecified, default to GENERIC. Vertical on Engine has to match vertical of the DataStore liniked to the engine.
	// Default value is GENERIC.
	// Possible values are: GENERIC, MEDIA.
	IndustryVertical *string `json:"industryVertical,omitempty" tf:"industry_vertical,omitempty"`

	// Configurations for a Media Recommendation Engine. Only applicable on the data stores
	// with SOLUTION_TYPE_RECOMMENDATION solution type and MEDIA industry vertical.
	// Structure is documented below.
	MediaRecommendationEngineConfig *MediaRecommendationEngineConfigInitParameters `json:"mediaRecommendationEngineConfig,omitempty" tf:"media_recommendation_engine_config,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`
}

type RecommendationEngineObservation struct {

	// Common config spec that specifies the metadata of the engine.
	// Structure is documented below.
	CommonConfig *RecommendationEngineCommonConfigObservation `json:"commonConfig,omitempty" tf:"common_config,omitempty"`

	// Timestamp the Engine was created at.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// The data stores associated with this engine. For SOLUTION_TYPE_RECOMMENDATION type of engines, they can only associate with at most one data store.
	DataStoreIds []*string `json:"dataStoreIds,omitempty" tf:"data_store_ids,omitempty"`

	// Required. The display name of the engine. Should be human readable. UTF-8 encoded string with limit of 1024 characters.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// an identifier for the resource with format projects/{{project}}/locations/{{location}}/collections/default_collection/engines/{{engine_id}}
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The industry vertical that the engine registers. The restriction of the Engine industry vertical is based on DataStore: If unspecified, default to GENERIC. Vertical on Engine has to match vertical of the DataStore liniked to the engine.
	// Default value is GENERIC.
	// Possible values are: GENERIC, MEDIA.
	IndustryVertical *string `json:"industryVertical,omitempty" tf:"industry_vertical,omitempty"`

	// The geographic location where the data store should reside. The value can
	// only be one of "global", "us" and "eu".
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// Configurations for a Media Recommendation Engine. Only applicable on the data stores
	// with SOLUTION_TYPE_RECOMMENDATION solution type and MEDIA industry vertical.
	// Structure is documented below.
	MediaRecommendationEngineConfig *MediaRecommendationEngineConfigObservation `json:"mediaRecommendationEngineConfig,omitempty" tf:"media_recommendation_engine_config,omitempty"`

	// The unique full resource name of the recommendation engine. Values are of the format
	// projects/{project}/locations/{location}/collections/{collection}/engines/{engine_id}.
	// This field must be a UTF-8 encoded string with a length limit of 1024 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Timestamp the Engine was last updated.
	UpdateTime *string `json:"updateTime,omitempty" tf:"update_time,omitempty"`
}

type RecommendationEngineParameters struct {

	// Common config spec that specifies the metadata of the engine.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	CommonConfig *RecommendationEngineCommonConfigParameters `json:"commonConfig,omitempty" tf:"common_config,omitempty"`

	// The data stores associated with this engine. For SOLUTION_TYPE_RECOMMENDATION type of engines, they can only associate with at most one data store.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/cluster/discoveryengine/v1beta1.DataStore
	// +kubebuilder:validation:Optional
	DataStoreIds []*string `json:"dataStoreIds,omitempty" tf:"data_store_ids,omitempty"`

	// References to DataStore in discoveryengine to populate dataStoreIds.
	// +kubebuilder:validation:Optional
	DataStoreIdsRefs []v1.Reference `json:"dataStoreIdsRefs,omitempty" tf:"-"`

	// Selector for a list of DataStore in discoveryengine to populate dataStoreIds.
	// +kubebuilder:validation:Optional
	DataStoreIdsSelector *v1.Selector `json:"dataStoreIdsSelector,omitempty" tf:"-"`

	// Required. The display name of the engine. Should be human readable. UTF-8 encoded string with limit of 1024 characters.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The industry vertical that the engine registers. The restriction of the Engine industry vertical is based on DataStore: If unspecified, default to GENERIC. Vertical on Engine has to match vertical of the DataStore liniked to the engine.
	// Default value is GENERIC.
	// Possible values are: GENERIC, MEDIA.
	// +kubebuilder:validation:Optional
	IndustryVertical *string `json:"industryVertical,omitempty" tf:"industry_vertical,omitempty"`

	// The geographic location where the data store should reside. The value can
	// only be one of "global", "us" and "eu".
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/cluster/discoveryengine/v1beta1.DataStore
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("location",false)
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// Reference to a DataStore in discoveryengine to populate location.
	// +kubebuilder:validation:Optional
	LocationRef *v1.Reference `json:"locationRef,omitempty" tf:"-"`

	// Selector for a DataStore in discoveryengine to populate location.
	// +kubebuilder:validation:Optional
	LocationSelector *v1.Selector `json:"locationSelector,omitempty" tf:"-"`

	// Configurations for a Media Recommendation Engine. Only applicable on the data stores
	// with SOLUTION_TYPE_RECOMMENDATION solution type and MEDIA industry vertical.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	MediaRecommendationEngineConfig *MediaRecommendationEngineConfigParameters `json:"mediaRecommendationEngineConfig,omitempty" tf:"media_recommendation_engine_config,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`
}

type RecommendedForYouConfigInitParameters struct {

	// The type of event with which the engine is queried at prediction time.
	// If set to generic, only view-item, media-play,and
	// media-complete will be used as context-event in engine training. If
	// set to view-home-page, view-home-page will also be used as
	// context-events in addition to view-item, media-play, and
	// media-complete. Currently supported for the recommended-for-you
	// engine. Currently supported values: view-home-page, generic.
	ContextEventType *string `json:"contextEventType,omitempty" tf:"context_event_type,omitempty"`
}

type RecommendedForYouConfigObservation struct {

	// The type of event with which the engine is queried at prediction time.
	// If set to generic, only view-item, media-play,and
	// media-complete will be used as context-event in engine training. If
	// set to view-home-page, view-home-page will also be used as
	// context-events in addition to view-item, media-play, and
	// media-complete. Currently supported for the recommended-for-you
	// engine. Currently supported values: view-home-page, generic.
	ContextEventType *string `json:"contextEventType,omitempty" tf:"context_event_type,omitempty"`
}

type RecommendedForYouConfigParameters struct {

	// The type of event with which the engine is queried at prediction time.
	// If set to generic, only view-item, media-play,and
	// media-complete will be used as context-event in engine training. If
	// set to view-home-page, view-home-page will also be used as
	// context-events in addition to view-item, media-play, and
	// media-complete. Currently supported for the recommended-for-you
	// engine. Currently supported values: view-home-page, generic.
	// +kubebuilder:validation:Optional
	ContextEventType *string `json:"contextEventType,omitempty" tf:"context_event_type,omitempty"`
}

// RecommendationEngineSpec defines the desired state of RecommendationEngine
type RecommendationEngineSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RecommendationEngineParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RecommendationEngineInitParameters `json:"initProvider,omitempty"`
}

// RecommendationEngineStatus defines the observed state of RecommendationEngine.
type RecommendationEngineStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RecommendationEngineObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RecommendationEngine is the Schema for the RecommendationEngines API. Vertex AI Search recommendation apps.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,gcp}
type RecommendationEngine struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	Spec   RecommendationEngineSpec   `json:"spec"`
	Status RecommendationEngineStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RecommendationEngineList contains a list of RecommendationEngines
type RecommendationEngineList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RecommendationEngine `json:"items"`
}

// Repository type metadata.
var (
	RecommendationEngine_Kind             = "RecommendationEngine"
	RecommendationEngine_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RecommendationEngine_Kind}.String()
	RecommendationEngine_KindAPIVersion   = RecommendationEngine_Kind + "." + CRDGroupVersion.String()
	RecommendationEngine_GroupVersionKind = CRDGroupVersion.WithKind(RecommendationEngine_Kind)
)

func init() {
	SchemeBuilder.Register(&RecommendationEngine{}, &RecommendationEngineList{})
}
