# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: discoveryengine.gcp.m.upbound.io/v1beta1
kind: ChatEngine
metadata:
  annotations:
    meta.upbound.io/example-id: discoveryengine/v1beta1/chatengine
  labels:
    testing.upbound.io/example-name: primary
  name: primary
  namespace: upbound-system
spec:
  forProvider:
    chatEngineConfig:
      agentCreationConfig:
        business: test business name
        defaultLanguageCode: en
        timeZone: America/Los_Angeles
    collectionId: default_collection
    commonConfig:
      companyName: test-company
    dataStoreIdsRefs:
    - name: test_data_store
    - name: test_data_store_2
    displayName: Chat engine
    industryVertical: GENERIC
    locationSelector:
      matchLabels:
        testing.upbound.io/example-name: test_data_store

---

apiVersion: discoveryengine.gcp.m.upbound.io/v1beta1
kind: DataStore
metadata:
  annotations:
    meta.upbound.io/example-id: discoveryengine/v1beta1/chatengine
  labels:
    testing.upbound.io/example-name: test_data_store
  name: test-data-store
  namespace: upbound-system
spec:
  forProvider:
    contentConfig: NO_CONTENT
    displayName: Structured datastore
    industryVertical: GENERIC
    location: global
    solutionTypes:
    - SOLUTION_TYPE_CHAT

---

apiVersion: discoveryengine.gcp.m.upbound.io/v1beta1
kind: DataStore
metadata:
  annotations:
    meta.upbound.io/example-id: discoveryengine/v1beta1/chatengine
  labels:
    testing.upbound.io/example-name: test_data_store_2
  name: test-data-store-2
  namespace: upbound-system
spec:
  forProvider:
    contentConfig: NO_CONTENT
    displayName: Structured datastore 2
    industryVertical: GENERIC
    location: global
    solutionTypes:
    - SOLUTION_TYPE_CHAT
