# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: discoveryengine.gcp.m.upbound.io/v1beta1
kind: Control
metadata:
  annotations:
    meta.upbound.io/example-id: discoveryengine/v1beta1/control
  labels:
    testing.upbound.io/example-name: basic
  name: basic
  namespace: upbound-system
spec:
  forProvider:
    displayName: tf-test-control
    engineIdSelector:
      matchLabels:
        testing.upbound.io/example-name: basic
    locationSelector:
      matchLabels:
        testing.upbound.io/example-name: basic
    solutionType: SOLUTION_TYPE_SEARCH
    synonymsAction:
      synonyms:
      - test
      - experiment
    useCases:
    - SEARCH_USE_CASE_SEARCH

---

apiVersion: discoveryengine.gcp.m.upbound.io/v1beta1
kind: DataStore
metadata:
  annotations:
    meta.upbound.io/example-id: discoveryengine/v1beta1/control
  labels:
    testing.upbound.io/example-name: basic
  name: basic
  namespace: upbound-system
spec:
  forProvider:
    contentConfig: NO_CONTENT
    createAdvancedSiteSearch: false
    displayName: tf-test-datastore
    industryVertical: GENERIC
    location: global
    solutionTypes:
    - SOLUTION_TYPE_SEARCH

---

apiVersion: discoveryengine.gcp.m.upbound.io/v1beta1
kind: SearchEngine
metadata:
  annotations:
    meta.upbound.io/example-id: discoveryengine/v1beta1/control
  labels:
    testing.upbound.io/example-name: basic
  name: basic
  namespace: upbound-system
spec:
  forProvider:
    appType: APP_TYPE_INTRANET
    collectionId: default_collection
    dataStoreIdsRefs:
    - name: basic
    displayName: tf-test-engine
    industryVertical: GENERIC
    locationSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    searchEngineConfig: {}
