// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ConnectionEndpointsInitParameters struct {
}

type ConnectionEndpointsObservation struct {

	// (Output)
	// The IPv4 address assigned to the producer instance network interface. This value will be a range in case of Serverless.
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// (Output)
	// The project id or number of the interface to which the IP was assigned.
	ProjectIDOrNum *string `json:"projectIdOrNum,omitempty" tf:"project_id_or_num,omitempty"`

	// (Output)
	// Alias IP ranges from the same subnetwork.
	SecondaryIPCidrRanges *string `json:"secondaryIpCidrRanges,omitempty" tf:"secondary_ip_cidr_ranges,omitempty"`

	// (Output)
	// The status of a connected endpoint to this network attachment.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (Output)
	// The subnetwork used to assign the IP to the producer instance network interface.
	Subnetwork *string `json:"subnetwork,omitempty" tf:"subnetwork,omitempty"`
}

type ConnectionEndpointsParameters struct {
}

type NetworkAttachmentInitParameters struct {

	// The connection preference of service attachment. The value can be set to ACCEPT_AUTOMATIC. An ACCEPT_AUTOMATIC service attachment is one that always accepts the connection from consumer forwarding rules.
	// Possible values are: ACCEPT_AUTOMATIC, ACCEPT_MANUAL, INVALID.
	ConnectionPreference *string `json:"connectionPreference,omitempty" tf:"connection_preference,omitempty"`

	// An optional description of this resource. Provide this property when you create the resource.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Projects that are allowed to connect to this network attachment. The project can be specified using its id or number.
	ProducerAcceptLists []*string `json:"producerAcceptLists,omitempty" tf:"producer_accept_lists,omitempty"`

	// Projects that are not allowed to connect to this network attachment. The project can be specified using its id or number.
	ProducerRejectLists []*string `json:"producerRejectLists,omitempty" tf:"producer_reject_lists,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// An array of URLs where each entry is the URL of a subnet provided by the service consumer to use for endpoints in the producers that connect to this network attachment.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/apis/cluster/compute/v1beta2.Subnetwork
	// +crossplane:generate:reference:extractor=github.com/upbound/provider-gcp/config/cluster/common.SelfLinkExtractor()
	Subnetworks []*string `json:"subnetworks,omitempty" tf:"subnetworks,omitempty"`

	// References to Subnetwork in compute to populate subnetworks.
	// +kubebuilder:validation:Optional
	SubnetworksRefs []v1.Reference `json:"subnetworksRefs,omitempty" tf:"-"`

	// Selector for a list of Subnetwork in compute to populate subnetworks.
	// +kubebuilder:validation:Optional
	SubnetworksSelector *v1.Selector `json:"subnetworksSelector,omitempty" tf:"-"`
}

type NetworkAttachmentObservation struct {

	// An array of connections for all the producers connected to this network attachment.
	// Structure is documented below.
	ConnectionEndpoints []ConnectionEndpointsObservation `json:"connectionEndpoints,omitempty" tf:"connection_endpoints,omitempty"`

	// The connection preference of service attachment. The value can be set to ACCEPT_AUTOMATIC. An ACCEPT_AUTOMATIC service attachment is one that always accepts the connection from consumer forwarding rules.
	// Possible values are: ACCEPT_AUTOMATIC, ACCEPT_MANUAL, INVALID.
	ConnectionPreference *string `json:"connectionPreference,omitempty" tf:"connection_preference,omitempty"`

	// Creation timestamp in RFC3339 text format.
	CreationTimestamp *string `json:"creationTimestamp,omitempty" tf:"creation_timestamp,omitempty"`

	// An optional description of this resource. Provide this property when you create the resource.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Fingerprint of this resource. A hash of the contents stored in this object. This
	// field is used in optimistic locking. An up-to-date fingerprint must be provided in order to patch.
	Fingerprint *string `json:"fingerprint,omitempty" tf:"fingerprint,omitempty"`

	// an identifier for the resource with format projects/{{project}}/regions/{{region}}/networkAttachments/{{name}}
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Type of the resource.
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// The URL of the network which the Network Attachment belongs to. Practically it is inferred by fetching the network of the first subnetwork associated.
	// Because it is required that all the subnetworks must be from the same network, it is assured that the Network Attachment belongs to the same network as all the subnetworks.
	Network *string `json:"network,omitempty" tf:"network,omitempty"`

	// Projects that are allowed to connect to this network attachment. The project can be specified using its id or number.
	ProducerAcceptLists []*string `json:"producerAcceptLists,omitempty" tf:"producer_accept_lists,omitempty"`

	// Projects that are not allowed to connect to this network attachment. The project can be specified using its id or number.
	ProducerRejectLists []*string `json:"producerRejectLists,omitempty" tf:"producer_reject_lists,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// URL of the region where the network attachment resides. This field applies only to the region resource. You must specify this field as part of the HTTP request URL. It is not settable as a field in the request body.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Server-defined URL for the resource.
	SelfLink *string `json:"selfLink,omitempty" tf:"self_link,omitempty"`

	// Server-defined URL for this resource's resource id.
	SelfLinkWithID *string `json:"selfLinkWithId,omitempty" tf:"self_link_with_id,omitempty"`

	// An array of URLs where each entry is the URL of a subnet provided by the service consumer to use for endpoints in the producers that connect to this network attachment.
	Subnetworks []*string `json:"subnetworks,omitempty" tf:"subnetworks,omitempty"`
}

type NetworkAttachmentParameters struct {

	// The connection preference of service attachment. The value can be set to ACCEPT_AUTOMATIC. An ACCEPT_AUTOMATIC service attachment is one that always accepts the connection from consumer forwarding rules.
	// Possible values are: ACCEPT_AUTOMATIC, ACCEPT_MANUAL, INVALID.
	// +kubebuilder:validation:Optional
	ConnectionPreference *string `json:"connectionPreference,omitempty" tf:"connection_preference,omitempty"`

	// An optional description of this resource. Provide this property when you create the resource.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Projects that are allowed to connect to this network attachment. The project can be specified using its id or number.
	// +kubebuilder:validation:Optional
	ProducerAcceptLists []*string `json:"producerAcceptLists,omitempty" tf:"producer_accept_lists,omitempty"`

	// Projects that are not allowed to connect to this network attachment. The project can be specified using its id or number.
	// +kubebuilder:validation:Optional
	ProducerRejectLists []*string `json:"producerRejectLists,omitempty" tf:"producer_reject_lists,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// URL of the region where the network attachment resides. This field applies only to the region resource. You must specify this field as part of the HTTP request URL. It is not settable as a field in the request body.
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`

	// An array of URLs where each entry is the URL of a subnet provided by the service consumer to use for endpoints in the producers that connect to this network attachment.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/apis/cluster/compute/v1beta2.Subnetwork
	// +crossplane:generate:reference:extractor=github.com/upbound/provider-gcp/config/cluster/common.SelfLinkExtractor()
	// +kubebuilder:validation:Optional
	Subnetworks []*string `json:"subnetworks,omitempty" tf:"subnetworks,omitempty"`

	// References to Subnetwork in compute to populate subnetworks.
	// +kubebuilder:validation:Optional
	SubnetworksRefs []v1.Reference `json:"subnetworksRefs,omitempty" tf:"-"`

	// Selector for a list of Subnetwork in compute to populate subnetworks.
	// +kubebuilder:validation:Optional
	SubnetworksSelector *v1.Selector `json:"subnetworksSelector,omitempty" tf:"-"`
}

// NetworkAttachmentSpec defines the desired state of NetworkAttachment
type NetworkAttachmentSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NetworkAttachmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NetworkAttachmentInitParameters `json:"initProvider,omitempty"`
}

// NetworkAttachmentStatus defines the observed state of NetworkAttachment.
type NetworkAttachmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NetworkAttachmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NetworkAttachment is the Schema for the NetworkAttachments API. A network attachment is a resource that lets a producer Virtual Private Cloud (VPC) network initiate connections to a consumer VPC network through a Private Service Connect interface.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,gcp}
type NetworkAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.connectionPreference) || (has(self.initProvider) && has(self.initProvider.connectionPreference))",message="spec.forProvider.connectionPreference is a required parameter"
	Spec   NetworkAttachmentSpec   `json:"spec"`
	Status NetworkAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkAttachmentList contains a list of NetworkAttachments
type NetworkAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkAttachment `json:"items"`
}

// Repository type metadata.
var (
	NetworkAttachment_Kind             = "NetworkAttachment"
	NetworkAttachment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NetworkAttachment_Kind}.String()
	NetworkAttachment_KindAPIVersion   = NetworkAttachment_Kind + "." + CRDGroupVersion.String()
	NetworkAttachment_GroupVersionKind = CRDGroupVersion.WithKind(NetworkAttachment_Kind)
)

func init() {
	SchemeBuilder.Register(&NetworkAttachment{}, &NetworkAttachmentList{})
}
