// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type EnrolledServicesInitParameters struct {

	// The product for which Access Approval will be enrolled. Allowed values are listed (case-sensitive):
	CloudProduct *string `json:"cloudProduct,omitempty" tf:"cloud_product,omitempty"`

	// The enrollment level of the service.
	// Default value is BLOCK_ALL.
	// Possible values are: BLOCK_ALL.
	EnrollmentLevel *string `json:"enrollmentLevel,omitempty" tf:"enrollment_level,omitempty"`
}

type EnrolledServicesObservation struct {

	// The product for which Access Approval will be enrolled. Allowed values are listed (case-sensitive):
	CloudProduct *string `json:"cloudProduct,omitempty" tf:"cloud_product,omitempty"`

	// The enrollment level of the service.
	// Default value is BLOCK_ALL.
	// Possible values are: BLOCK_ALL.
	EnrollmentLevel *string `json:"enrollmentLevel,omitempty" tf:"enrollment_level,omitempty"`
}

type EnrolledServicesParameters struct {

	// The product for which Access Approval will be enrolled. Allowed values are listed (case-sensitive):
	// +kubebuilder:validation:Optional
	CloudProduct *string `json:"cloudProduct" tf:"cloud_product,omitempty"`

	// The enrollment level of the service.
	// Default value is BLOCK_ALL.
	// Possible values are: BLOCK_ALL.
	// +kubebuilder:validation:Optional
	EnrollmentLevel *string `json:"enrollmentLevel,omitempty" tf:"enrollment_level,omitempty"`
}

type FolderSettingsInitParameters struct {

	// The asymmetric crypto key version to use for signing approval requests.
	// Empty active_key_version indicates that a Google-managed key should be used for signing.
	// This property will be ignored if set by an ancestor of the resource, and new non-empty values may not be set.
	ActiveKeyVersion *string `json:"activeKeyVersion,omitempty" tf:"active_key_version,omitempty"`

	// A list of Google Cloud Services for which the given resource has Access Approval enrolled.
	// Access requests for the resource given by name against any of these services contained here will be required
	// to have explicit approval. Enrollment can only be done on an all or nothing basis.
	// A maximum of 10 enrolled services will be enforced, to be expanded as the set of supported services is expanded.
	// Structure is documented below.
	EnrolledServices []EnrolledServicesInitParameters `json:"enrolledServices,omitempty" tf:"enrolled_services,omitempty"`

	// A list of email addresses to which notifications relating to approval requests should be sent.
	// Notifications relating to a resource will be sent to all emails in the settings of ancestor
	// resources of that resource. A maximum of 50 email addresses are allowed.
	// +listType=set
	NotificationEmails []*string `json:"notificationEmails,omitempty" tf:"notification_emails,omitempty"`
}

type FolderSettingsObservation struct {

	// The asymmetric crypto key version to use for signing approval requests.
	// Empty active_key_version indicates that a Google-managed key should be used for signing.
	// This property will be ignored if set by an ancestor of the resource, and new non-empty values may not be set.
	ActiveKeyVersion *string `json:"activeKeyVersion,omitempty" tf:"active_key_version,omitempty"`

	// If the field is true, that indicates that an ancestor of this Folder has set active_key_version.
	AncestorHasActiveKeyVersion *bool `json:"ancestorHasActiveKeyVersion,omitempty" tf:"ancestor_has_active_key_version,omitempty"`

	// If the field is true, that indicates that at least one service is enrolled for Access Approval in one or more ancestors of the Folder.
	EnrolledAncestor *bool `json:"enrolledAncestor,omitempty" tf:"enrolled_ancestor,omitempty"`

	// A list of Google Cloud Services for which the given resource has Access Approval enrolled.
	// Access requests for the resource given by name against any of these services contained here will be required
	// to have explicit approval. Enrollment can only be done on an all or nothing basis.
	// A maximum of 10 enrolled services will be enforced, to be expanded as the set of supported services is expanded.
	// Structure is documented below.
	EnrolledServices []EnrolledServicesObservation `json:"enrolledServices,omitempty" tf:"enrolled_services,omitempty"`

	// ID of the folder of the access approval settings.
	FolderID *string `json:"folderId,omitempty" tf:"folder_id,omitempty"`

	// an identifier for the resource with format folders/{{folder_id}}/accessApprovalSettings
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// If the field is true, that indicates that there is some configuration issue with the active_key_version
	// configured on this Folder (e.g. it doesn't exist or the Access Approval service account doesn't have the
	// correct permissions on it, etc.) This key version is not necessarily the effective key version at this level,
	// as key versions are inherited top-down.
	InvalidKeyVersion *bool `json:"invalidKeyVersion,omitempty" tf:"invalid_key_version,omitempty"`

	// The resource name of the settings. Format is "folders/{folder_id}/accessApprovalSettings"
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A list of email addresses to which notifications relating to approval requests should be sent.
	// Notifications relating to a resource will be sent to all emails in the settings of ancestor
	// resources of that resource. A maximum of 50 email addresses are allowed.
	// +listType=set
	NotificationEmails []*string `json:"notificationEmails,omitempty" tf:"notification_emails,omitempty"`
}

type FolderSettingsParameters struct {

	// The asymmetric crypto key version to use for signing approval requests.
	// Empty active_key_version indicates that a Google-managed key should be used for signing.
	// This property will be ignored if set by an ancestor of the resource, and new non-empty values may not be set.
	// +kubebuilder:validation:Optional
	ActiveKeyVersion *string `json:"activeKeyVersion,omitempty" tf:"active_key_version,omitempty"`

	// A list of Google Cloud Services for which the given resource has Access Approval enrolled.
	// Access requests for the resource given by name against any of these services contained here will be required
	// to have explicit approval. Enrollment can only be done on an all or nothing basis.
	// A maximum of 10 enrolled services will be enforced, to be expanded as the set of supported services is expanded.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	EnrolledServices []EnrolledServicesParameters `json:"enrolledServices,omitempty" tf:"enrolled_services,omitempty"`

	// ID of the folder of the access approval settings.
	// +kubebuilder:validation:Required
	FolderID *string `json:"folderId" tf:"folder_id,omitempty"`

	// A list of email addresses to which notifications relating to approval requests should be sent.
	// Notifications relating to a resource will be sent to all emails in the settings of ancestor
	// resources of that resource. A maximum of 50 email addresses are allowed.
	// +kubebuilder:validation:Optional
	// +listType=set
	NotificationEmails []*string `json:"notificationEmails,omitempty" tf:"notification_emails,omitempty"`
}

// FolderSettingsSpec defines the desired state of FolderSettings
type FolderSettingsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FolderSettingsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FolderSettingsInitParameters `json:"initProvider,omitempty"`
}

// FolderSettingsStatus defines the observed state of FolderSettings.
type FolderSettingsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FolderSettingsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FolderSettings is the Schema for the FolderSettingss API. Access Approval enables you to require your explicit approval whenever Google support and engineering need to access your customer content.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,gcp}
type FolderSettings struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enrolledServices) || (has(self.initProvider) && has(self.initProvider.enrolledServices))",message="spec.forProvider.enrolledServices is a required parameter"
	Spec   FolderSettingsSpec   `json:"spec"`
	Status FolderSettingsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FolderSettingsList contains a list of FolderSettingss
type FolderSettingsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FolderSettings `json:"items"`
}

// Repository type metadata.
var (
	FolderSettings_Kind             = "FolderSettings"
	FolderSettings_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FolderSettings_Kind}.String()
	FolderSettings_KindAPIVersion   = FolderSettings_Kind + "." + CRDGroupVersion.String()
	FolderSettings_GroupVersionKind = CRDGroupVersion.WithKind(FolderSettings_Kind)
)

func init() {
	SchemeBuilder.Register(&FolderSettings{}, &FolderSettingsList{})
}
