apiVersion: kms.gcp.upbound.io/v1beta1
kind: SecretCiphertext
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1beta1/secretciphertext
  labels:
    testing.upbound.io/example-name: my_password
  name: my-password
spec:
  forProvider:
    cryptoKeySelector:
      matchLabels:
        testing.upbound.io/example-name: cryptokey
    plaintext: my-secret-password

---

apiVersion: kms.gcp.upbound.io/v1beta2
kind: CryptoKey
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1beta1/secretciphertext
  labels:
    testing.upbound.io/example-name: cryptokey
  name: cryptokey
spec:
  forProvider:
    keyRingSelector:
      matchLabels:
        testing.upbound.io/example-name: keyring
    rotationPeriod: 7776000s

---

apiVersion: kms.gcp.upbound.io/v1beta1
kind: KeyRing
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1beta1/secretciphertext
  labels:
    testing.upbound.io/example-name: keyring
  name: keyring
spec:
  forProvider:
    location: global
