// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by angryjet. DO NOT EDIT.
// Code transformed by upjet. DO NOT EDIT.

package v1beta1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	xpresource "github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	apisresolver "github.com/upbound/provider-gcp/v3/internal/apis"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

func (mg *Repository) ResolveReferences( // ResolveReferences of this Repository.
	ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	if mg.Spec.ForProvider.GitRemoteSettings != nil {
		{
			m, l, err = apisresolver.GetManagedResource("secretmanager.gcp.upbound.io", "v1beta1", "SecretVersion", "SecretVersionList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.GitRemoteSettings.AuthenticationTokenSecretVersion),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.GitRemoteSettings.AuthenticationTokenSecretVersionRef,
				Selector:     mg.Spec.ForProvider.GitRemoteSettings.AuthenticationTokenSecretVersionSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.GitRemoteSettings.AuthenticationTokenSecretVersion")
		}
		mg.Spec.ForProvider.GitRemoteSettings.AuthenticationTokenSecretVersion = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.GitRemoteSettings.AuthenticationTokenSecretVersionRef = rsp.ResolvedReference

	}
	{
		m, l, err = apisresolver.GetManagedResource("kms.gcp.upbound.io", "v1beta2", "CryptoKey", "CryptoKeyList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.KMSKeyName),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.KMSKeyNameRef,
			Selector:     mg.Spec.ForProvider.KMSKeyNameSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.KMSKeyName")
	}
	mg.Spec.ForProvider.KMSKeyName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.KMSKeyNameRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("secretmanager.gcp.upbound.io", "v1beta1", "SecretVersion", "SecretVersionList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.NpmrcEnvironmentVariablesSecretVersion),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.NpmrcEnvironmentVariablesSecretVersionRef,
			Selector:     mg.Spec.ForProvider.NpmrcEnvironmentVariablesSecretVersionSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NpmrcEnvironmentVariablesSecretVersion")
	}
	mg.Spec.ForProvider.NpmrcEnvironmentVariablesSecretVersion = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NpmrcEnvironmentVariablesSecretVersionRef = rsp.ResolvedReference

	if mg.Spec.InitProvider.GitRemoteSettings != nil {
		{
			m, l, err = apisresolver.GetManagedResource("secretmanager.gcp.upbound.io", "v1beta1", "SecretVersion", "SecretVersionList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.GitRemoteSettings.AuthenticationTokenSecretVersion),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.GitRemoteSettings.AuthenticationTokenSecretVersionRef,
				Selector:     mg.Spec.InitProvider.GitRemoteSettings.AuthenticationTokenSecretVersionSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.GitRemoteSettings.AuthenticationTokenSecretVersion")
		}
		mg.Spec.InitProvider.GitRemoteSettings.AuthenticationTokenSecretVersion = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.GitRemoteSettings.AuthenticationTokenSecretVersionRef = rsp.ResolvedReference

	}
	{
		m, l, err = apisresolver.GetManagedResource("kms.gcp.upbound.io", "v1beta2", "CryptoKey", "CryptoKeyList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.KMSKeyName),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.KMSKeyNameRef,
			Selector:     mg.Spec.InitProvider.KMSKeyNameSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.KMSKeyName")
	}
	mg.Spec.InitProvider.KMSKeyName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.KMSKeyNameRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("secretmanager.gcp.upbound.io", "v1beta1", "SecretVersion", "SecretVersionList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.NpmrcEnvironmentVariablesSecretVersion),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.NpmrcEnvironmentVariablesSecretVersionRef,
			Selector:     mg.Spec.InitProvider.NpmrcEnvironmentVariablesSecretVersionSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.NpmrcEnvironmentVariablesSecretVersion")
	}
	mg.Spec.InitProvider.NpmrcEnvironmentVariablesSecretVersion = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NpmrcEnvironmentVariablesSecretVersionRef = rsp.ResolvedReference

	return nil
}
