// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ReleaseChannelSettingBindingInitParameters struct {

	// Labels as key value pairs.
	// Note: This field is non-authoritative, and will only manage the labels present in your configuration.
	// Please refer to the field effective_labels for all of the labels present on the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Product type of the setting binding.
	// Possible values are: GEMINI_CLOUD_ASSIST, GEMINI_CODE_ASSIST.
	Product *string `json:"product,omitempty" tf:"product,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Target of the binding.
	Target *string `json:"target,omitempty" tf:"target,omitempty"`
}

type ReleaseChannelSettingBindingObservation struct {

	// Create time stamp.
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// +mapType=granular
	EffectiveLabels map[string]*string `json:"effectiveLabels,omitempty" tf:"effective_labels,omitempty"`

	// an identifier for the resource with format projects/{{project}}/locations/{{location}}/releaseChannelSettings/{{release_channel_setting_id}}/settingBindings/{{setting_binding_id}}
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels as key value pairs.
	// Note: This field is non-authoritative, and will only manage the labels present in your configuration.
	// Please refer to the field effective_labels for all of the labels present on the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Resource ID segment making up resource name. It identifies the resource within its parent collection as described in https://google.aip.dev/122.
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// Identifier. Name of the resource.
	// Format:projects/{project}/locations/{location}/releaseChannelSettings/{setting}/settingBindings/{setting_binding}
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Product type of the setting binding.
	// Possible values are: GEMINI_CLOUD_ASSIST, GEMINI_CODE_ASSIST.
	Product *string `json:"product,omitempty" tf:"product,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Resource ID segment making up resource name. It identifies the resource within its parent collection as described in https://google.aip.dev/122.
	ReleaseChannelSettingID *string `json:"releaseChannelSettingId,omitempty" tf:"release_channel_setting_id,omitempty"`

	// Target of the binding.
	Target *string `json:"target,omitempty" tf:"target,omitempty"`

	// The combination of labels configured directly on the resource
	// and default labels configured on the provider.
	// +mapType=granular
	TerraformLabels map[string]*string `json:"terraformLabels,omitempty" tf:"terraform_labels,omitempty"`

	// Update time stamp.
	UpdateTime *string `json:"updateTime,omitempty" tf:"update_time,omitempty"`
}

type ReleaseChannelSettingBindingParameters struct {

	// Labels as key value pairs.
	// Note: This field is non-authoritative, and will only manage the labels present in your configuration.
	// Please refer to the field effective_labels for all of the labels present on the resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Resource ID segment making up resource name. It identifies the resource within its parent collection as described in https://google.aip.dev/122.
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// Product type of the setting binding.
	// Possible values are: GEMINI_CLOUD_ASSIST, GEMINI_CODE_ASSIST.
	// +kubebuilder:validation:Optional
	Product *string `json:"product,omitempty" tf:"product,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Resource ID segment making up resource name. It identifies the resource within its parent collection as described in https://google.aip.dev/122.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/cluster/gemini/v1beta1.ReleaseChannelSetting
	// +kubebuilder:validation:Optional
	ReleaseChannelSettingID *string `json:"releaseChannelSettingId,omitempty" tf:"release_channel_setting_id,omitempty"`

	// Reference to a ReleaseChannelSetting in gemini to populate releaseChannelSettingId.
	// +kubebuilder:validation:Optional
	ReleaseChannelSettingIDRef *v1.Reference `json:"releaseChannelSettingIdRef,omitempty" tf:"-"`

	// Selector for a ReleaseChannelSetting in gemini to populate releaseChannelSettingId.
	// +kubebuilder:validation:Optional
	ReleaseChannelSettingIDSelector *v1.Selector `json:"releaseChannelSettingIdSelector,omitempty" tf:"-"`

	// Target of the binding.
	// +kubebuilder:validation:Optional
	Target *string `json:"target,omitempty" tf:"target,omitempty"`
}

// ReleaseChannelSettingBindingSpec defines the desired state of ReleaseChannelSettingBinding
type ReleaseChannelSettingBindingSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ReleaseChannelSettingBindingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ReleaseChannelSettingBindingInitParameters `json:"initProvider,omitempty"`
}

// ReleaseChannelSettingBindingStatus defines the observed state of ReleaseChannelSettingBinding.
type ReleaseChannelSettingBindingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ReleaseChannelSettingBindingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ReleaseChannelSettingBinding is the Schema for the ReleaseChannelSettingBindings API. The resource for managing ReleaseChannel setting bindings for Admin Control.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,gcp}
type ReleaseChannelSettingBinding struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.target) || (has(self.initProvider) && has(self.initProvider.target))",message="spec.forProvider.target is a required parameter"
	Spec   ReleaseChannelSettingBindingSpec   `json:"spec"`
	Status ReleaseChannelSettingBindingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ReleaseChannelSettingBindingList contains a list of ReleaseChannelSettingBindings
type ReleaseChannelSettingBindingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ReleaseChannelSettingBinding `json:"items"`
}

// Repository type metadata.
var (
	ReleaseChannelSettingBinding_Kind             = "ReleaseChannelSettingBinding"
	ReleaseChannelSettingBinding_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ReleaseChannelSettingBinding_Kind}.String()
	ReleaseChannelSettingBinding_KindAPIVersion   = ReleaseChannelSettingBinding_Kind + "." + CRDGroupVersion.String()
	ReleaseChannelSettingBinding_GroupVersionKind = CRDGroupVersion.WithKind(ReleaseChannelSettingBinding_Kind)
)

func init() {
	SchemeBuilder.Register(&ReleaseChannelSettingBinding{}, &ReleaseChannelSettingBindingList{})
}
