// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ConditionInitParameters struct {
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type ConditionObservation struct {
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type ConditionParameters struct {

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Optional
	Expression *string `json:"expression" tf:"expression,omitempty"`

	// +kubebuilder:validation:Optional
	Title *string `json:"title" tf:"title,omitempty"`
}

type RepositoryGroupIAMMemberInitParameters struct {

	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/cluster/gemini/v1beta1.CodeRepositoryIndex
	CodeRepositoryIndex *string `json:"codeRepositoryIndex,omitempty" tf:"code_repository_index,omitempty"`

	// Reference to a CodeRepositoryIndex in gemini to populate codeRepositoryIndex.
	// +kubebuilder:validation:Optional
	CodeRepositoryIndexRef *v1.Reference `json:"codeRepositoryIndexRef,omitempty" tf:"-"`

	// Selector for a CodeRepositoryIndex in gemini to populate codeRepositoryIndex.
	// +kubebuilder:validation:Optional
	CodeRepositoryIndexSelector *v1.Selector `json:"codeRepositoryIndexSelector,omitempty" tf:"-"`

	Condition *ConditionInitParameters `json:"condition,omitempty" tf:"condition,omitempty"`

	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	Member *string `json:"member,omitempty" tf:"member,omitempty"`

	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/cluster/gemini/v1beta1.RepositoryGroup
	RepositoryGroupID *string `json:"repositoryGroupId,omitempty" tf:"repository_group_id,omitempty"`

	// Reference to a RepositoryGroup in gemini to populate repositoryGroupId.
	// +kubebuilder:validation:Optional
	RepositoryGroupIDRef *v1.Reference `json:"repositoryGroupIdRef,omitempty" tf:"-"`

	// Selector for a RepositoryGroup in gemini to populate repositoryGroupId.
	// +kubebuilder:validation:Optional
	RepositoryGroupIDSelector *v1.Selector `json:"repositoryGroupIdSelector,omitempty" tf:"-"`

	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

type RepositoryGroupIAMMemberObservation struct {
	CodeRepositoryIndex *string `json:"codeRepositoryIndex,omitempty" tf:"code_repository_index,omitempty"`

	Condition *ConditionObservation `json:"condition,omitempty" tf:"condition,omitempty"`

	Etag *string `json:"etag,omitempty" tf:"etag,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	Member *string `json:"member,omitempty" tf:"member,omitempty"`

	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	RepositoryGroupID *string `json:"repositoryGroupId,omitempty" tf:"repository_group_id,omitempty"`

	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

type RepositoryGroupIAMMemberParameters struct {

	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/cluster/gemini/v1beta1.CodeRepositoryIndex
	// +kubebuilder:validation:Optional
	CodeRepositoryIndex *string `json:"codeRepositoryIndex,omitempty" tf:"code_repository_index,omitempty"`

	// Reference to a CodeRepositoryIndex in gemini to populate codeRepositoryIndex.
	// +kubebuilder:validation:Optional
	CodeRepositoryIndexRef *v1.Reference `json:"codeRepositoryIndexRef,omitempty" tf:"-"`

	// Selector for a CodeRepositoryIndex in gemini to populate codeRepositoryIndex.
	// +kubebuilder:validation:Optional
	CodeRepositoryIndexSelector *v1.Selector `json:"codeRepositoryIndexSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	Condition *ConditionParameters `json:"condition,omitempty" tf:"condition,omitempty"`

	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// +kubebuilder:validation:Optional
	Member *string `json:"member,omitempty" tf:"member,omitempty"`

	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/cluster/gemini/v1beta1.RepositoryGroup
	// +kubebuilder:validation:Optional
	RepositoryGroupID *string `json:"repositoryGroupId,omitempty" tf:"repository_group_id,omitempty"`

	// Reference to a RepositoryGroup in gemini to populate repositoryGroupId.
	// +kubebuilder:validation:Optional
	RepositoryGroupIDRef *v1.Reference `json:"repositoryGroupIdRef,omitempty" tf:"-"`

	// Selector for a RepositoryGroup in gemini to populate repositoryGroupId.
	// +kubebuilder:validation:Optional
	RepositoryGroupIDSelector *v1.Selector `json:"repositoryGroupIdSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

// RepositoryGroupIAMMemberSpec defines the desired state of RepositoryGroupIAMMember
type RepositoryGroupIAMMemberSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RepositoryGroupIAMMemberParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RepositoryGroupIAMMemberInitParameters `json:"initProvider,omitempty"`
}

// RepositoryGroupIAMMemberStatus defines the observed state of RepositoryGroupIAMMember.
type RepositoryGroupIAMMemberStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RepositoryGroupIAMMemberObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RepositoryGroupIAMMember is the Schema for the RepositoryGroupIAMMembers API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,gcp}
type RepositoryGroupIAMMember struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.member) || (has(self.initProvider) && has(self.initProvider.member))",message="spec.forProvider.member is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.role) || (has(self.initProvider) && has(self.initProvider.role))",message="spec.forProvider.role is a required parameter"
	Spec   RepositoryGroupIAMMemberSpec   `json:"spec"`
	Status RepositoryGroupIAMMemberStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RepositoryGroupIAMMemberList contains a list of RepositoryGroupIAMMembers
type RepositoryGroupIAMMemberList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RepositoryGroupIAMMember `json:"items"`
}

// Repository type metadata.
var (
	RepositoryGroupIAMMember_Kind             = "RepositoryGroupIAMMember"
	RepositoryGroupIAMMember_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RepositoryGroupIAMMember_Kind}.String()
	RepositoryGroupIAMMember_KindAPIVersion   = RepositoryGroupIAMMember_Kind + "." + CRDGroupVersion.String()
	RepositoryGroupIAMMember_GroupVersionKind = CRDGroupVersion.WithKind(RepositoryGroupIAMMember_Kind)
)

func init() {
	SchemeBuilder.Register(&RepositoryGroupIAMMember{}, &RepositoryGroupIAMMemberList{})
}
