apiVersion: vertexai.gcp.m.upbound.io/v1beta1
kind: FeatureOnlineStoreFeatureview
metadata:
  annotations:
    meta.upbound.io/example-id: vertexai/v1beta1/featureonlinestorefeatureview
  labels:
    testing.upbound.io/example-name: featureview
  name: featureview
  namespace: upbound-system
spec:
  forProvider:
    bigQuerySource:
    - entityIdColumns:
      - test_entity_column
      uri: bq://${google_bigquery_table.tf-test-table.project}.${google_bigquery_table.tf-test-table.dataset_id}.${google_bigquery_table.tf-test-table.table_id}
    featureOnlineStoreSelector:
      matchLabels:
        testing.upbound.io/example-name: featureonlinestore
    region: us-central1
    syncConfig:
    - cron: 0 0 * * *

---

apiVersion: vertexai.gcp.m.upbound.io/v1beta1
kind: FeatureOnlineStore
metadata:
  annotations:
    meta.upbound.io/example-id: vertexai/v1beta1/featureonlinestorefeatureview
  labels:
    testing.upbound.io/example-name: featureonlinestore
  name: featureonlinestore
  namespace: upbound-system
spec:
  forProvider:
    bigtable:
    - autoScaling:
      - cpuUtilizationTarget: 80
        maxNodeCount: 2
        minNodeCount: 1
    labels:
      foo: bar
    region: us-central1
