# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: vertexai.gcp.m.upbound.io/v1beta1
kind: Index
metadata:
  annotations:
    meta.upbound.io/example-id: vertexai/v1beta1/index
  labels:
    testing.upbound.io/example-name: index
  name: index
  namespace: upbound-system
spec:
  forProvider:
    description: index for test
    displayName: test-index
    encryptionSpec:
      kmsKeyName: kms-name
    indexUpdateMethod: BATCH_UPDATE
    labels:
      foo: bar
    metadata:
      config:
        algorithmConfig:
          treeAhConfig:
            leafNodeEmbeddingCount: 500
            leafNodesToSearchPercent: 7
        approximateNeighborsCount: 150
        dimensions: 2
        distanceMeasureType: DOT_PRODUCT_DISTANCE
        shardSize: SHARD_SIZE_SMALL
      contentsDeltaUri: gs://${google_storage_bucket.bucket.name}/contents
    provider: ${google-beta}
    region: us-central1

---

apiVersion: storage.gcp.m.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: vertexai/v1beta1/index
  labels:
    testing.upbound.io/example-name: bucket
  name: bucket
  namespace: upbound-system
spec:
  forProvider:
    location: us-central1
    provider: ${google-beta}
    uniformBucketLevelAccess: true

---

apiVersion: storage.gcp.m.upbound.io/v1beta1
kind: BucketObject
metadata:
  annotations:
    meta.upbound.io/example-id: vertexai/v1beta1/index
  labels:
    testing.upbound.io/example-name: data
  name: data
  namespace: upbound-system
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: bucket
    content: |
      {"id": "42", "embedding": [0.5, 1.0], "restricts": [{"namespace": "class", "allow": ["cat", "pet"]},{"namespace": "category", "allow": ["feline"]}]}
      {"id": "43", "embedding": [0.6, 1.0], "restricts": [{"namespace": "class", "allow": ["dog", "pet"]},{"namespace": "category", "allow": ["canine"]}]}
    name: contents/data.json
    provider: ${google-beta}
