// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type UserWorkloadsSecretInitParameters struct {
	Data map[string]*string `json:"dataSecretRef,omitempty" tf:"-"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/namespaced/cloudplatform/v1beta1.Project
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in cloudplatform to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v1.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in cloudplatform to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v1.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`
}

type UserWorkloadsSecretObservation struct {

	// Environment where the Kubernetes Secret will be stored and used.
	Environment *string `json:"environment,omitempty" tf:"environment,omitempty"`

	// an identifier for the resource with format projects/{{project}}/locations/{{region}}/environments/{{environment}}/userWorkloadsSecrets/{{name}}
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The location or Compute Engine region for the environment.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type UserWorkloadsSecretParameters struct {

	// The "data" field of Kubernetes Secret, organized in key-value pairs,
	// which can contain sensitive values such as a password, a token, or a key. To protect sensitive data,
	// follow the best practices outlined in the HashiCorp documentation:
	// https://developer.hashicorp.
	// The values for all keys have to be base64-encoded strings.
	// For details see: https://kubernetes.io/docs/concepts/configuration/secret/
	// +kubebuilder:validation:Optional
	DataSecretRef *v1.LocalSecretReference `json:"dataSecretRef,omitempty" tf:"-"`

	// Environment where the Kubernetes Secret will be stored and used.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/namespaced/composer/v1beta1.Environment
	// +kubebuilder:validation:Required
	Environment *string `json:"environment" tf:"environment,omitempty"`

	// Reference to a Environment in composer to populate environment.
	// +kubebuilder:validation:Optional
	EnvironmentRef *v1.NamespacedReference `json:"environmentRef,omitempty" tf:"-"`

	// Selector for a Environment in composer to populate environment.
	// +kubebuilder:validation:Optional
	EnvironmentSelector *v1.NamespacedSelector `json:"environmentSelector,omitempty" tf:"-"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/namespaced/cloudplatform/v1beta1.Project
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in cloudplatform to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v1.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in cloudplatform to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v1.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`

	// The location or Compute Engine region for the environment.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

// UserWorkloadsSecretSpec defines the desired state of UserWorkloadsSecret
type UserWorkloadsSecretSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            UserWorkloadsSecretParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserWorkloadsSecretInitParameters `json:"initProvider,omitempty"`
}

// UserWorkloadsSecretStatus defines the observed state of UserWorkloadsSecret.
type UserWorkloadsSecretStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserWorkloadsSecretObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// UserWorkloadsSecret is the Schema for the UserWorkloadsSecrets API. User workloads Secret used by Airflow tasks that run with Kubernetes Executor or KubernetesPodOperator.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gcp}
type UserWorkloadsSecret struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              UserWorkloadsSecretSpec   `json:"spec"`
	Status            UserWorkloadsSecretStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserWorkloadsSecretList contains a list of UserWorkloadsSecrets
type UserWorkloadsSecretList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UserWorkloadsSecret `json:"items"`
}

// Repository type metadata.
var (
	UserWorkloadsSecret_Kind             = "UserWorkloadsSecret"
	UserWorkloadsSecret_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UserWorkloadsSecret_Kind}.String()
	UserWorkloadsSecret_KindAPIVersion   = UserWorkloadsSecret_Kind + "." + CRDGroupVersion.String()
	UserWorkloadsSecret_GroupVersionKind = CRDGroupVersion.WithKind(UserWorkloadsSecret_Kind)
)

func init() {
	SchemeBuilder.Register(&UserWorkloadsSecret{}, &UserWorkloadsSecretList{})
}
