// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type UserWorkloadsConfigMapInitParameters struct {

	// The "data" field of Kubernetes ConfigMap, organized in key-value pairs.
	// For details see: https://kubernetes.io/docs/concepts/configuration/configmap/
	// +mapType=granular
	Data map[string]*string `json:"data,omitempty" tf:"data,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/namespaced/cloudplatform/v1beta1.Project
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in cloudplatform to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v1.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in cloudplatform to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v1.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`
}

type UserWorkloadsConfigMapObservation struct {

	// The "data" field of Kubernetes ConfigMap, organized in key-value pairs.
	// For details see: https://kubernetes.io/docs/concepts/configuration/configmap/
	// +mapType=granular
	Data map[string]*string `json:"data,omitempty" tf:"data,omitempty"`

	// Environment where the Kubernetes ConfigMap will be stored and used.
	Environment *string `json:"environment,omitempty" tf:"environment,omitempty"`

	// an identifier for the resource with format projects/{{project}}/locations/{{region}}/environments/{{environment}}/userWorkloadsConfigMaps/{{name}}
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The location or Compute Engine region for the environment.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type UserWorkloadsConfigMapParameters struct {

	// The "data" field of Kubernetes ConfigMap, organized in key-value pairs.
	// For details see: https://kubernetes.io/docs/concepts/configuration/configmap/
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Data map[string]*string `json:"data,omitempty" tf:"data,omitempty"`

	// Environment where the Kubernetes ConfigMap will be stored and used.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/namespaced/composer/v1beta1.Environment
	// +kubebuilder:validation:Required
	Environment *string `json:"environment" tf:"environment,omitempty"`

	// Reference to a Environment in composer to populate environment.
	// +kubebuilder:validation:Optional
	EnvironmentRef *v1.NamespacedReference `json:"environmentRef,omitempty" tf:"-"`

	// Selector for a Environment in composer to populate environment.
	// +kubebuilder:validation:Optional
	EnvironmentSelector *v1.NamespacedSelector `json:"environmentSelector,omitempty" tf:"-"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/namespaced/cloudplatform/v1beta1.Project
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in cloudplatform to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v1.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in cloudplatform to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v1.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`

	// The location or Compute Engine region for the environment.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

// UserWorkloadsConfigMapSpec defines the desired state of UserWorkloadsConfigMap
type UserWorkloadsConfigMapSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            UserWorkloadsConfigMapParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserWorkloadsConfigMapInitParameters `json:"initProvider,omitempty"`
}

// UserWorkloadsConfigMapStatus defines the observed state of UserWorkloadsConfigMap.
type UserWorkloadsConfigMapStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserWorkloadsConfigMapObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// UserWorkloadsConfigMap is the Schema for the UserWorkloadsConfigMaps API. User workloads ConfigMap used by Airflow tasks that run with Kubernetes Executor or KubernetesPodOperator.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gcp}
type UserWorkloadsConfigMap struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              UserWorkloadsConfigMapSpec   `json:"spec"`
	Status            UserWorkloadsConfigMapStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserWorkloadsConfigMapList contains a list of UserWorkloadsConfigMaps
type UserWorkloadsConfigMapList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UserWorkloadsConfigMap `json:"items"`
}

// Repository type metadata.
var (
	UserWorkloadsConfigMap_Kind             = "UserWorkloadsConfigMap"
	UserWorkloadsConfigMap_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UserWorkloadsConfigMap_Kind}.String()
	UserWorkloadsConfigMap_KindAPIVersion   = UserWorkloadsConfigMap_Kind + "." + CRDGroupVersion.String()
	UserWorkloadsConfigMap_GroupVersionKind = CRDGroupVersion.WithKind(UserWorkloadsConfigMap_Kind)
)

func init() {
	SchemeBuilder.Register(&UserWorkloadsConfigMap{}, &UserWorkloadsConfigMapList{})
}
