apiVersion: accessapproval.gcp.upbound.io/v1beta1
kind: OrganizationSettings
metadata:
  annotations:
    meta.upbound.io/example-id: accessapproval/v1beta1/organizationsettings
  labels:
    testing.upbound.io/example-name: organization_access_approval
  name: organization-access-approval
spec:
  forProvider:
    enrolledServices:
    - cloudProduct: appengine.googleapis.com
    - cloudProduct: dataflow.googleapis.com
      enrollmentLevel: BLOCK_ALL
    notificationEmails:
    - testuser@example.com
    - example.user@example.com
    organizationId: "123456789"
