# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: composer.gcp.upbound.io/v1beta1
kind: UserWorkloadsSecret
metadata:
  annotations:
    meta.upbound.io/example-id: composer/v1beta1/userworkloadssecret
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    dataSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    environmentSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    projectSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    region: us-central1

---

apiVersion: composer.gcp.upbound.io/v1beta2
kind: Environment
metadata:
  annotations:
    meta.upbound.io/example-id: composer/v1beta1/userworkloadssecret
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    config:
      softwareConfig:
        imageVersion: example-image-version
    projectSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    region: us-central1
