// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AssistantInitParameters struct {

	// Customer policy for the assistant.
	// Structure is documented below.
	CustomerPolicy *CustomerPolicyInitParameters `json:"customerPolicy,omitempty" tf:"customer_policy,omitempty"`

	// Description for additional information. Expected to be shown on the
	// configuration UI, not to the users of the assistant.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The assistant display name.
	// It must be a UTF-8 encoded string with a length limit of 128 characters.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Configuration for the generation of the assistant response.
	// Structure is documented below.
	GenerationConfig *GenerationConfigInitParameters `json:"generationConfig,omitempty" tf:"generation_config,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The type of web grounding to use.
	// The supported values: 'WEB_GROUNDING_TYPE_DISABLED', 'WEB_GROUNDING_TYPE_GOOGLE_SEARCH', 'WEB_GROUNDING_TYPE_ENTERPRISE_WEB_SEARCH'.
	WebGroundingType *string `json:"webGroundingType,omitempty" tf:"web_grounding_type,omitempty"`
}

type AssistantObservation struct {

	// The unique id of the collection.
	CollectionID *string `json:"collectionId,omitempty" tf:"collection_id,omitempty"`

	// Customer policy for the assistant.
	// Structure is documented below.
	CustomerPolicy *CustomerPolicyObservation `json:"customerPolicy,omitempty" tf:"customer_policy,omitempty"`

	// Description for additional information. Expected to be shown on the
	// configuration UI, not to the users of the assistant.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The assistant display name.
	// It must be a UTF-8 encoded string with a length limit of 128 characters.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The unique id of the engine.
	EngineID *string `json:"engineId,omitempty" tf:"engine_id,omitempty"`

	// Configuration for the generation of the assistant response.
	// Structure is documented below.
	GenerationConfig *GenerationConfigObservation `json:"generationConfig,omitempty" tf:"generation_config,omitempty"`

	// an identifier for the resource with format projects/{{project}}/locations/{{location}}/collections/{{collection_id}}/engines/{{engine_id}}/assistants/{{assistant_id}}
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The geographic location where the data store should reside. The value can
	// only be one of "global", "us" and "eu".
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// Resource name of the assistant.
	// Format:
	// projects/{project}/locations/{location}/collections/{collection}/engines/{engine}/assistants/{assistant}
	// It must be a UTF-8 encoded string with a length limit of 1024 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The type of web grounding to use.
	// The supported values: 'WEB_GROUNDING_TYPE_DISABLED', 'WEB_GROUNDING_TYPE_GOOGLE_SEARCH', 'WEB_GROUNDING_TYPE_ENTERPRISE_WEB_SEARCH'.
	WebGroundingType *string `json:"webGroundingType,omitempty" tf:"web_grounding_type,omitempty"`
}

type AssistantParameters struct {

	// The unique id of the collection.
	// +kubebuilder:validation:Required
	CollectionID *string `json:"collectionId" tf:"collection_id,omitempty"`

	// Customer policy for the assistant.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	CustomerPolicy *CustomerPolicyParameters `json:"customerPolicy,omitempty" tf:"customer_policy,omitempty"`

	// Description for additional information. Expected to be shown on the
	// configuration UI, not to the users of the assistant.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The assistant display name.
	// It must be a UTF-8 encoded string with a length limit of 128 characters.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The unique id of the engine.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/namespaced/discoveryengine/v1beta1.SearchEngine
	// +kubebuilder:validation:Optional
	EngineID *string `json:"engineId,omitempty" tf:"engine_id,omitempty"`

	// Reference to a SearchEngine in discoveryengine to populate engineId.
	// +kubebuilder:validation:Optional
	EngineIDRef *v1.NamespacedReference `json:"engineIdRef,omitempty" tf:"-"`

	// Selector for a SearchEngine in discoveryengine to populate engineId.
	// +kubebuilder:validation:Optional
	EngineIDSelector *v1.NamespacedSelector `json:"engineIdSelector,omitempty" tf:"-"`

	// Configuration for the generation of the assistant response.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	GenerationConfig *GenerationConfigParameters `json:"generationConfig,omitempty" tf:"generation_config,omitempty"`

	// The geographic location where the data store should reside. The value can
	// only be one of "global", "us" and "eu".
	// +kubebuilder:validation:Required
	Location *string `json:"location" tf:"location,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The type of web grounding to use.
	// The supported values: 'WEB_GROUNDING_TYPE_DISABLED', 'WEB_GROUNDING_TYPE_GOOGLE_SEARCH', 'WEB_GROUNDING_TYPE_ENTERPRISE_WEB_SEARCH'.
	// +kubebuilder:validation:Optional
	WebGroundingType *string `json:"webGroundingType,omitempty" tf:"web_grounding_type,omitempty"`
}

type BannedPhrasesInitParameters struct {

	// If true, diacritical marks (e.g., accents, umlauts) are ignored when
	// matching banned phrases. For example, "cafe" would match "café".
	IgnoreDiacritics *bool `json:"ignoreDiacritics,omitempty" tf:"ignore_diacritics,omitempty"`

	// Match type for the banned phrase.
	// The supported values: 'SIMPLE_STRING_MATCH', 'WORD_BOUNDARY_STRING_MATCH'.
	MatchType *string `json:"matchType,omitempty" tf:"match_type,omitempty"`

	// The raw string content to be banned.
	Phrase *string `json:"phrase,omitempty" tf:"phrase,omitempty"`
}

type BannedPhrasesObservation struct {

	// If true, diacritical marks (e.g., accents, umlauts) are ignored when
	// matching banned phrases. For example, "cafe" would match "café".
	IgnoreDiacritics *bool `json:"ignoreDiacritics,omitempty" tf:"ignore_diacritics,omitempty"`

	// Match type for the banned phrase.
	// The supported values: 'SIMPLE_STRING_MATCH', 'WORD_BOUNDARY_STRING_MATCH'.
	MatchType *string `json:"matchType,omitempty" tf:"match_type,omitempty"`

	// The raw string content to be banned.
	Phrase *string `json:"phrase,omitempty" tf:"phrase,omitempty"`
}

type BannedPhrasesParameters struct {

	// If true, diacritical marks (e.g., accents, umlauts) are ignored when
	// matching banned phrases. For example, "cafe" would match "café".
	// +kubebuilder:validation:Optional
	IgnoreDiacritics *bool `json:"ignoreDiacritics,omitempty" tf:"ignore_diacritics,omitempty"`

	// Match type for the banned phrase.
	// The supported values: 'SIMPLE_STRING_MATCH', 'WORD_BOUNDARY_STRING_MATCH'.
	// +kubebuilder:validation:Optional
	MatchType *string `json:"matchType,omitempty" tf:"match_type,omitempty"`

	// The raw string content to be banned.
	// +kubebuilder:validation:Optional
	Phrase *string `json:"phrase" tf:"phrase,omitempty"`
}

type CustomerPolicyInitParameters struct {

	// List of banned phrases.
	// Structure is documented below.
	BannedPhrases []BannedPhrasesInitParameters `json:"bannedPhrases,omitempty" tf:"banned_phrases,omitempty"`

	// Model Armor configuration to be used for sanitizing user prompts and assistant responses.
	// Structure is documented below.
	ModelArmorConfig *ModelArmorConfigInitParameters `json:"modelArmorConfig,omitempty" tf:"model_armor_config,omitempty"`
}

type CustomerPolicyObservation struct {

	// List of banned phrases.
	// Structure is documented below.
	BannedPhrases []BannedPhrasesObservation `json:"bannedPhrases,omitempty" tf:"banned_phrases,omitempty"`

	// Model Armor configuration to be used for sanitizing user prompts and assistant responses.
	// Structure is documented below.
	ModelArmorConfig *ModelArmorConfigObservation `json:"modelArmorConfig,omitempty" tf:"model_armor_config,omitempty"`
}

type CustomerPolicyParameters struct {

	// List of banned phrases.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	BannedPhrases []BannedPhrasesParameters `json:"bannedPhrases,omitempty" tf:"banned_phrases,omitempty"`

	// Model Armor configuration to be used for sanitizing user prompts and assistant responses.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	ModelArmorConfig *ModelArmorConfigParameters `json:"modelArmorConfig,omitempty" tf:"model_armor_config,omitempty"`
}

type GenerationConfigInitParameters struct {

	// The default language to use for the generation of the assistant response.
	// Use an ISO 639-1 language code such as en.
	// If not specified, the language will be automatically detected.
	DefaultLanguage *string `json:"defaultLanguage,omitempty" tf:"default_language,omitempty"`

	// System instruction, also known as the prompt preamble for LLM calls.
	// See also https://cloud.google.com/vertex-ai/generative-ai/docs/learn/prompts/system-instructions
	// Structure is documented below.
	SystemInstruction *SystemInstructionInitParameters `json:"systemInstruction,omitempty" tf:"system_instruction,omitempty"`
}

type GenerationConfigObservation struct {

	// The default language to use for the generation of the assistant response.
	// Use an ISO 639-1 language code such as en.
	// If not specified, the language will be automatically detected.
	DefaultLanguage *string `json:"defaultLanguage,omitempty" tf:"default_language,omitempty"`

	// System instruction, also known as the prompt preamble for LLM calls.
	// See also https://cloud.google.com/vertex-ai/generative-ai/docs/learn/prompts/system-instructions
	// Structure is documented below.
	SystemInstruction *SystemInstructionObservation `json:"systemInstruction,omitempty" tf:"system_instruction,omitempty"`
}

type GenerationConfigParameters struct {

	// The default language to use for the generation of the assistant response.
	// Use an ISO 639-1 language code such as en.
	// If not specified, the language will be automatically detected.
	// +kubebuilder:validation:Optional
	DefaultLanguage *string `json:"defaultLanguage,omitempty" tf:"default_language,omitempty"`

	// System instruction, also known as the prompt preamble for LLM calls.
	// See also https://cloud.google.com/vertex-ai/generative-ai/docs/learn/prompts/system-instructions
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	SystemInstruction *SystemInstructionParameters `json:"systemInstruction,omitempty" tf:"system_instruction,omitempty"`
}

type ModelArmorConfigInitParameters struct {

	// Defines the failure mode for Model Armor sanitization.
	// The supported values: 'FAIL_OPEN', 'FAIL_CLOSED'.
	FailureMode *string `json:"failureMode,omitempty" tf:"failure_mode,omitempty"`

	// The resource name of the Model Armor template for sanitizing assistant
	// responses. Format:
	// projects/{project}/locations/{location}/templates/{template_id}
	// If not specified, no sanitization will be applied to the assistant
	// response.
	ResponseTemplate *string `json:"responseTemplate,omitempty" tf:"response_template,omitempty"`

	// The resource name of the Model Armor template for sanitizing user
	// prompts. Format:
	// projects/{project}/locations/{location}/templates/{template_id}
	// If not specified, no sanitization will be applied to the user prompt.
	UserPromptTemplate *string `json:"userPromptTemplate,omitempty" tf:"user_prompt_template,omitempty"`
}

type ModelArmorConfigObservation struct {

	// Defines the failure mode for Model Armor sanitization.
	// The supported values: 'FAIL_OPEN', 'FAIL_CLOSED'.
	FailureMode *string `json:"failureMode,omitempty" tf:"failure_mode,omitempty"`

	// The resource name of the Model Armor template for sanitizing assistant
	// responses. Format:
	// projects/{project}/locations/{location}/templates/{template_id}
	// If not specified, no sanitization will be applied to the assistant
	// response.
	ResponseTemplate *string `json:"responseTemplate,omitempty" tf:"response_template,omitempty"`

	// The resource name of the Model Armor template for sanitizing user
	// prompts. Format:
	// projects/{project}/locations/{location}/templates/{template_id}
	// If not specified, no sanitization will be applied to the user prompt.
	UserPromptTemplate *string `json:"userPromptTemplate,omitempty" tf:"user_prompt_template,omitempty"`
}

type ModelArmorConfigParameters struct {

	// Defines the failure mode for Model Armor sanitization.
	// The supported values: 'FAIL_OPEN', 'FAIL_CLOSED'.
	// +kubebuilder:validation:Optional
	FailureMode *string `json:"failureMode,omitempty" tf:"failure_mode,omitempty"`

	// The resource name of the Model Armor template for sanitizing assistant
	// responses. Format:
	// projects/{project}/locations/{location}/templates/{template_id}
	// If not specified, no sanitization will be applied to the assistant
	// response.
	// +kubebuilder:validation:Optional
	ResponseTemplate *string `json:"responseTemplate" tf:"response_template,omitempty"`

	// The resource name of the Model Armor template for sanitizing user
	// prompts. Format:
	// projects/{project}/locations/{location}/templates/{template_id}
	// If not specified, no sanitization will be applied to the user prompt.
	// +kubebuilder:validation:Optional
	UserPromptTemplate *string `json:"userPromptTemplate" tf:"user_prompt_template,omitempty"`
}

type SystemInstructionInitParameters struct {

	// Additional system instruction that will be added to the default system instruction.
	AdditionalSystemInstruction *string `json:"additionalSystemInstruction,omitempty" tf:"additional_system_instruction,omitempty"`
}

type SystemInstructionObservation struct {

	// Additional system instruction that will be added to the default system instruction.
	AdditionalSystemInstruction *string `json:"additionalSystemInstruction,omitempty" tf:"additional_system_instruction,omitempty"`
}

type SystemInstructionParameters struct {

	// Additional system instruction that will be added to the default system instruction.
	// +kubebuilder:validation:Optional
	AdditionalSystemInstruction *string `json:"additionalSystemInstruction,omitempty" tf:"additional_system_instruction,omitempty"`
}

// AssistantSpec defines the desired state of Assistant
type AssistantSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AssistantParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AssistantInitParameters `json:"initProvider,omitempty"`
}

// AssistantStatus defines the observed state of Assistant.
type AssistantStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AssistantObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Assistant is the Schema for the Assistants API. Assistant
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gcp}
type Assistant struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	Spec   AssistantSpec   `json:"spec"`
	Status AssistantStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AssistantList contains a list of Assistants
type AssistantList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Assistant `json:"items"`
}

// Repository type metadata.
var (
	Assistant_Kind             = "Assistant"
	Assistant_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Assistant_Kind}.String()
	Assistant_KindAPIVersion   = Assistant_Kind + "." + CRDGroupVersion.String()
	Assistant_GroupVersionKind = CRDGroupVersion.WithKind(Assistant_Kind)
)

func init() {
	SchemeBuilder.Register(&Assistant{}, &AssistantList{})
}
