// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ActiveTimeRangeInitParameters struct {

	// The end time of the active time range.
	EndTime *string `json:"endTime,omitempty" tf:"end_time,omitempty"`

	// The start time of the active time range.
	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`
}

type ActiveTimeRangeObservation struct {

	// The end time of the active time range.
	EndTime *string `json:"endTime,omitempty" tf:"end_time,omitempty"`

	// The start time of the active time range.
	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`
}

type ActiveTimeRangeParameters struct {

	// The end time of the active time range.
	// +kubebuilder:validation:Optional
	EndTime *string `json:"endTime,omitempty" tf:"end_time,omitempty"`

	// The start time of the active time range.
	// +kubebuilder:validation:Optional
	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`
}

type BoostActionInitParameters struct {

	// The data store to boost.
	DataStore *string `json:"dataStore,omitempty" tf:"data_store,omitempty"`

	// The filter to apply to the search results.
	Filter *string `json:"filter,omitempty" tf:"filter,omitempty"`

	// The fixed boost value to apply to the search results. Positive values will increase the relevance of the results, while negative values will decrease the relevance. The value must be between -100 and 100.
	FixedBoost *float64 `json:"fixedBoost,omitempty" tf:"fixed_boost,omitempty"`

	// The interpolation boost specification to apply to the search results.
	// Structure is documented below.
	InterpolationBoostSpec *InterpolationBoostSpecInitParameters `json:"interpolationBoostSpec,omitempty" tf:"interpolation_boost_spec,omitempty"`
}

type BoostActionObservation struct {

	// The data store to boost.
	DataStore *string `json:"dataStore,omitempty" tf:"data_store,omitempty"`

	// The filter to apply to the search results.
	Filter *string `json:"filter,omitempty" tf:"filter,omitempty"`

	// The fixed boost value to apply to the search results. Positive values will increase the relevance of the results, while negative values will decrease the relevance. The value must be between -100 and 100.
	FixedBoost *float64 `json:"fixedBoost,omitempty" tf:"fixed_boost,omitempty"`

	// The interpolation boost specification to apply to the search results.
	// Structure is documented below.
	InterpolationBoostSpec *InterpolationBoostSpecObservation `json:"interpolationBoostSpec,omitempty" tf:"interpolation_boost_spec,omitempty"`
}

type BoostActionParameters struct {

	// The data store to boost.
	// +kubebuilder:validation:Optional
	DataStore *string `json:"dataStore" tf:"data_store,omitempty"`

	// The filter to apply to the search results.
	// +kubebuilder:validation:Optional
	Filter *string `json:"filter" tf:"filter,omitempty"`

	// The fixed boost value to apply to the search results. Positive values will increase the relevance of the results, while negative values will decrease the relevance. The value must be between -100 and 100.
	// +kubebuilder:validation:Optional
	FixedBoost *float64 `json:"fixedBoost,omitempty" tf:"fixed_boost,omitempty"`

	// The interpolation boost specification to apply to the search results.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	InterpolationBoostSpec *InterpolationBoostSpecParameters `json:"interpolationBoostSpec,omitempty" tf:"interpolation_boost_spec,omitempty"`
}

type ConditionsInitParameters struct {

	// The time range when the condition is active.
	// Structure is documented below.
	ActiveTimeRange []ActiveTimeRangeInitParameters `json:"activeTimeRange,omitempty" tf:"active_time_range,omitempty"`

	// The regular expression that the query must match for this condition to be met.
	QueryRegex *string `json:"queryRegex,omitempty" tf:"query_regex,omitempty"`

	// The query terms that must be present in the search request for this condition to be met.
	// Structure is documented below.
	QueryTerms []QueryTermsInitParameters `json:"queryTerms,omitempty" tf:"query_terms,omitempty"`
}

type ConditionsObservation struct {

	// The time range when the condition is active.
	// Structure is documented below.
	ActiveTimeRange []ActiveTimeRangeObservation `json:"activeTimeRange,omitempty" tf:"active_time_range,omitempty"`

	// The regular expression that the query must match for this condition to be met.
	QueryRegex *string `json:"queryRegex,omitempty" tf:"query_regex,omitempty"`

	// The query terms that must be present in the search request for this condition to be met.
	// Structure is documented below.
	QueryTerms []QueryTermsObservation `json:"queryTerms,omitempty" tf:"query_terms,omitempty"`
}

type ConditionsParameters struct {

	// The time range when the condition is active.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	ActiveTimeRange []ActiveTimeRangeParameters `json:"activeTimeRange,omitempty" tf:"active_time_range,omitempty"`

	// The regular expression that the query must match for this condition to be met.
	// +kubebuilder:validation:Optional
	QueryRegex *string `json:"queryRegex,omitempty" tf:"query_regex,omitempty"`

	// The query terms that must be present in the search request for this condition to be met.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	QueryTerms []QueryTermsParameters `json:"queryTerms,omitempty" tf:"query_terms,omitempty"`
}

type ControlInitParameters struct {

	// Changes the returned order of results.
	// Structure is documented below.
	BoostAction *BoostActionInitParameters `json:"boostAction,omitempty" tf:"boost_action,omitempty"`

	// The conditions under which the control is active.
	// Structure is documented below.
	Conditions []ConditionsInitParameters `json:"conditions,omitempty" tf:"conditions,omitempty"`

	// The display name of the control. This field must be a UTF-8 encoded
	// string with a length limit of 128 characters.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Removes entries from returned results.
	// Structure is documented below.
	FilterAction *FilterActionInitParameters `json:"filterAction,omitempty" tf:"filter_action,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Promotes a specified link for a query.
	// Structure is documented below.
	PromoteAction *PromoteActionInitParameters `json:"promoteAction,omitempty" tf:"promote_action,omitempty"`

	// Redirects to a specified URI.
	// Structure is documented below.
	RedirectAction *RedirectActionInitParameters `json:"redirectAction,omitempty" tf:"redirect_action,omitempty"`

	// The solution type that the control belongs to.
	// Possible values are: SOLUTION_TYPE_RECOMMENDATION, SOLUTION_TYPE_SEARCH, SOLUTION_TYPE_CHAT, SOLUTION_TYPE_GENERATIVE_CHAT.
	SolutionType *string `json:"solutionType,omitempty" tf:"solution_type,omitempty"`

	// Associates queries with each other.
	// Structure is documented below.
	SynonymsAction *SynonymsActionInitParameters `json:"synonymsAction,omitempty" tf:"synonyms_action,omitempty"`

	// The use cases that the control is used for.
	// Each value may be one of: SEARCH_USE_CASE_SEARCH, SEARCH_USE_CASE_BROWSE.
	UseCases []*string `json:"useCases,omitempty" tf:"use_cases,omitempty"`
}

type ControlObservation struct {

	// Changes the returned order of results.
	// Structure is documented below.
	BoostAction *BoostActionObservation `json:"boostAction,omitempty" tf:"boost_action,omitempty"`

	// The collection ID. Currently only accepts "default_collection".
	CollectionID *string `json:"collectionId,omitempty" tf:"collection_id,omitempty"`

	// The conditions under which the control is active.
	// Structure is documented below.
	Conditions []ConditionsObservation `json:"conditions,omitempty" tf:"conditions,omitempty"`

	// The display name of the control. This field must be a UTF-8 encoded
	// string with a length limit of 128 characters.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The engine to add the control to.
	EngineID *string `json:"engineId,omitempty" tf:"engine_id,omitempty"`

	// Removes entries from returned results.
	// Structure is documented below.
	FilterAction *FilterActionObservation `json:"filterAction,omitempty" tf:"filter_action,omitempty"`

	// an identifier for the resource with format projects/{{project}}/locations/{{location}}/collections/{{collection_id}}/engines/{{engine_id}}/controls/{{control_id}}
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The geographic location where the data store should reside. The value can
	// only be one of "global", "us" and "eu".
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// The unique full resource name of the control. Values are of the format
	// projects/{project}/locations/{location}/collections/{collection_id}/engines/{engine_id}/controls/{control_id}.
	// This field must be a UTF-8 encoded string with a length limit of 1024
	// characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Promotes a specified link for a query.
	// Structure is documented below.
	PromoteAction *PromoteActionObservation `json:"promoteAction,omitempty" tf:"promote_action,omitempty"`

	// Redirects to a specified URI.
	// Structure is documented below.
	RedirectAction *RedirectActionObservation `json:"redirectAction,omitempty" tf:"redirect_action,omitempty"`

	// The solution type that the control belongs to.
	// Possible values are: SOLUTION_TYPE_RECOMMENDATION, SOLUTION_TYPE_SEARCH, SOLUTION_TYPE_CHAT, SOLUTION_TYPE_GENERATIVE_CHAT.
	SolutionType *string `json:"solutionType,omitempty" tf:"solution_type,omitempty"`

	// Associates queries with each other.
	// Structure is documented below.
	SynonymsAction *SynonymsActionObservation `json:"synonymsAction,omitempty" tf:"synonyms_action,omitempty"`

	// The use cases that the control is used for.
	// Each value may be one of: SEARCH_USE_CASE_SEARCH, SEARCH_USE_CASE_BROWSE.
	UseCases []*string `json:"useCases,omitempty" tf:"use_cases,omitempty"`
}

type ControlParameters struct {

	// Changes the returned order of results.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	BoostAction *BoostActionParameters `json:"boostAction,omitempty" tf:"boost_action,omitempty"`

	// The collection ID. Currently only accepts "default_collection".
	// +kubebuilder:validation:Optional
	CollectionID *string `json:"collectionId,omitempty" tf:"collection_id,omitempty"`

	// The conditions under which the control is active.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	Conditions []ConditionsParameters `json:"conditions,omitempty" tf:"conditions,omitempty"`

	// The display name of the control. This field must be a UTF-8 encoded
	// string with a length limit of 128 characters.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The engine to add the control to.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/namespaced/discoveryengine/v1beta1.SearchEngine
	// +kubebuilder:validation:Optional
	EngineID *string `json:"engineId,omitempty" tf:"engine_id,omitempty"`

	// Reference to a SearchEngine in discoveryengine to populate engineId.
	// +kubebuilder:validation:Optional
	EngineIDRef *v1.NamespacedReference `json:"engineIdRef,omitempty" tf:"-"`

	// Selector for a SearchEngine in discoveryengine to populate engineId.
	// +kubebuilder:validation:Optional
	EngineIDSelector *v1.NamespacedSelector `json:"engineIdSelector,omitempty" tf:"-"`

	// Removes entries from returned results.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	FilterAction *FilterActionParameters `json:"filterAction,omitempty" tf:"filter_action,omitempty"`

	// The geographic location where the data store should reside. The value can
	// only be one of "global", "us" and "eu".
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/namespaced/discoveryengine/v1beta1.SearchEngine
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("location",false)
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// Reference to a SearchEngine in discoveryengine to populate location.
	// +kubebuilder:validation:Optional
	LocationRef *v1.NamespacedReference `json:"locationRef,omitempty" tf:"-"`

	// Selector for a SearchEngine in discoveryengine to populate location.
	// +kubebuilder:validation:Optional
	LocationSelector *v1.NamespacedSelector `json:"locationSelector,omitempty" tf:"-"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Promotes a specified link for a query.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	PromoteAction *PromoteActionParameters `json:"promoteAction,omitempty" tf:"promote_action,omitempty"`

	// Redirects to a specified URI.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	RedirectAction *RedirectActionParameters `json:"redirectAction,omitempty" tf:"redirect_action,omitempty"`

	// The solution type that the control belongs to.
	// Possible values are: SOLUTION_TYPE_RECOMMENDATION, SOLUTION_TYPE_SEARCH, SOLUTION_TYPE_CHAT, SOLUTION_TYPE_GENERATIVE_CHAT.
	// +kubebuilder:validation:Optional
	SolutionType *string `json:"solutionType,omitempty" tf:"solution_type,omitempty"`

	// Associates queries with each other.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	SynonymsAction *SynonymsActionParameters `json:"synonymsAction,omitempty" tf:"synonyms_action,omitempty"`

	// The use cases that the control is used for.
	// Each value may be one of: SEARCH_USE_CASE_SEARCH, SEARCH_USE_CASE_BROWSE.
	// +kubebuilder:validation:Optional
	UseCases []*string `json:"useCases,omitempty" tf:"use_cases,omitempty"`
}

type ControlPointInitParameters struct {

	// The attribute value of the control point.
	AttributeValue *string `json:"attributeValue,omitempty" tf:"attribute_value,omitempty"`

	// The value between -1 to 1 by which to boost the score if the attributeValue
	// evaluates to the value specified above.
	BoostAmount *float64 `json:"boostAmount,omitempty" tf:"boost_amount,omitempty"`
}

type ControlPointObservation struct {

	// The attribute value of the control point.
	AttributeValue *string `json:"attributeValue,omitempty" tf:"attribute_value,omitempty"`

	// The value between -1 to 1 by which to boost the score if the attributeValue
	// evaluates to the value specified above.
	BoostAmount *float64 `json:"boostAmount,omitempty" tf:"boost_amount,omitempty"`
}

type ControlPointParameters struct {

	// The attribute value of the control point.
	// +kubebuilder:validation:Optional
	AttributeValue *string `json:"attributeValue,omitempty" tf:"attribute_value,omitempty"`

	// The value between -1 to 1 by which to boost the score if the attributeValue
	// evaluates to the value specified above.
	// +kubebuilder:validation:Optional
	BoostAmount *float64 `json:"boostAmount,omitempty" tf:"boost_amount,omitempty"`
}

type FilterActionInitParameters struct {

	// The data store to filter.
	DataStore *string `json:"dataStore,omitempty" tf:"data_store,omitempty"`

	// The filter to apply to the search results.
	Filter *string `json:"filter,omitempty" tf:"filter,omitempty"`
}

type FilterActionObservation struct {

	// The data store to filter.
	DataStore *string `json:"dataStore,omitempty" tf:"data_store,omitempty"`

	// The filter to apply to the search results.
	Filter *string `json:"filter,omitempty" tf:"filter,omitempty"`
}

type FilterActionParameters struct {

	// The data store to filter.
	// +kubebuilder:validation:Optional
	DataStore *string `json:"dataStore" tf:"data_store,omitempty"`

	// The filter to apply to the search results.
	// +kubebuilder:validation:Optional
	Filter *string `json:"filter" tf:"filter,omitempty"`
}

type InterpolationBoostSpecInitParameters struct {

	// The attribute type to be used to determine the boost amount.
	// Possible values are: NUMERICAL, FRESHNESS.
	AttributeType *string `json:"attributeType,omitempty" tf:"attribute_type,omitempty"`

	// The control points used to define the curve.
	// Structure is documented below.
	ControlPoint *ControlPointInitParameters `json:"controlPoint,omitempty" tf:"control_point,omitempty"`

	// The name of the field whose value will be used to determine the boost amount.
	FieldName *string `json:"fieldName,omitempty" tf:"field_name,omitempty"`

	// The interpolation type to be applied to connect the control points.
	// Possible values are: LINEAR.
	InterpolationType *string `json:"interpolationType,omitempty" tf:"interpolation_type,omitempty"`
}

type InterpolationBoostSpecObservation struct {

	// The attribute type to be used to determine the boost amount.
	// Possible values are: NUMERICAL, FRESHNESS.
	AttributeType *string `json:"attributeType,omitempty" tf:"attribute_type,omitempty"`

	// The control points used to define the curve.
	// Structure is documented below.
	ControlPoint *ControlPointObservation `json:"controlPoint,omitempty" tf:"control_point,omitempty"`

	// The name of the field whose value will be used to determine the boost amount.
	FieldName *string `json:"fieldName,omitempty" tf:"field_name,omitempty"`

	// The interpolation type to be applied to connect the control points.
	// Possible values are: LINEAR.
	InterpolationType *string `json:"interpolationType,omitempty" tf:"interpolation_type,omitempty"`
}

type InterpolationBoostSpecParameters struct {

	// The attribute type to be used to determine the boost amount.
	// Possible values are: NUMERICAL, FRESHNESS.
	// +kubebuilder:validation:Optional
	AttributeType *string `json:"attributeType,omitempty" tf:"attribute_type,omitempty"`

	// The control points used to define the curve.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	ControlPoint *ControlPointParameters `json:"controlPoint,omitempty" tf:"control_point,omitempty"`

	// The name of the field whose value will be used to determine the boost amount.
	// +kubebuilder:validation:Optional
	FieldName *string `json:"fieldName,omitempty" tf:"field_name,omitempty"`

	// The interpolation type to be applied to connect the control points.
	// Possible values are: LINEAR.
	// +kubebuilder:validation:Optional
	InterpolationType *string `json:"interpolationType,omitempty" tf:"interpolation_type,omitempty"`
}

type PromoteActionInitParameters struct {

	// The data store to promote.
	DataStore *string `json:"dataStore,omitempty" tf:"data_store,omitempty"`

	// The search link promotion to apply to the search results.
	// Structure is documented below.
	SearchLinkPromotion *SearchLinkPromotionInitParameters `json:"searchLinkPromotion,omitempty" tf:"search_link_promotion,omitempty"`
}

type PromoteActionObservation struct {

	// The data store to promote.
	DataStore *string `json:"dataStore,omitempty" tf:"data_store,omitempty"`

	// The search link promotion to apply to the search results.
	// Structure is documented below.
	SearchLinkPromotion *SearchLinkPromotionObservation `json:"searchLinkPromotion,omitempty" tf:"search_link_promotion,omitempty"`
}

type PromoteActionParameters struct {

	// The data store to promote.
	// +kubebuilder:validation:Optional
	DataStore *string `json:"dataStore" tf:"data_store,omitempty"`

	// The search link promotion to apply to the search results.
	// Structure is documented below.
	// +kubebuilder:validation:Optional
	SearchLinkPromotion *SearchLinkPromotionParameters `json:"searchLinkPromotion" tf:"search_link_promotion,omitempty"`
}

type QueryTermsInitParameters struct {

	// If true, the query term must be an exact match. Otherwise, the query term can be a partial match.
	FullMatch *bool `json:"fullMatch,omitempty" tf:"full_match,omitempty"`

	// The value of the query term.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type QueryTermsObservation struct {

	// If true, the query term must be an exact match. Otherwise, the query term can be a partial match.
	FullMatch *bool `json:"fullMatch,omitempty" tf:"full_match,omitempty"`

	// The value of the query term.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type QueryTermsParameters struct {

	// If true, the query term must be an exact match. Otherwise, the query term can be a partial match.
	// +kubebuilder:validation:Optional
	FullMatch *bool `json:"fullMatch,omitempty" tf:"full_match,omitempty"`

	// The value of the query term.
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type RedirectActionInitParameters struct {

	// The URI to redirect to.
	RedirectURI *string `json:"redirectUri,omitempty" tf:"redirect_uri,omitempty"`
}

type RedirectActionObservation struct {

	// The URI to redirect to.
	RedirectURI *string `json:"redirectUri,omitempty" tf:"redirect_uri,omitempty"`
}

type RedirectActionParameters struct {

	// The URI to redirect to.
	// +kubebuilder:validation:Optional
	RedirectURI *string `json:"redirectUri" tf:"redirect_uri,omitempty"`
}

type SearchLinkPromotionInitParameters struct {

	// The description of the promoted link.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The document to promote.
	Document *string `json:"document,omitempty" tf:"document,omitempty"`

	// Return promotions for basic site search.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The image URI of the promoted link.
	ImageURI *string `json:"imageUri,omitempty" tf:"image_uri,omitempty"`

	// The title of the promoted link.
	Title *string `json:"title,omitempty" tf:"title,omitempty"`

	// The URI to promote.
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`
}

type SearchLinkPromotionObservation struct {

	// The description of the promoted link.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The document to promote.
	Document *string `json:"document,omitempty" tf:"document,omitempty"`

	// Return promotions for basic site search.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The image URI of the promoted link.
	ImageURI *string `json:"imageUri,omitempty" tf:"image_uri,omitempty"`

	// The title of the promoted link.
	Title *string `json:"title,omitempty" tf:"title,omitempty"`

	// The URI to promote.
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`
}

type SearchLinkPromotionParameters struct {

	// The description of the promoted link.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The document to promote.
	// +kubebuilder:validation:Optional
	Document *string `json:"document,omitempty" tf:"document,omitempty"`

	// Return promotions for basic site search.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The image URI of the promoted link.
	// +kubebuilder:validation:Optional
	ImageURI *string `json:"imageUri,omitempty" tf:"image_uri,omitempty"`

	// The title of the promoted link.
	// +kubebuilder:validation:Optional
	Title *string `json:"title" tf:"title,omitempty"`

	// The URI to promote.
	// +kubebuilder:validation:Optional
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`
}

type SynonymsActionInitParameters struct {

	// The synonyms to apply to the search results.
	Synonyms []*string `json:"synonyms,omitempty" tf:"synonyms,omitempty"`
}

type SynonymsActionObservation struct {

	// The synonyms to apply to the search results.
	Synonyms []*string `json:"synonyms,omitempty" tf:"synonyms,omitempty"`
}

type SynonymsActionParameters struct {

	// The synonyms to apply to the search results.
	// +kubebuilder:validation:Optional
	Synonyms []*string `json:"synonyms,omitempty" tf:"synonyms,omitempty"`
}

// ControlSpec defines the desired state of Control
type ControlSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ControlParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ControlInitParameters `json:"initProvider,omitempty"`
}

// ControlStatus defines the observed state of Control.
type ControlStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ControlObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Control is the Schema for the Controls API. Controls are rules that influence search results.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gcp}
type Control struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.solutionType) || (has(self.initProvider) && has(self.initProvider.solutionType))",message="spec.forProvider.solutionType is a required parameter"
	Spec   ControlSpec   `json:"spec"`
	Status ControlStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ControlList contains a list of Controls
type ControlList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Control `json:"items"`
}

// Repository type metadata.
var (
	Control_Kind             = "Control"
	Control_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Control_Kind}.String()
	Control_KindAPIVersion   = Control_Kind + "." + CRDGroupVersion.String()
	Control_GroupVersionKind = CRDGroupVersion.WithKind(Control_Kind)
)

func init() {
	SchemeBuilder.Register(&Control{}, &ControlList{})
}
