// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type SchemaInitParameters struct {

	// The JSON representation of the schema.
	JSONSchema *string `json:"jsonSchema,omitempty" tf:"json_schema,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`
}

type SchemaObservation struct {

	// The unique id of the data store.
	DataStoreID *string `json:"dataStoreId,omitempty" tf:"data_store_id,omitempty"`

	// an identifier for the resource with format projects/{{project}}/locations/{{location}}/collections/default_collection/dataStores/{{data_store_id}}/schemas/{{schema_id}}
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The JSON representation of the schema.
	JSONSchema *string `json:"jsonSchema,omitempty" tf:"json_schema,omitempty"`

	// The geographic location where the data store should reside. The value can
	// only be one of "global", "us" and "eu".
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// The unique full resource name of the schema. Values are of the format
	// projects/{project}/locations/{location}/collections/{collection_id}/dataStores/{data_store_id}/schemas/{schema_id}.
	// This field must be a UTF-8 encoded string with a length limit of 1024
	// characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`
}

type SchemaParameters struct {

	// The unique id of the data store.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/namespaced/discoveryengine/v1beta1.DataStore
	// +kubebuilder:validation:Optional
	DataStoreID *string `json:"dataStoreId,omitempty" tf:"data_store_id,omitempty"`

	// Reference to a DataStore in discoveryengine to populate dataStoreId.
	// +kubebuilder:validation:Optional
	DataStoreIDRef *v1.NamespacedReference `json:"dataStoreIdRef,omitempty" tf:"-"`

	// Selector for a DataStore in discoveryengine to populate dataStoreId.
	// +kubebuilder:validation:Optional
	DataStoreIDSelector *v1.NamespacedSelector `json:"dataStoreIdSelector,omitempty" tf:"-"`

	// The JSON representation of the schema.
	// +kubebuilder:validation:Optional
	JSONSchema *string `json:"jsonSchema,omitempty" tf:"json_schema,omitempty"`

	// The geographic location where the data store should reside. The value can
	// only be one of "global", "us" and "eu".
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/namespaced/discoveryengine/v1beta1.DataStore
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("location",false)
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// Reference to a DataStore in discoveryengine to populate location.
	// +kubebuilder:validation:Optional
	LocationRef *v1.NamespacedReference `json:"locationRef,omitempty" tf:"-"`

	// Selector for a DataStore in discoveryengine to populate location.
	// +kubebuilder:validation:Optional
	LocationSelector *v1.NamespacedSelector `json:"locationSelector,omitempty" tf:"-"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`
}

// SchemaSpec defines the desired state of Schema
type SchemaSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SchemaParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SchemaInitParameters `json:"initProvider,omitempty"`
}

// SchemaStatus defines the observed state of Schema.
type SchemaStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SchemaObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Schema is the Schema for the Schemas API. Schema defines the structure and layout of a type of document data.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gcp}
type Schema struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SchemaSpec   `json:"spec"`
	Status            SchemaStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SchemaList contains a list of Schemas
type SchemaList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Schema `json:"items"`
}

// Repository type metadata.
var (
	Schema_Kind             = "Schema"
	Schema_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Schema_Kind}.String()
	Schema_KindAPIVersion   = Schema_Kind + "." + CRDGroupVersion.String()
	Schema_GroupVersionKind = CRDGroupVersion.WithKind(Schema_Kind)
)

func init() {
	SchemeBuilder.Register(&Schema{}, &SchemaList{})
}
