// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ServingConfigInitParameters struct {
	BoostControlIds []*string `json:"boostControlIds,omitempty" tf:"boost_control_ids,omitempty"`

	FilterControlIds []*string `json:"filterControlIds,omitempty" tf:"filter_control_ids,omitempty"`

	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	PromoteControlIds []*string `json:"promoteControlIds,omitempty" tf:"promote_control_ids,omitempty"`

	RedirectControlIds []*string `json:"redirectControlIds,omitempty" tf:"redirect_control_ids,omitempty"`

	SynonymsControlIds []*string `json:"synonymsControlIds,omitempty" tf:"synonyms_control_ids,omitempty"`
}

type ServingConfigObservation struct {
	BoostControlIds []*string `json:"boostControlIds,omitempty" tf:"boost_control_ids,omitempty"`

	CollectionID *string `json:"collectionId,omitempty" tf:"collection_id,omitempty"`

	EngineID *string `json:"engineId,omitempty" tf:"engine_id,omitempty"`

	FilterControlIds []*string `json:"filterControlIds,omitempty" tf:"filter_control_ids,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	PromoteControlIds []*string `json:"promoteControlIds,omitempty" tf:"promote_control_ids,omitempty"`

	RedirectControlIds []*string `json:"redirectControlIds,omitempty" tf:"redirect_control_ids,omitempty"`

	SynonymsControlIds []*string `json:"synonymsControlIds,omitempty" tf:"synonyms_control_ids,omitempty"`
}

type ServingConfigParameters struct {

	// +kubebuilder:validation:Optional
	BoostControlIds []*string `json:"boostControlIds,omitempty" tf:"boost_control_ids,omitempty"`

	// +kubebuilder:validation:Optional
	CollectionID *string `json:"collectionId,omitempty" tf:"collection_id,omitempty"`

	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/namespaced/discoveryengine/v1beta1.SearchEngine
	// +kubebuilder:validation:Optional
	EngineID *string `json:"engineId,omitempty" tf:"engine_id,omitempty"`

	// Reference to a SearchEngine in discoveryengine to populate engineId.
	// +kubebuilder:validation:Optional
	EngineIDRef *v1.NamespacedReference `json:"engineIdRef,omitempty" tf:"-"`

	// Selector for a SearchEngine in discoveryengine to populate engineId.
	// +kubebuilder:validation:Optional
	EngineIDSelector *v1.NamespacedSelector `json:"engineIdSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	FilterControlIds []*string `json:"filterControlIds,omitempty" tf:"filter_control_ids,omitempty"`

	// +kubebuilder:validation:Required
	Location *string `json:"location" tf:"location,omitempty"`

	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// +kubebuilder:validation:Optional
	PromoteControlIds []*string `json:"promoteControlIds,omitempty" tf:"promote_control_ids,omitempty"`

	// +kubebuilder:validation:Optional
	RedirectControlIds []*string `json:"redirectControlIds,omitempty" tf:"redirect_control_ids,omitempty"`

	// +kubebuilder:validation:Optional
	SynonymsControlIds []*string `json:"synonymsControlIds,omitempty" tf:"synonyms_control_ids,omitempty"`
}

// ServingConfigSpec defines the desired state of ServingConfig
type ServingConfigSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ServingConfigParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServingConfigInitParameters `json:"initProvider,omitempty"`
}

// ServingConfigStatus defines the observed state of ServingConfig.
type ServingConfigStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServingConfigObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ServingConfig is the Schema for the ServingConfigs API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gcp}
type ServingConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ServingConfigSpec   `json:"spec"`
	Status            ServingConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServingConfigList contains a list of ServingConfigs
type ServingConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServingConfig `json:"items"`
}

// Repository type metadata.
var (
	ServingConfig_Kind             = "ServingConfig"
	ServingConfig_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ServingConfig_Kind}.String()
	ServingConfig_KindAPIVersion   = ServingConfig_Kind + "." + CRDGroupVersion.String()
	ServingConfig_GroupVersionKind = CRDGroupVersion.WithKind(ServingConfig_Kind)
)

func init() {
	SchemeBuilder.Register(&ServingConfig{}, &ServingConfigList{})
}
