// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type UserStoreInitParameters struct {

	// The resource name of the default license config assigned to users created in
	// this user store. Format:
	// projects/{project}/locations/{location}/licenseConfigs/{license_config}.
	// If enableLicenseAutoRegister is true, new users will automatically
	// register under the default subscription.
	// If the default license config doesn't have remaining license seats left,
	// new users will not be assigned with license.
	DefaultLicenseConfig *string `json:"defaultLicenseConfig,omitempty" tf:"default_license_config,omitempty"`

	// Whether to enable automatic license update for users with expired licenses
	// in this user store. If enabled, users with expired licenses will
	// automatically be updated to the default subscription if there are
	// remaining license seats.
	EnableExpiredLicenseAutoUpdate *bool `json:"enableExpiredLicenseAutoUpdate,omitempty" tf:"enable_expired_license_auto_update,omitempty"`

	// Whether to enable automatic license registration for new users created in
	// this user store. If enabled, new users will automatically register under
	// the default subscription.
	EnableLicenseAutoRegister *bool `json:"enableLicenseAutoRegister,omitempty" tf:"enable_license_auto_register,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`
}

type UserStoreObservation struct {

	// The resource name of the default license config assigned to users created in
	// this user store. Format:
	// projects/{project}/locations/{location}/licenseConfigs/{license_config}.
	// If enableLicenseAutoRegister is true, new users will automatically
	// register under the default subscription.
	// If the default license config doesn't have remaining license seats left,
	// new users will not be assigned with license.
	DefaultLicenseConfig *string `json:"defaultLicenseConfig,omitempty" tf:"default_license_config,omitempty"`

	// Whether to enable automatic license update for users with expired licenses
	// in this user store. If enabled, users with expired licenses will
	// automatically be updated to the default subscription if there are
	// remaining license seats.
	EnableExpiredLicenseAutoUpdate *bool `json:"enableExpiredLicenseAutoUpdate,omitempty" tf:"enable_expired_license_auto_update,omitempty"`

	// Whether to enable automatic license registration for new users created in
	// this user store. If enabled, new users will automatically register under
	// the default subscription.
	EnableLicenseAutoRegister *bool `json:"enableLicenseAutoRegister,omitempty" tf:"enable_license_auto_register,omitempty"`

	// an identifier for the resource with format projects/{{project}}/locations/{{location}}/userStores/{{user_store_id}}
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The geographic location where the data store should reside. The value can
	// only be one of "global", "us" and "eu".
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// The unique full resource name of the user store. Values are of the format
	// projects/{project}/locations/{location}/userStores/{user_store_id}.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`
}

type UserStoreParameters struct {

	// The resource name of the default license config assigned to users created in
	// this user store. Format:
	// projects/{project}/locations/{location}/licenseConfigs/{license_config}.
	// If enableLicenseAutoRegister is true, new users will automatically
	// register under the default subscription.
	// If the default license config doesn't have remaining license seats left,
	// new users will not be assigned with license.
	// +kubebuilder:validation:Optional
	DefaultLicenseConfig *string `json:"defaultLicenseConfig,omitempty" tf:"default_license_config,omitempty"`

	// Whether to enable automatic license update for users with expired licenses
	// in this user store. If enabled, users with expired licenses will
	// automatically be updated to the default subscription if there are
	// remaining license seats.
	// +kubebuilder:validation:Optional
	EnableExpiredLicenseAutoUpdate *bool `json:"enableExpiredLicenseAutoUpdate,omitempty" tf:"enable_expired_license_auto_update,omitempty"`

	// Whether to enable automatic license registration for new users created in
	// this user store. If enabled, new users will automatically register under
	// the default subscription.
	// +kubebuilder:validation:Optional
	EnableLicenseAutoRegister *bool `json:"enableLicenseAutoRegister,omitempty" tf:"enable_license_auto_register,omitempty"`

	// The geographic location where the data store should reside. The value can
	// only be one of "global", "us" and "eu".
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/namespaced/discoveryengine/v1beta1.LicenseConfig
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("location",false)
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// Reference to a LicenseConfig in discoveryengine to populate location.
	// +kubebuilder:validation:Optional
	LocationRef *v1.NamespacedReference `json:"locationRef,omitempty" tf:"-"`

	// Selector for a LicenseConfig in discoveryengine to populate location.
	// +kubebuilder:validation:Optional
	LocationSelector *v1.NamespacedSelector `json:"locationSelector,omitempty" tf:"-"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`
}

// UserStoreSpec defines the desired state of UserStore
type UserStoreSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            UserStoreParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserStoreInitParameters `json:"initProvider,omitempty"`
}

// UserStoreStatus defines the observed state of UserStore.
type UserStoreStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserStoreObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// UserStore is the Schema for the UserStores API. Represents a user store.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gcp}
type UserStore struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              UserStoreSpec   `json:"spec"`
	Status            UserStoreStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserStoreList contains a list of UserStores
type UserStoreList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UserStore `json:"items"`
}

// Repository type metadata.
var (
	UserStore_Kind             = "UserStore"
	UserStore_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UserStore_Kind}.String()
	UserStore_KindAPIVersion   = UserStore_Kind + "." + CRDGroupVersion.String()
	UserStore_GroupVersionKind = CRDGroupVersion.WithKind(UserStore_Kind)
)

func init() {
	SchemeBuilder.Register(&UserStore{}, &UserStoreList{})
}
