apiVersion: compute.gcp.m.upbound.io/v1beta1
kind: BackendBucket
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/backendbucket
  labels:
    testing.upbound.io/example-name: image_backend
  name: image-backend
  namespace: upbound-system
spec:
  forProvider:
    bucketName: ${google_storage_bucket.image_bucket.name}
    description: Contains beautiful images
    enableCdn: true
