apiVersion: compute.gcp.m.upbound.io/v1beta1
kind: RegionNetworkEndpointGroup
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/regionnetworkendpointgroup
  labels:
    testing.upbound.io/example-name: function_neg
  name: function-neg
  namespace: upbound-system
spec:
  forProvider:
    cloudFunction:
    - function: ${google_cloudfunctions_function.function_neg.name}
    networkEndpointType: SERVERLESS
    region: us-central1
