apiVersion: compute.gcp.upbound.io/v1beta1
kind: FirewallPolicyAssociation
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/firewallpolicyassociation
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    attachmentTarget: ${google_folder.folder.name}
    firewallPolicySelector:
      matchLabels:
        testing.upbound.io/example-name: policy
    name: my-association

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: FirewallPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/firewallpolicyassociation
  labels:
    testing.upbound.io/example-name: policy
  name: policy
spec:
  forProvider:
    description: Example Resource
    parent: organizations/123456789
    shortName: my-policy
