apiVersion: compute.gcp.upbound.io/v1beta1
kind: NetworkAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/networkattachment
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    connectionPreference: ACCEPT_MANUAL
    description: basic network attachment description
    producerAcceptLists:
    - ${google_project.accepted_producer_project.project_id}
    producerRejectLists:
    - ${google_project.rejected_producer_project.project_id}
    region: us-central1
    subnetworksRefs:
    - name: default

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/networkattachment
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    autoCreateSubnetworks: false

---

apiVersion: compute.gcp.upbound.io/v1beta2
kind: Subnetwork
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/networkattachment
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    ipCidrRange: 10.0.0.0/16
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    region: us-central1
