apiVersion: compute.gcp.upbound.io/v1beta1
kind: NetworkFirewallPolicyRule
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/networkfirewallpolicyrule
  labels:
    testing.upbound.io/example-name: primary
  name: primary
spec:
  forProvider:
    action: allow
    description: This is a simple rule description
    direction: INGRESS
    disabled: false
    enableLogging: true
    firewallPolicySelector:
      matchLabels:
        testing.upbound.io/example-name: basic_network_firewall_policy
    match:
    - layer4Configs:
      - ipProtocol: all
      srcAddressGroups:
      - ${google_network_security_address_group.basic_global_networksecurity_address_group.id}
      srcFqdns:
      - google.com
      srcIpRanges:
      - 10.100.0.1/32
      srcRegionCodes:
      - US
      srcSecureTags:
      - name: ${google_tags_tag_value.basic_value.id}
      srcThreatIntelligences:
      - iplist-known-malicious-ips
    priority: 1000
    ruleName: test-rule
    targetServiceAccounts:
    - my@service-account.com

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/networkfirewallpolicyrule
  labels:
    testing.upbound.io/example-name: basic_network
  name: basic-network
spec:
  forProvider: {}

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: NetworkFirewallPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/networkfirewallpolicyrule
  labels:
    testing.upbound.io/example-name: basic_network_firewall_policy
  name: basic-network-firewall-policy
spec:
  forProvider:
    description: Sample global network firewall policy
    project: my-project-name
