//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountIAMMember) DeepCopyInto(out *AccountIAMMember) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountIAMMember.
func (in *AccountIAMMember) DeepCopy() *AccountIAMMember {
	if in == nil {
		return nil
	}
	out := new(AccountIAMMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountIAMMember) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountIAMMemberInitParameters) DeepCopyInto(out *AccountIAMMemberInitParameters) {
	*out = *in
	if in.BillingAccountID != nil {
		in, out := &in.BillingAccountID, &out.BillingAccountID
		*out = new(string)
		**out = **in
	}
	if in.Condition != nil {
		in, out := &in.Condition, &out.Condition
		*out = new(ConditionInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Member != nil {
		in, out := &in.Member, &out.Member
		*out = new(string)
		**out = **in
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountIAMMemberInitParameters.
func (in *AccountIAMMemberInitParameters) DeepCopy() *AccountIAMMemberInitParameters {
	if in == nil {
		return nil
	}
	out := new(AccountIAMMemberInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountIAMMemberList) DeepCopyInto(out *AccountIAMMemberList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccountIAMMember, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountIAMMemberList.
func (in *AccountIAMMemberList) DeepCopy() *AccountIAMMemberList {
	if in == nil {
		return nil
	}
	out := new(AccountIAMMemberList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountIAMMemberList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountIAMMemberObservation) DeepCopyInto(out *AccountIAMMemberObservation) {
	*out = *in
	if in.BillingAccountID != nil {
		in, out := &in.BillingAccountID, &out.BillingAccountID
		*out = new(string)
		**out = **in
	}
	if in.Condition != nil {
		in, out := &in.Condition, &out.Condition
		*out = new(ConditionObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Etag != nil {
		in, out := &in.Etag, &out.Etag
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Member != nil {
		in, out := &in.Member, &out.Member
		*out = new(string)
		**out = **in
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountIAMMemberObservation.
func (in *AccountIAMMemberObservation) DeepCopy() *AccountIAMMemberObservation {
	if in == nil {
		return nil
	}
	out := new(AccountIAMMemberObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountIAMMemberParameters) DeepCopyInto(out *AccountIAMMemberParameters) {
	*out = *in
	if in.BillingAccountID != nil {
		in, out := &in.BillingAccountID, &out.BillingAccountID
		*out = new(string)
		**out = **in
	}
	if in.Condition != nil {
		in, out := &in.Condition, &out.Condition
		*out = new(ConditionParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Member != nil {
		in, out := &in.Member, &out.Member
		*out = new(string)
		**out = **in
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountIAMMemberParameters.
func (in *AccountIAMMemberParameters) DeepCopy() *AccountIAMMemberParameters {
	if in == nil {
		return nil
	}
	out := new(AccountIAMMemberParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountIAMMemberSpec) DeepCopyInto(out *AccountIAMMemberSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountIAMMemberSpec.
func (in *AccountIAMMemberSpec) DeepCopy() *AccountIAMMemberSpec {
	if in == nil {
		return nil
	}
	out := new(AccountIAMMemberSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountIAMMemberStatus) DeepCopyInto(out *AccountIAMMemberStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountIAMMemberStatus.
func (in *AccountIAMMemberStatus) DeepCopy() *AccountIAMMemberStatus {
	if in == nil {
		return nil
	}
	out := new(AccountIAMMemberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllUpdatesRuleInitParameters) DeepCopyInto(out *AllUpdatesRuleInitParameters) {
	*out = *in
	if in.DisableDefaultIAMRecipients != nil {
		in, out := &in.DisableDefaultIAMRecipients, &out.DisableDefaultIAMRecipients
		*out = new(bool)
		**out = **in
	}
	if in.EnableProjectLevelRecipients != nil {
		in, out := &in.EnableProjectLevelRecipients, &out.EnableProjectLevelRecipients
		*out = new(bool)
		**out = **in
	}
	if in.MonitoringNotificationChannels != nil {
		in, out := &in.MonitoringNotificationChannels, &out.MonitoringNotificationChannels
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.MonitoringNotificationChannelsRefs != nil {
		in, out := &in.MonitoringNotificationChannelsRefs, &out.MonitoringNotificationChannelsRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MonitoringNotificationChannelsSelector != nil {
		in, out := &in.MonitoringNotificationChannelsSelector, &out.MonitoringNotificationChannelsSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.PubsubTopic != nil {
		in, out := &in.PubsubTopic, &out.PubsubTopic
		*out = new(string)
		**out = **in
	}
	if in.PubsubTopicRef != nil {
		in, out := &in.PubsubTopicRef, &out.PubsubTopicRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.PubsubTopicSelector != nil {
		in, out := &in.PubsubTopicSelector, &out.PubsubTopicSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.SchemaVersion != nil {
		in, out := &in.SchemaVersion, &out.SchemaVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllUpdatesRuleInitParameters.
func (in *AllUpdatesRuleInitParameters) DeepCopy() *AllUpdatesRuleInitParameters {
	if in == nil {
		return nil
	}
	out := new(AllUpdatesRuleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllUpdatesRuleObservation) DeepCopyInto(out *AllUpdatesRuleObservation) {
	*out = *in
	if in.DisableDefaultIAMRecipients != nil {
		in, out := &in.DisableDefaultIAMRecipients, &out.DisableDefaultIAMRecipients
		*out = new(bool)
		**out = **in
	}
	if in.EnableProjectLevelRecipients != nil {
		in, out := &in.EnableProjectLevelRecipients, &out.EnableProjectLevelRecipients
		*out = new(bool)
		**out = **in
	}
	if in.MonitoringNotificationChannels != nil {
		in, out := &in.MonitoringNotificationChannels, &out.MonitoringNotificationChannels
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PubsubTopic != nil {
		in, out := &in.PubsubTopic, &out.PubsubTopic
		*out = new(string)
		**out = **in
	}
	if in.SchemaVersion != nil {
		in, out := &in.SchemaVersion, &out.SchemaVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllUpdatesRuleObservation.
func (in *AllUpdatesRuleObservation) DeepCopy() *AllUpdatesRuleObservation {
	if in == nil {
		return nil
	}
	out := new(AllUpdatesRuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllUpdatesRuleParameters) DeepCopyInto(out *AllUpdatesRuleParameters) {
	*out = *in
	if in.DisableDefaultIAMRecipients != nil {
		in, out := &in.DisableDefaultIAMRecipients, &out.DisableDefaultIAMRecipients
		*out = new(bool)
		**out = **in
	}
	if in.EnableProjectLevelRecipients != nil {
		in, out := &in.EnableProjectLevelRecipients, &out.EnableProjectLevelRecipients
		*out = new(bool)
		**out = **in
	}
	if in.MonitoringNotificationChannels != nil {
		in, out := &in.MonitoringNotificationChannels, &out.MonitoringNotificationChannels
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.MonitoringNotificationChannelsRefs != nil {
		in, out := &in.MonitoringNotificationChannelsRefs, &out.MonitoringNotificationChannelsRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MonitoringNotificationChannelsSelector != nil {
		in, out := &in.MonitoringNotificationChannelsSelector, &out.MonitoringNotificationChannelsSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.PubsubTopic != nil {
		in, out := &in.PubsubTopic, &out.PubsubTopic
		*out = new(string)
		**out = **in
	}
	if in.PubsubTopicRef != nil {
		in, out := &in.PubsubTopicRef, &out.PubsubTopicRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.PubsubTopicSelector != nil {
		in, out := &in.PubsubTopicSelector, &out.PubsubTopicSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.SchemaVersion != nil {
		in, out := &in.SchemaVersion, &out.SchemaVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllUpdatesRuleParameters.
func (in *AllUpdatesRuleParameters) DeepCopy() *AllUpdatesRuleParameters {
	if in == nil {
		return nil
	}
	out := new(AllUpdatesRuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmountInitParameters) DeepCopyInto(out *AmountInitParameters) {
	*out = *in
	if in.LastPeriodAmount != nil {
		in, out := &in.LastPeriodAmount, &out.LastPeriodAmount
		*out = new(bool)
		**out = **in
	}
	if in.SpecifiedAmount != nil {
		in, out := &in.SpecifiedAmount, &out.SpecifiedAmount
		*out = new(SpecifiedAmountInitParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmountInitParameters.
func (in *AmountInitParameters) DeepCopy() *AmountInitParameters {
	if in == nil {
		return nil
	}
	out := new(AmountInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmountObservation) DeepCopyInto(out *AmountObservation) {
	*out = *in
	if in.LastPeriodAmount != nil {
		in, out := &in.LastPeriodAmount, &out.LastPeriodAmount
		*out = new(bool)
		**out = **in
	}
	if in.SpecifiedAmount != nil {
		in, out := &in.SpecifiedAmount, &out.SpecifiedAmount
		*out = new(SpecifiedAmountObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmountObservation.
func (in *AmountObservation) DeepCopy() *AmountObservation {
	if in == nil {
		return nil
	}
	out := new(AmountObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmountParameters) DeepCopyInto(out *AmountParameters) {
	*out = *in
	if in.LastPeriodAmount != nil {
		in, out := &in.LastPeriodAmount, &out.LastPeriodAmount
		*out = new(bool)
		**out = **in
	}
	if in.SpecifiedAmount != nil {
		in, out := &in.SpecifiedAmount, &out.SpecifiedAmount
		*out = new(SpecifiedAmountParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmountParameters.
func (in *AmountParameters) DeepCopy() *AmountParameters {
	if in == nil {
		return nil
	}
	out := new(AmountParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Budget) DeepCopyInto(out *Budget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Budget.
func (in *Budget) DeepCopy() *Budget {
	if in == nil {
		return nil
	}
	out := new(Budget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Budget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetFilterInitParameters) DeepCopyInto(out *BudgetFilterInitParameters) {
	*out = *in
	if in.CalendarPeriod != nil {
		in, out := &in.CalendarPeriod, &out.CalendarPeriod
		*out = new(string)
		**out = **in
	}
	if in.CreditTypes != nil {
		in, out := &in.CreditTypes, &out.CreditTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CreditTypesTreatment != nil {
		in, out := &in.CreditTypesTreatment, &out.CreditTypesTreatment
		*out = new(string)
		**out = **in
	}
	if in.CustomPeriod != nil {
		in, out := &in.CustomPeriod, &out.CustomPeriod
		*out = new(CustomPeriodInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Projects != nil {
		in, out := &in.Projects, &out.Projects
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ResourceAncestors != nil {
		in, out := &in.ResourceAncestors, &out.ResourceAncestors
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Subaccounts != nil {
		in, out := &in.Subaccounts, &out.Subaccounts
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetFilterInitParameters.
func (in *BudgetFilterInitParameters) DeepCopy() *BudgetFilterInitParameters {
	if in == nil {
		return nil
	}
	out := new(BudgetFilterInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetFilterObservation) DeepCopyInto(out *BudgetFilterObservation) {
	*out = *in
	if in.CalendarPeriod != nil {
		in, out := &in.CalendarPeriod, &out.CalendarPeriod
		*out = new(string)
		**out = **in
	}
	if in.CreditTypes != nil {
		in, out := &in.CreditTypes, &out.CreditTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CreditTypesTreatment != nil {
		in, out := &in.CreditTypesTreatment, &out.CreditTypesTreatment
		*out = new(string)
		**out = **in
	}
	if in.CustomPeriod != nil {
		in, out := &in.CustomPeriod, &out.CustomPeriod
		*out = new(CustomPeriodObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Projects != nil {
		in, out := &in.Projects, &out.Projects
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ResourceAncestors != nil {
		in, out := &in.ResourceAncestors, &out.ResourceAncestors
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Subaccounts != nil {
		in, out := &in.Subaccounts, &out.Subaccounts
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetFilterObservation.
func (in *BudgetFilterObservation) DeepCopy() *BudgetFilterObservation {
	if in == nil {
		return nil
	}
	out := new(BudgetFilterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetFilterParameters) DeepCopyInto(out *BudgetFilterParameters) {
	*out = *in
	if in.CalendarPeriod != nil {
		in, out := &in.CalendarPeriod, &out.CalendarPeriod
		*out = new(string)
		**out = **in
	}
	if in.CreditTypes != nil {
		in, out := &in.CreditTypes, &out.CreditTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CreditTypesTreatment != nil {
		in, out := &in.CreditTypesTreatment, &out.CreditTypesTreatment
		*out = new(string)
		**out = **in
	}
	if in.CustomPeriod != nil {
		in, out := &in.CustomPeriod, &out.CustomPeriod
		*out = new(CustomPeriodParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Projects != nil {
		in, out := &in.Projects, &out.Projects
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ResourceAncestors != nil {
		in, out := &in.ResourceAncestors, &out.ResourceAncestors
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Subaccounts != nil {
		in, out := &in.Subaccounts, &out.Subaccounts
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetFilterParameters.
func (in *BudgetFilterParameters) DeepCopy() *BudgetFilterParameters {
	if in == nil {
		return nil
	}
	out := new(BudgetFilterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetInitParameters) DeepCopyInto(out *BudgetInitParameters) {
	*out = *in
	if in.AllUpdatesRule != nil {
		in, out := &in.AllUpdatesRule, &out.AllUpdatesRule
		*out = new(AllUpdatesRuleInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(AmountInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.BillingAccount != nil {
		in, out := &in.BillingAccount, &out.BillingAccount
		*out = new(string)
		**out = **in
	}
	if in.BudgetFilter != nil {
		in, out := &in.BudgetFilter, &out.BudgetFilter
		*out = new(BudgetFilterInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.OwnershipScope != nil {
		in, out := &in.OwnershipScope, &out.OwnershipScope
		*out = new(string)
		**out = **in
	}
	if in.ThresholdRules != nil {
		in, out := &in.ThresholdRules, &out.ThresholdRules
		*out = make([]ThresholdRulesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetInitParameters.
func (in *BudgetInitParameters) DeepCopy() *BudgetInitParameters {
	if in == nil {
		return nil
	}
	out := new(BudgetInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetList) DeepCopyInto(out *BudgetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Budget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetList.
func (in *BudgetList) DeepCopy() *BudgetList {
	if in == nil {
		return nil
	}
	out := new(BudgetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BudgetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetObservation) DeepCopyInto(out *BudgetObservation) {
	*out = *in
	if in.AllUpdatesRule != nil {
		in, out := &in.AllUpdatesRule, &out.AllUpdatesRule
		*out = new(AllUpdatesRuleObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(AmountObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.BillingAccount != nil {
		in, out := &in.BillingAccount, &out.BillingAccount
		*out = new(string)
		**out = **in
	}
	if in.BudgetFilter != nil {
		in, out := &in.BudgetFilter, &out.BudgetFilter
		*out = new(BudgetFilterObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OwnershipScope != nil {
		in, out := &in.OwnershipScope, &out.OwnershipScope
		*out = new(string)
		**out = **in
	}
	if in.ThresholdRules != nil {
		in, out := &in.ThresholdRules, &out.ThresholdRules
		*out = make([]ThresholdRulesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetObservation.
func (in *BudgetObservation) DeepCopy() *BudgetObservation {
	if in == nil {
		return nil
	}
	out := new(BudgetObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetParameters) DeepCopyInto(out *BudgetParameters) {
	*out = *in
	if in.AllUpdatesRule != nil {
		in, out := &in.AllUpdatesRule, &out.AllUpdatesRule
		*out = new(AllUpdatesRuleParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(AmountParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.BillingAccount != nil {
		in, out := &in.BillingAccount, &out.BillingAccount
		*out = new(string)
		**out = **in
	}
	if in.BudgetFilter != nil {
		in, out := &in.BudgetFilter, &out.BudgetFilter
		*out = new(BudgetFilterParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.OwnershipScope != nil {
		in, out := &in.OwnershipScope, &out.OwnershipScope
		*out = new(string)
		**out = **in
	}
	if in.ThresholdRules != nil {
		in, out := &in.ThresholdRules, &out.ThresholdRules
		*out = make([]ThresholdRulesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetParameters.
func (in *BudgetParameters) DeepCopy() *BudgetParameters {
	if in == nil {
		return nil
	}
	out := new(BudgetParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetSpec) DeepCopyInto(out *BudgetSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetSpec.
func (in *BudgetSpec) DeepCopy() *BudgetSpec {
	if in == nil {
		return nil
	}
	out := new(BudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetStatus) DeepCopyInto(out *BudgetStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetStatus.
func (in *BudgetStatus) DeepCopy() *BudgetStatus {
	if in == nil {
		return nil
	}
	out := new(BudgetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionInitParameters) DeepCopyInto(out *ConditionInitParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionInitParameters.
func (in *ConditionInitParameters) DeepCopy() *ConditionInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConditionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionObservation) DeepCopyInto(out *ConditionObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionObservation.
func (in *ConditionObservation) DeepCopy() *ConditionObservation {
	if in == nil {
		return nil
	}
	out := new(ConditionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionParameters) DeepCopyInto(out *ConditionParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionParameters.
func (in *ConditionParameters) DeepCopy() *ConditionParameters {
	if in == nil {
		return nil
	}
	out := new(ConditionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomPeriodInitParameters) DeepCopyInto(out *CustomPeriodInitParameters) {
	*out = *in
	if in.EndDate != nil {
		in, out := &in.EndDate, &out.EndDate
		*out = new(EndDateInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.StartDate != nil {
		in, out := &in.StartDate, &out.StartDate
		*out = new(StartDateInitParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomPeriodInitParameters.
func (in *CustomPeriodInitParameters) DeepCopy() *CustomPeriodInitParameters {
	if in == nil {
		return nil
	}
	out := new(CustomPeriodInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomPeriodObservation) DeepCopyInto(out *CustomPeriodObservation) {
	*out = *in
	if in.EndDate != nil {
		in, out := &in.EndDate, &out.EndDate
		*out = new(EndDateObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.StartDate != nil {
		in, out := &in.StartDate, &out.StartDate
		*out = new(StartDateObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomPeriodObservation.
func (in *CustomPeriodObservation) DeepCopy() *CustomPeriodObservation {
	if in == nil {
		return nil
	}
	out := new(CustomPeriodObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomPeriodParameters) DeepCopyInto(out *CustomPeriodParameters) {
	*out = *in
	if in.EndDate != nil {
		in, out := &in.EndDate, &out.EndDate
		*out = new(EndDateParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.StartDate != nil {
		in, out := &in.StartDate, &out.StartDate
		*out = new(StartDateParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomPeriodParameters.
func (in *CustomPeriodParameters) DeepCopy() *CustomPeriodParameters {
	if in == nil {
		return nil
	}
	out := new(CustomPeriodParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndDateInitParameters) DeepCopyInto(out *EndDateInitParameters) {
	*out = *in
	if in.Day != nil {
		in, out := &in.Day, &out.Day
		*out = new(float64)
		**out = **in
	}
	if in.Month != nil {
		in, out := &in.Month, &out.Month
		*out = new(float64)
		**out = **in
	}
	if in.Year != nil {
		in, out := &in.Year, &out.Year
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndDateInitParameters.
func (in *EndDateInitParameters) DeepCopy() *EndDateInitParameters {
	if in == nil {
		return nil
	}
	out := new(EndDateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndDateObservation) DeepCopyInto(out *EndDateObservation) {
	*out = *in
	if in.Day != nil {
		in, out := &in.Day, &out.Day
		*out = new(float64)
		**out = **in
	}
	if in.Month != nil {
		in, out := &in.Month, &out.Month
		*out = new(float64)
		**out = **in
	}
	if in.Year != nil {
		in, out := &in.Year, &out.Year
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndDateObservation.
func (in *EndDateObservation) DeepCopy() *EndDateObservation {
	if in == nil {
		return nil
	}
	out := new(EndDateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndDateParameters) DeepCopyInto(out *EndDateParameters) {
	*out = *in
	if in.Day != nil {
		in, out := &in.Day, &out.Day
		*out = new(float64)
		**out = **in
	}
	if in.Month != nil {
		in, out := &in.Month, &out.Month
		*out = new(float64)
		**out = **in
	}
	if in.Year != nil {
		in, out := &in.Year, &out.Year
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndDateParameters.
func (in *EndDateParameters) DeepCopy() *EndDateParameters {
	if in == nil {
		return nil
	}
	out := new(EndDateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectInfo) DeepCopyInto(out *ProjectInfo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectInfo.
func (in *ProjectInfo) DeepCopy() *ProjectInfo {
	if in == nil {
		return nil
	}
	out := new(ProjectInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectInfo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectInfoInitParameters) DeepCopyInto(out *ProjectInfoInitParameters) {
	*out = *in
	if in.BillingAccount != nil {
		in, out := &in.BillingAccount, &out.BillingAccount
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectInfoInitParameters.
func (in *ProjectInfoInitParameters) DeepCopy() *ProjectInfoInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProjectInfoInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectInfoList) DeepCopyInto(out *ProjectInfoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProjectInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectInfoList.
func (in *ProjectInfoList) DeepCopy() *ProjectInfoList {
	if in == nil {
		return nil
	}
	out := new(ProjectInfoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectInfoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectInfoObservation) DeepCopyInto(out *ProjectInfoObservation) {
	*out = *in
	if in.BillingAccount != nil {
		in, out := &in.BillingAccount, &out.BillingAccount
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectInfoObservation.
func (in *ProjectInfoObservation) DeepCopy() *ProjectInfoObservation {
	if in == nil {
		return nil
	}
	out := new(ProjectInfoObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectInfoParameters) DeepCopyInto(out *ProjectInfoParameters) {
	*out = *in
	if in.BillingAccount != nil {
		in, out := &in.BillingAccount, &out.BillingAccount
		*out = new(string)
		**out = **in
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectSelector != nil {
		in, out := &in.ProjectSelector, &out.ProjectSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectInfoParameters.
func (in *ProjectInfoParameters) DeepCopy() *ProjectInfoParameters {
	if in == nil {
		return nil
	}
	out := new(ProjectInfoParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectInfoSpec) DeepCopyInto(out *ProjectInfoSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectInfoSpec.
func (in *ProjectInfoSpec) DeepCopy() *ProjectInfoSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectInfoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectInfoStatus) DeepCopyInto(out *ProjectInfoStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectInfoStatus.
func (in *ProjectInfoStatus) DeepCopy() *ProjectInfoStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectInfoStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecifiedAmountInitParameters) DeepCopyInto(out *SpecifiedAmountInitParameters) {
	*out = *in
	if in.CurrencyCode != nil {
		in, out := &in.CurrencyCode, &out.CurrencyCode
		*out = new(string)
		**out = **in
	}
	if in.Nanos != nil {
		in, out := &in.Nanos, &out.Nanos
		*out = new(float64)
		**out = **in
	}
	if in.Units != nil {
		in, out := &in.Units, &out.Units
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecifiedAmountInitParameters.
func (in *SpecifiedAmountInitParameters) DeepCopy() *SpecifiedAmountInitParameters {
	if in == nil {
		return nil
	}
	out := new(SpecifiedAmountInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecifiedAmountObservation) DeepCopyInto(out *SpecifiedAmountObservation) {
	*out = *in
	if in.CurrencyCode != nil {
		in, out := &in.CurrencyCode, &out.CurrencyCode
		*out = new(string)
		**out = **in
	}
	if in.Nanos != nil {
		in, out := &in.Nanos, &out.Nanos
		*out = new(float64)
		**out = **in
	}
	if in.Units != nil {
		in, out := &in.Units, &out.Units
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecifiedAmountObservation.
func (in *SpecifiedAmountObservation) DeepCopy() *SpecifiedAmountObservation {
	if in == nil {
		return nil
	}
	out := new(SpecifiedAmountObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecifiedAmountParameters) DeepCopyInto(out *SpecifiedAmountParameters) {
	*out = *in
	if in.CurrencyCode != nil {
		in, out := &in.CurrencyCode, &out.CurrencyCode
		*out = new(string)
		**out = **in
	}
	if in.Nanos != nil {
		in, out := &in.Nanos, &out.Nanos
		*out = new(float64)
		**out = **in
	}
	if in.Units != nil {
		in, out := &in.Units, &out.Units
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecifiedAmountParameters.
func (in *SpecifiedAmountParameters) DeepCopy() *SpecifiedAmountParameters {
	if in == nil {
		return nil
	}
	out := new(SpecifiedAmountParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartDateInitParameters) DeepCopyInto(out *StartDateInitParameters) {
	*out = *in
	if in.Day != nil {
		in, out := &in.Day, &out.Day
		*out = new(float64)
		**out = **in
	}
	if in.Month != nil {
		in, out := &in.Month, &out.Month
		*out = new(float64)
		**out = **in
	}
	if in.Year != nil {
		in, out := &in.Year, &out.Year
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartDateInitParameters.
func (in *StartDateInitParameters) DeepCopy() *StartDateInitParameters {
	if in == nil {
		return nil
	}
	out := new(StartDateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartDateObservation) DeepCopyInto(out *StartDateObservation) {
	*out = *in
	if in.Day != nil {
		in, out := &in.Day, &out.Day
		*out = new(float64)
		**out = **in
	}
	if in.Month != nil {
		in, out := &in.Month, &out.Month
		*out = new(float64)
		**out = **in
	}
	if in.Year != nil {
		in, out := &in.Year, &out.Year
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartDateObservation.
func (in *StartDateObservation) DeepCopy() *StartDateObservation {
	if in == nil {
		return nil
	}
	out := new(StartDateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartDateParameters) DeepCopyInto(out *StartDateParameters) {
	*out = *in
	if in.Day != nil {
		in, out := &in.Day, &out.Day
		*out = new(float64)
		**out = **in
	}
	if in.Month != nil {
		in, out := &in.Month, &out.Month
		*out = new(float64)
		**out = **in
	}
	if in.Year != nil {
		in, out := &in.Year, &out.Year
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartDateParameters.
func (in *StartDateParameters) DeepCopy() *StartDateParameters {
	if in == nil {
		return nil
	}
	out := new(StartDateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThresholdRulesInitParameters) DeepCopyInto(out *ThresholdRulesInitParameters) {
	*out = *in
	if in.SpendBasis != nil {
		in, out := &in.SpendBasis, &out.SpendBasis
		*out = new(string)
		**out = **in
	}
	if in.ThresholdPercent != nil {
		in, out := &in.ThresholdPercent, &out.ThresholdPercent
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThresholdRulesInitParameters.
func (in *ThresholdRulesInitParameters) DeepCopy() *ThresholdRulesInitParameters {
	if in == nil {
		return nil
	}
	out := new(ThresholdRulesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThresholdRulesObservation) DeepCopyInto(out *ThresholdRulesObservation) {
	*out = *in
	if in.SpendBasis != nil {
		in, out := &in.SpendBasis, &out.SpendBasis
		*out = new(string)
		**out = **in
	}
	if in.ThresholdPercent != nil {
		in, out := &in.ThresholdPercent, &out.ThresholdPercent
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThresholdRulesObservation.
func (in *ThresholdRulesObservation) DeepCopy() *ThresholdRulesObservation {
	if in == nil {
		return nil
	}
	out := new(ThresholdRulesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThresholdRulesParameters) DeepCopyInto(out *ThresholdRulesParameters) {
	*out = *in
	if in.SpendBasis != nil {
		in, out := &in.SpendBasis, &out.SpendBasis
		*out = new(string)
		**out = **in
	}
	if in.ThresholdPercent != nil {
		in, out := &in.ThresholdPercent, &out.ThresholdPercent
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThresholdRulesParameters.
func (in *ThresholdRulesParameters) DeepCopy() *ThresholdRulesParameters {
	if in == nil {
		return nil
	}
	out := new(ThresholdRulesParameters)
	in.DeepCopyInto(out)
	return out
}
