// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by angryjet. DO NOT EDIT.
// Code transformed by upjet. DO NOT EDIT.

package v1beta1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	xpresource "github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	apisresolver "github.com/upbound/provider-gcp/internal/apis"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

func (mg *Budget) ResolveReferences( // ResolveReferences of this Budget.
	ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var mrsp reference.MultiResolutionResponse
	var err error

	if mg.Spec.ForProvider.AllUpdatesRule != nil {
		{
			m, l, err = apisresolver.GetManagedResource("monitoring.gcp.upbound.io", "v1beta2", "NotificationChannel", "NotificationChannelList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
				CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.AllUpdatesRule.MonitoringNotificationChannels),
				Extract:       resource.ExtractResourceID(),
				Namespace:     mg.GetNamespace(),
				References:    mg.Spec.ForProvider.AllUpdatesRule.MonitoringNotificationChannelsRefs,
				Selector:      mg.Spec.ForProvider.AllUpdatesRule.MonitoringNotificationChannelsSelector,
				To:            reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.AllUpdatesRule.MonitoringNotificationChannels")
		}
		mg.Spec.ForProvider.AllUpdatesRule.MonitoringNotificationChannels = reference.ToPtrValues(mrsp.ResolvedValues)
		mg.Spec.ForProvider.AllUpdatesRule.MonitoringNotificationChannelsRefs = mrsp.ResolvedReferences

	}
	if mg.Spec.ForProvider.AllUpdatesRule != nil {
		{
			m, l, err = apisresolver.GetManagedResource("pubsub.gcp.upbound.io", "v1beta2", "Topic", "TopicList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.AllUpdatesRule.PubsubTopic),
				Extract:      reference.ExternalName(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.AllUpdatesRule.PubsubTopicRef,
				Selector:     mg.Spec.ForProvider.AllUpdatesRule.PubsubTopicSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.AllUpdatesRule.PubsubTopic")
		}
		mg.Spec.ForProvider.AllUpdatesRule.PubsubTopic = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.AllUpdatesRule.PubsubTopicRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.AllUpdatesRule != nil {
		{
			m, l, err = apisresolver.GetManagedResource("monitoring.gcp.upbound.io", "v1beta2", "NotificationChannel", "NotificationChannelList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
				CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.AllUpdatesRule.MonitoringNotificationChannels),
				Extract:       resource.ExtractResourceID(),
				Namespace:     mg.GetNamespace(),
				References:    mg.Spec.InitProvider.AllUpdatesRule.MonitoringNotificationChannelsRefs,
				Selector:      mg.Spec.InitProvider.AllUpdatesRule.MonitoringNotificationChannelsSelector,
				To:            reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.AllUpdatesRule.MonitoringNotificationChannels")
		}
		mg.Spec.InitProvider.AllUpdatesRule.MonitoringNotificationChannels = reference.ToPtrValues(mrsp.ResolvedValues)
		mg.Spec.InitProvider.AllUpdatesRule.MonitoringNotificationChannelsRefs = mrsp.ResolvedReferences

	}
	if mg.Spec.InitProvider.AllUpdatesRule != nil {
		{
			m, l, err = apisresolver.GetManagedResource("pubsub.gcp.upbound.io", "v1beta2", "Topic", "TopicList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.AllUpdatesRule.PubsubTopic),
				Extract:      reference.ExternalName(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.AllUpdatesRule.PubsubTopicRef,
				Selector:     mg.Spec.InitProvider.AllUpdatesRule.PubsubTopicSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.AllUpdatesRule.PubsubTopic")
		}
		mg.Spec.InitProvider.AllUpdatesRule.PubsubTopic = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.AllUpdatesRule.PubsubTopicRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this ProjectInfo.
func (mg *ProjectInfo) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("cloudplatform.gcp.upbound.io", "v1beta1", "Project", "ProjectList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Project),
			Extract:      resource.ExtractParamPath("project_id", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.ProjectRef,
			Selector:     mg.Spec.ForProvider.ProjectSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Project")
	}
	mg.Spec.ForProvider.Project = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectRef = rsp.ResolvedReference

	return nil
}
