// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ProjectInfoInitParameters struct {

	// The ID of the billing account associated with the project, if
	// any. Set to empty string to disable billing for the project.
	// For example, "012345-567890-ABCDEF" or "".
	BillingAccount *string `json:"billingAccount,omitempty" tf:"billing_account,omitempty"`
}

type ProjectInfoObservation struct {

	// The ID of the billing account associated with the project, if
	// any. Set to empty string to disable billing for the project.
	// For example, "012345-567890-ABCDEF" or "".
	BillingAccount *string `json:"billingAccount,omitempty" tf:"billing_account,omitempty"`

	// an identifier for the resource with format projects/{{project}}
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`
}

type ProjectInfoParameters struct {

	// The ID of the billing account associated with the project, if
	// any. Set to empty string to disable billing for the project.
	// For example, "012345-567890-ABCDEF" or "".
	// +kubebuilder:validation:Optional
	BillingAccount *string `json:"billingAccount,omitempty" tf:"billing_account,omitempty"`

	// The ID of the project in which the resource belongs.
	// If it is not provided, the provider project is used.
	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/apis/cluster/cloudplatform/v1beta1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("project_id",false)
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in cloudplatform to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v1.Reference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in cloudplatform to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v1.Selector `json:"projectSelector,omitempty" tf:"-"`
}

// ProjectInfoSpec defines the desired state of ProjectInfo
type ProjectInfoSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ProjectInfoParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectInfoInitParameters `json:"initProvider,omitempty"`
}

// ProjectInfoStatus defines the observed state of ProjectInfo.
type ProjectInfoStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProjectInfoObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ProjectInfo is the Schema for the ProjectInfos API. Billing information for a project.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,gcp}
type ProjectInfo struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.billingAccount) || (has(self.initProvider) && has(self.initProvider.billingAccount))",message="spec.forProvider.billingAccount is a required parameter"
	Spec   ProjectInfoSpec   `json:"spec"`
	Status ProjectInfoStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectInfoList contains a list of ProjectInfos
type ProjectInfoList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProjectInfo `json:"items"`
}

// Repository type metadata.
var (
	ProjectInfo_Kind             = "ProjectInfo"
	ProjectInfo_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProjectInfo_Kind}.String()
	ProjectInfo_KindAPIVersion   = ProjectInfo_Kind + "." + CRDGroupVersion.String()
	ProjectInfo_GroupVersionKind = CRDGroupVersion.WithKind(ProjectInfo_Kind)
)

func init() {
	SchemeBuilder.Register(&ProjectInfo{}, &ProjectInfoList{})
}
