// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type V2ServiceIAMMemberConditionInitParameters struct {
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type V2ServiceIAMMemberConditionObservation struct {
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type V2ServiceIAMMemberConditionParameters struct {

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Optional
	Expression *string `json:"expression" tf:"expression,omitempty"`

	// +kubebuilder:validation:Optional
	Title *string `json:"title" tf:"title,omitempty"`
}

type V2ServiceIAMMemberInitParameters struct {
	Condition *V2ServiceIAMMemberConditionInitParameters `json:"condition,omitempty" tf:"condition,omitempty"`

	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	Member *string `json:"member,omitempty" tf:"member,omitempty"`

	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/namespaced/cloudrun/v1beta1.V2Service
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Reference to a V2Service in cloudrun to populate name.
	// +kubebuilder:validation:Optional
	NameRef *v1.NamespacedReference `json:"nameRef,omitempty" tf:"-"`

	// Selector for a V2Service in cloudrun to populate name.
	// +kubebuilder:validation:Optional
	NameSelector *v1.NamespacedSelector `json:"nameSelector,omitempty" tf:"-"`

	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

type V2ServiceIAMMemberObservation struct {
	Condition *V2ServiceIAMMemberConditionObservation `json:"condition,omitempty" tf:"condition,omitempty"`

	Etag *string `json:"etag,omitempty" tf:"etag,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	Member *string `json:"member,omitempty" tf:"member,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

type V2ServiceIAMMemberParameters struct {

	// +kubebuilder:validation:Optional
	Condition *V2ServiceIAMMemberConditionParameters `json:"condition,omitempty" tf:"condition,omitempty"`

	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// +kubebuilder:validation:Optional
	Member *string `json:"member,omitempty" tf:"member,omitempty"`

	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/v2/apis/namespaced/cloudrun/v1beta1.V2Service
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Reference to a V2Service in cloudrun to populate name.
	// +kubebuilder:validation:Optional
	NameRef *v1.NamespacedReference `json:"nameRef,omitempty" tf:"-"`

	// Selector for a V2Service in cloudrun to populate name.
	// +kubebuilder:validation:Optional
	NameSelector *v1.NamespacedSelector `json:"nameSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// +kubebuilder:validation:Optional
	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

// V2ServiceIAMMemberSpec defines the desired state of V2ServiceIAMMember
type V2ServiceIAMMemberSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            V2ServiceIAMMemberParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider V2ServiceIAMMemberInitParameters `json:"initProvider,omitempty"`
}

// V2ServiceIAMMemberStatus defines the observed state of V2ServiceIAMMember.
type V2ServiceIAMMemberStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        V2ServiceIAMMemberObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// V2ServiceIAMMember is the Schema for the V2ServiceIAMMembers API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,gcp}
type V2ServiceIAMMember struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.member) || (has(self.initProvider) && has(self.initProvider.member))",message="spec.forProvider.member is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.role) || (has(self.initProvider) && has(self.initProvider.role))",message="spec.forProvider.role is a required parameter"
	Spec   V2ServiceIAMMemberSpec   `json:"spec"`
	Status V2ServiceIAMMemberStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// V2ServiceIAMMemberList contains a list of V2ServiceIAMMembers
type V2ServiceIAMMemberList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []V2ServiceIAMMember `json:"items"`
}

// Repository type metadata.
var (
	V2ServiceIAMMember_Kind             = "V2ServiceIAMMember"
	V2ServiceIAMMember_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: V2ServiceIAMMember_Kind}.String()
	V2ServiceIAMMember_KindAPIVersion   = V2ServiceIAMMember_Kind + "." + CRDGroupVersion.String()
	V2ServiceIAMMember_GroupVersionKind = CRDGroupVersion.WithKind(V2ServiceIAMMember_Kind)
)

func init() {
	SchemeBuilder.Register(&V2ServiceIAMMember{}, &V2ServiceIAMMemberList{})
}
