apiVersion: compute.gcp.upbound.io/v1beta2
kind: BackendBucket
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta2/backendbucket
  labels:
    testing.upbound.io/example-name: image_backend
  name: image-backend
spec:
  forProvider:
    bucketName: ${google_storage_bucket.image_bucket.name}
    description: Contains beautiful images
    enableCdn: true
